### ISSUE TITLE
callback for rate limiting

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#112]
When using twarc as a library it can be useful to know when you have been rate-limited. It would be useful in these situations to be able to pass `search` a callback to execute, which would be called just before the process goes to sleep:

``` python

def rate_limit(secs):
    print("going to sleep for %s seconds" % secs)

for tweet in twarc.search("obama", rate_limit=rate_limit):
    print(tweet['text'])
```

This was useful for https://github.comDocNow/dnflow which needed to show users that their search job was being rate limited, so they needn't be concerned about the job appearing stalled or failed.

**Comment by dchud** [comment]
Another option might be to add a `--drive-slow` option that would use feedback from API calls to add a fractional delay between calls, ensuring that the rate limit wouldn't be hit.  The added headers in rest API call responses useful for this are documented at:

  https://dev.twitter.com/rest/public/rate-limiting

**Comment by igorbrigadir** [comment]
Going through some old issues: in twarc2 this is a decorator now https://github.com/DocNow/twarc/blob/main/twarc/decorators2.py#L16 and twarc logs rate limit sleeps
