### ISSUE TITLE
allow option to skip json parsing on streams

### ISSUE THREAD

**Issue by dchud** [DocNow/twarc#113]
When using a Twarc.filter() operation (see https://github.com/edsu/twarc/blob/master/twarc.py#L525) and Twarc.sample() (see https://github.com/edsu/twarc/blob/master/twarc.py#L573) twarc will parse the JSON data into a Python object.  This is useful in most cases, but when simply writing the incoming streaming data to a file for later use, it requires re-serializing the JSON back out.

It would be great to have an option to yield the raw data instead in both cases.

**Comment by igorbrigadir** [comment]
Going through closing some old issues: The extra serialization doesn't seem to cost much processing.
