### ISSUE TITLE
twarc-archive.py references a method removed from twarc.py

### ISSUE THREAD

**Issue by nwoodward** [DocNow/twarc#125]
I may be missing something, but the reference to default_config_filename() here (https://github.com/DocNow/twarc/blob/master/utils/twarc-archive.py#L65) throws an error for me, and I think it's because it was removed as part of the configuration refactor in this commit (https://github.com/DocNow/twarc/commit/bfaa9809d2b62d8f32b32410a43a403b6464e8de).

**Comment by edsu** [comment]
Oh, thanks for ticketing this. I think twarc-archive needs to be updated after the v1.0.0 release.

**Comment by nwoodward** [comment]
Thanks, Ed. I noticed the twarc-archive section was removed from the README. If I should be using original twarc for daily archiving then just say the word.

**Comment by edsu** [comment]
Hey @cazzerson thanks for looking into this!
