### ISSUE TITLE
add dehydrate command

### ISSUE THREAD

**Issue by pbinkley** [DocNow/twarc#127]
it would be nice to have a ```twarc dehydrate``` command, to extract the list of tweet ids from a harvest to make it easier to deposit a harvested set into a data repository and share it on http://www.docnow.io/catalog/ . It's not difficult to do with ```utils/ids.py```, but having a parallel to ```twarc hydrate``` would help make this a routine operation. Ideally it would deduplicate as well (though that could always be handled externally).

**Comment by edsu** [comment]
i normally do a `jq -r .id-str tweets.json > ids.txt` but yes, absolutely!
