### ISSUE TITLE
Deleted tweets

### ISSUE THREAD

**Issue by HolzmanoLagrene** [DocNow/twarc#135]
When hydrating, deleted tweets used to show up in the .json-File.
Cant find any of them anymore! Does twarc remove them automatically?

**Comment by edsu** [comment]
twarc doesn't remove them, but Twitter does not let you hydrate an id for a deleted tweet. You can read more about it [here](https://dev.twitter.com/rest/reference/get/statuses/lookup).

**Comment by HolzmanoLagrene** [comment]
Thanks for answering so quick! But did that change lately or was it always like that?

**Comment by edsu** [comment]
I believe Twitter's API has always operated that way, or at least as long as I have been working with it.
