### ISSUE TITLE
replies doesn't get upstream conversation

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#140]
The replies command gets replies to a given tweet. And using replies with --recursive will go and get the replies to those replies. But if the supplied tweet is itself a reply it doesn't go and fetch the upstream conversation. For example consider this conversation thread:

```
      a 
     / \
    b   c
       / \
      d   e
```

If you get the replies to `c` you will get `d` and `e` but not `a` and `b`. This makes sense from the perspective of replies. But from the perspective of getting the entire conversation it is not ideal. 

Maybe it would be good to add another command `conversation` that will fetch the whole thing?

**Comment by todrobbins** [comment]
👍🏻 to a `conversation` command. How does the Twitter API present the relationship between a tweet that is midstream in the conversation? I'm not as well read on the docs.

**Comment by edsu** [comment]
The tweet will have a `in_reply_to_status_id_str` key.

**Comment by edsu** [comment]
I wonder if it might make sense to include quotes of a tweet as well?
