### ISSUE TITLE
Filter on Network.py

### ISSUE THREAD

**Issue by ianmilligan1** [DocNow/twarc#143]
@ruebot and I have been playing with `network.py`, specifically using it to explore the #WomensMarch tweets. The GEXF on very large networks can get extremely large (i.e. we're working with a half GB file). 

For users w/o powerful machines, I think they'd have trouble ingesting into some network analysis software. This may be a moon shot, but is there any way to put a filter variable (i.e. include only users with more than 5 interactions)?

**Comment by edsu** [comment]
Do you have have a sense of what was causing the most pain? Did the gexf file generate without crushing the machine too bad, and then opening it with Gephi is what was difficult?

As you can tell this little scriptwasn't really designed to be a *big data* tool, but rather something for more close up qualitative analysis. network.py builds an in memory graph of the conversation network using networkx and then writes it out in a variety of formats. If the network is getting built ok it ought to be possible to reduce it using the degree of the nodes present in the graph.

Does that sound worth trying?

**Comment by ianmilligan1** [comment]
Yep, precisely - opening with Gephi was fairly difficult (I have a super beefy machine, but many might not). If you had something like

```
network.py --degree 5 tweets.json tweets.gexf
``` 

as noted above that would be perfect!

**Comment by edsu** [comment]
I've added two new options `--min_subgraph_size` and `--max_subgraph_size` to help in limiting what gets persisted to the output graph. See 0ce504e for details.

I'm not sure this is going to solve you specific problem, so if you get a chance to try it out please let me know. I could add an option that removes nodes with a degree less than `n` if it would be more helpful. If that's the case just reopen this ticket or open a new one.

**Comment by ianmilligan1** [comment]
Great, thanks @edsu – I will try on one of our largest Twitter networks!
