### ISSUE TITLE
Network.py by User not Tweet Label

### ISSUE THREAD

**Issue by ianmilligan1** [DocNow/twarc#144]
Me again. Another pie-in-the-sky request. Right now, the GEXF file outputs like this:

```
      <node id="822960026289635328" label="822960026289635328">
        <attvalues>
          <attvalue for="1" value="DarbyEsquire" />
        </attvalues>
      </node>
```

So when mapped, it's really looking at the relationship between tweets. While some hard core data wrangling could map by user, that's difficult. If you did want people to be able to see central users, etc. (you may not), allowing an option to make the node ID the screen_name of the user rather than the tweet ID might help?

Accordingly, the edge output would then be:

```
      <edge id="1549792" source="823050483678019584" target="823030321276977152" type="quote" />
      <edge id="1549793" source="823607709589270533" target="822852245532319744" type="quote" />
```

with the source/target replaced by usernames.

**Comment by edsu** [comment]
Ok, what you are suggesting is a graph where the nodes are users rather than tweets?

**Comment by ianmilligan1** [comment]
Hi @edsu – yep that was the idea. Much more succinctly put. I will give it a try!

**Comment by edsu** [comment]
Cool, let me know if it does what you need. And of course feel free to reopen this or add a new issue if it doesn't!

**Comment by ianmilligan1** [comment]
I feel like the worst person in the world as I kept meaning to try this, but the semester ran away from me. But I am playing with this now and it's great, thanks!

**Comment by edsu** [comment]
Kind of funny to use GitHub issue tickets as a chat system :-)

**Comment by ianmilligan1** [comment]
Hah yeah, so many lines of communication. 😄  Yes in theory working on another book, although with so many things on the go my big goal is to prune things down for next Fall – so I can do more fun experimenting too! You're in Toronto for AERI this summer right?
