### ISSUE TITLE
Error: cannot import name 'Twarc'

### ISSUE THREAD

**Issue by jte229** [DocNow/twarc#148]
Hi! I'm pretty new to python and twitter; I'm trying to run the sample code to use twarc as a library to collect tweets, but I keep getting **ImportError: cannot import name 'Twarc'** whenever I run the code. Any ideas what I'm doing wrong?

Thanks!

**Comment by hugovk** [comment]
What code are you running? It helps if you have a minimal example.

This might help: https://github.com/DocNow/twarc#use-as-a-library

Does this work for you?
```python
from twarc import Twarc

t = Twarc(consumer_key, consumer_secret, access_token, access_token_secret)
for tweet in t.search("ferguson"):
    print(tweet["text"])
```

**Comment by jte229** [comment]
Yeah, that's what I'm running when I get the error. I have no problems running the command line code, but I keep getting **line 1, in <module>
    from twarc import Twarc
ImportError: cannot import name 'Twarc'**

**Comment by hugovk** [comment]
Did you install twarc with `pip install twarc`?

Where are you running the script from? Do you have your own directory called twarc from where you're running your script? That may cause problems.

**Comment by jte229** [comment]
Yep, I used `pip install twarc` on python 2.7.10 on my mac. I do not have a directory called twarc. Do I need a different version of python?

**Comment by edsu** [comment]
Do you happen to have a file called twarc.py in the directory you are running the code from? What do you see if you do this:

```python
import twarc
print(twarc.__file__)
```

**Comment by jte229** [comment]
When I run that I get
`/Users/myusername/Documents/twarc.pyc
/Users/myusername/Documents/twarc.pyc`

**Comment by edsu** [comment]
Can you try to rename that file to something else? I think Python is finding it before the twarc module you installed.

**Comment by hugovk** [comment]
Make sure to rename both:
* `/Users/myusername/Documents/twarc.pyc /Users/myusername/Documents/twarc.py` and 
* `/Users/myusername/Documents/twarc.pyc /Users/myusername/Documents/twarc.pyc`

**Comment by jte229** [comment]
Hi! Sorry for the delay.

I renamed the files, and now I get this error: `ImportError: No module named twarc`

Sorry I can't seem to figure this out! Thanks!

**Comment by hugovk** [comment]
Can you check you have twarc installed? Try:

 * `pip freeze | grep twarc`
or
* `pip freeze`

**Comment by jte229** [comment]
Yep! I have twarc 1.0.7 installed

**Comment by edsu** [comment]
How are you running your script?

**Comment by jte229** [comment]
I saved the code as a file (test.py) in my directory and then in the terminal run `python test.py`

**Comment by jte229** [comment]
I tried it on my other computer and it's working just fine. Any ideas why I'm having this problem?

**Comment by edsu** [comment]
What do you see if you do this?

`which python`

and 

`which pip` 

at the command line?

**Comment by edsu** [comment]
Also, can you share your test.py in here -- just a copy paste as a comment?

**Comment by jte229** [comment]
I get: `/usr/bin/python` and `/usr/local/bin/pip` which I think might be the problem?

**Comment by edsu** [comment]
Yes, I think you have two pythons for some reason, and twarc isn't installed in one of them. It isn't really a problem to have multiple pythons installed. But it can be problematic when you don't know which one you are using :-)

What do these show?

`/usr/bin/python -V`

and 

`/usr/local/bin/python -V`

**Comment by jte229** [comment]
the first returns `Python 2.7.10` and the second appears to not have python installed :)

**Comment by edsu** [comment]
Please paste the full output of:

    `pip --version`

**Comment by jte229** [comment]
`pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)`

**Comment by edsu** [comment]
how about the output of 

    ls -l /usr/local/bin/python*

**Comment by jte229** [comment]
`lrwxr-xr-x  1 root  wheel  69 Nov 17 17:52 /usr/local/bin/python3 -> ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3
lrwxr-xr-x  1 root  wheel  72 Nov 17 17:52 /usr/local/bin/python3-32 -> ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3-32
lrwxr-xr-x  1 root  wheel  76 Nov 17 17:52 /usr/local/bin/python3-config -> ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
lrwxr-xr-x  1 root  wheel  71 Nov 17 17:52 /usr/local/bin/python3.6 -> ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
lrwxr-xr-x  1 root  wheel  74 Nov 17 17:52 /usr/local/bin/python3.6-32 -> ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-32
lrwxr-xr-x  1 root  wheel  78 Nov 17 17:52 /usr/local/bin/python3.6-config -> ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
lrwxr-xr-x  1 root  wheel  72 Nov 17 17:52 /usr/local/bin/python3.6m -> ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m
lrwxr-xr-x  1 root  wheel  79 Nov 17 17:52 /usr/local/bin/python3.6m-config -> ../../../Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config`

**Comment by edsu** [comment]
ahah, so you installed Python3 it looks like

try to run your program like this:

    python3 test.py

**Comment by edsu** [comment]
Closing this since it appears to be a problem with your local environment, and not with twarc.
