### ISSUE TITLE
log authorization errors

### ISSUE THREAD

**Issue by cazzerson** [DocNow/twarc#149]
If a timeline search for a protected or deleted account is run, an exception is generated that prevents the lockfile from being deleted. Any future run will fail due to the existence of the lockfile. For example:

    requests.exceptions.HTTPError: 401 Client Error: Authorization Required for url: https://api.twitter.com/1.1/statuses/user_timeline.json?count=200&user_id=479065673

**Comment by edsu** [comment]
Thanks, this seems fixable. What would you want to see happen? An error in the log and continuing on like normal?

**Comment by cazzerson** [comment]
@edsu That sounds about right to me. Thanks!

**Comment by edsu** [comment]
Just for clarification, are you getting this error when you run `utils/twarc-archive.py`?

**Comment by cazzerson** [comment]
@edu Yes, that's right.

**Comment by edsu** [comment]
@cazzerson how do you fetch a user timeline with twarc-archive.py? I thought it only did search?

**Comment by cazzerson** [comment]
@edsu Ack, sorry about that. This is a locally modified version of the archive script :-) Let me transfer this to @bretdavidson.

**Comment by edsu** [comment]
It sounds like some functionality that others might find useful...

**Comment by bretdavidson** [comment]
@edsu @cazzerson Yeah, sorry about the confusion. We just put this together in the past few weeks. Will try to open a PR soon. Thanks for looking at this!

**Comment by igorbrigadir** [comment]
I think this can be closed as the functionality is provided by https://github.com/DocNow/twarc-timeline-archive now?
