### ISSUE TITLE
extended tweets

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#153]
From @toddstoffer in email:

---

I wanted to check in and see how twarc is currently handling tweets that are over 140 characters. 
This was enabled somewhat recently by Twitter (https://dev.twitter.com/overview/api/upcoming-changes-to-tweets). 

From my very limited understanding of the twitter API - this change added an option for a new parameter 'tweet_mode'. Which allows an app to either return the old version of the JSON (truncated text field for anything over 140 characters) or the new extended response that returns an additional field of extended_tweet.

Has twarc been updated to allow for the return of the extended_tweet field? 

I have posted a gist (https://gist.github.com/toddstoffer/f1c38b34aa8bc20c38413721a70a3a24) that shows what I am currently getting as a response for a tweet that is longer than 140 characters. The text field is truncated since that tweet was 140 characters plus an image. 

I am basically just looking to see if there is an existing option I can run with the twarc command to get the extended_tweet field.

**Comment by edsu** [comment]
Hi @toddstoffer, [here](https://github.com/DocNow/twarc/commit/721607272f933d2d0df5d78a123df73f3508f97b) is a proposed change to twarc to handle extended tweets. Basically twarc will operate in `compat` mode with Twitter's REST API by default, unless told to do otherwise.

@justinlittman I'd be curious to hear what you think too.

**Comment by justinlittman** [comment]
The sensible side of me says to follow Twitter's guidance and mirror the rollout of the changes. So I'd agree with defaulting to compat mode.

**Comment by edsu** [comment]
Thanks, yeah that was my rationale as well - to mirror Twitter's defaults

**Comment by toddstoffer** [comment]
Would it be possible to add this functionality to the twarc-archive.py script as well?

**Comment by edsu** [comment]
@todstoffer Yes that is definitely possible. But I believe you have a forked version of that at the moment?

**Comment by toddstoffer** [comment]
@edsu We actually do not have a forked version of that yet. We are using the current twarc-archive.py for search based harvests. We are getting ready to fork and add changes to allow similar archive functionality but for timeline based harvests.

**Comment by edsu** [comment]
I'm inclined to merge and release this now that the support for `--tweet_mode` is in twarc-archive.py ... unless there's something else that needs attention?

I began adding doc to the README.md about `--tweet_mode`, but it's damn confusing, and could get out of date quickly, depending on how Twitter expects to continue to develop it.

The plan is to keep twarc operating along with the defaults of the API, and to offer functionality for changing the knobs where appropriate. I don't think all those knobs can be adequately discussed in the twarc documentation.

**Comment by toddstoffer** [comment]
That sounds good to me. Thanks!

**Comment by edsu** [comment]
The extended branch was just merged and released as v1.0.9.
