### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by toddstoffer** [DocNow/twarc#155]
Hello - after the 1.0.9 update I am getting the following error when trying to hydrate tweet ids. 

Traceback (most recent call last):
   File "/usr/local/bin/twarc", line 4, in <module>
    twarc.main()
   File "/usr/local/lib/python2.7/site-packages/twarc.py", line 195, in main
    for thing in things:
   File "/usr/local/lib/python2.7/site-packages/twarc.py", line 740, in hydrate
    resp = self.client.post(url, data={"id": ','.join(ids)})
   AttributeError: 'NoneType' object has no attribute 'post'

Is anyone else seeing this error when they try to hydrate a tweet?

**Comment by edsu** [comment]
@toddstoffer I haven't seen it. How are you creating the error?

**Comment by edsu** [comment]
Oh, like this?

    twarc tweet 843983938448232400

**Comment by edsu** [comment]
Thanks for reporting this @toddstoffer -- the fix was just released as part of v1.0.10
