### ISSUE TITLE
Support request: max_id and since_id doesn't seem to work

### ISSUE THREAD

**Issue by ismailcherri** [DocNow/twarc#158]
Hi,
I was playing with your wonderful twarc fetching some twitter timelines when I face a certain issue regarding the number of tweets retrieved.
It seems that `--since_id` or `--max_id` don't have any effect on the `timeline` command, is this correct or I'm doing something wrong?
the command I'm running is:
`twarc timeline ismailcherri --since_id 852749158066790400 > ismailcheri.json`

So what am I doing wrong here?
Thanks!

**Comment by edsu** [comment]
Thanks for reporting this @ismailcherri! You weren't doing anything wrong. The command line invocation of timeline was not wired up correctly to Twarc.timeline, which was preventing the since_id and max_id options from being passed through to it.

This was fixed and just released to PyPI as v1.1.0.

**Comment by ismailcherri** [comment]
Wow! Thanks for the quick reply and fix.
I'm using it to scrape some twitter accounts for a social media platform that I'm working on, really nice.

**Comment by edsu** [comment]
@ismailcherri interesting! You aren't by any chance working with Mastodon / GNU Social are you?

**Comment by ismailcherri** [comment]
Unfortunately , no, not at this time.
I meant in my previous comment, a social media management platform 😅
