### ISSUE TITLE
twarc replies error with invalid tweet identifier

### ISSUE THREAD

**Issue by F00LY** [DocNow/twarc#164]
`python twarc.py --access_token XXXXXXX --access_token_secret YYYYYYY --consumer_key ZZZZZZZZ --consumer_secret AAAAAAAAA --recursive replies 874344317745152000`

Returns

```
Traceback (most recent call last):
  File "twarc.py", line 1052, in <module>
    main()
  File "twarc.py", line 179, in main
    things = t.replies(next(t.hydrate([query])), args.recursive)
StopIteration

```

I'm not sure why...

Also, is there a way to catch if you were returned a rate limit to wait and try again built in?

**Comment by edsu** [comment]
That tweet id doesn't exist:

    https://twitter.com/i/status/874344317745152000

But twarc should say that instead of emitting that unhelpful error, so thanks for reporting it.

FYI: Often when you see tweets ending in 000 there has sometimes been an overflow error in handling the tweet identifier as an integer rather than a string.
