### ISSUE TITLE
Generate JSON output using twarc as a library

### ISSUE THREAD

**Issue by koljamaier** [DocNow/twarc#167]
Hi all,

is there a way to generate a JSON file, like one would do on command line via ``twarc hydrate ids.txt > tweets.json``, using ``twarc`` as a library?

Right now, I do the parsing by myself. 
Problem: Another library (``poultry`` [corresponding issue over there](https://github.com/dimazest/poultry/issues/5)) doesn't process my created JSON.

Cheers

**Comment by edsu** [comment]
Thanks for the pointer to poultry, I hadn't seen that before. I've subscribed to that issue ticket to make sure that twarc's output isn't messed up in some way.

On the topic of using twarc as a library to hydrate tweet ids the trick is creating a generator function that produces your ids and passing that to `twarc.hydrate`. I guess generators are more on the advanced side of python, so maybe that wasn't the most user friendly choice. But they really are handy for when you have a long series of values and you don't want to have to read them all into memory to process them. 

So here's an example of using twarc as a library to hydrate a file of tweet ids:

```python

import twarc

t = twarc.Twarc()

def ids():
    for line in open("ids.txt"):
        yield line

for tweet in t.hydrate(ids()):
    print(tweet['text'])

```

The cool thing is your ids function could be reading the ids from a database or a spreadsheet or whatever. The only rule is that it must yield a tweet id for the hydrate call to work properly. Feel free to reopen this ticket if you run into problems.
