### ISSUE TITLE
hydration ids format

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#169]
The documentation is not clear about what format the tweet ids should look like for hydration. If you feed in a JSON list of ids, or something other than numbers and newlines the output is empty. If the input doesn't look like numbers and newlines it should respond with a helpful error message.

**Comment by dianaascher** [comment]
A sample file would be very helpful

**Comment by edsu** [comment]
The hydrate command expects to be give a file that contains a tweet identifier on each line:

```
919505987303886849
919505982882844672
919505982602039297
919505980018348032
919505974574100480
919505961332637697
919505957096493056
919505940453326849
919505923776774150
919505919880376320
919505919649763328
```
919505914356318210
919505909625344000
919505905313443840
919505904663388160
