### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#172]
When outputting tweets it would be useful to have the CSV option in the command itself. Something like:

    twarc search blacklivesmatter --output csv > tweets.csv

The downside is that this would result in data loss since not everything makes it into the CSV. But perhaps this is something some researchers are willing to live with? At the moment it is a bit clunky constantly referring people to [json2csv.py](https://github.com/DocNow/twarc/blob/master/utils/json2csv.py) but perhaps this isn't too much of a hardship?

If anyone has an opinion I'd love to hear it.

**Comment by alibama** [comment]
this is a great idea - would love to have the option
