### ISSUE TITLE
documentation should use .jsonl extension

### ISSUE THREAD

**Issue by alibama** [DocNow/twarc#173]
hey folks - love the tool, wondering why it doesn't create valid json?  i've looked at it in various validator tools and it always throws errors since there are multiple root elements.   how do other people resolve this or is it a non-issue for some reason

thanks again - great tool

**Comment by edsu** [comment]
Yes, the output is [line-delimited-json](https://en.wikipedia.org/wiki/JSON_Streaming#Line_delimited_JSON). This is how Twitter send it over the wire, and it's a convenient way to store it for downstream processing because you don't need to parse a large JSON document and store it in memory to work with the tweets. It's also really handy to use at the command line with unix utilities and tools like [jq](https://stedolan.github.io/jq/) that understand it.

**Comment by hugovk** [comment]
The README says:

> Tweets are stored as line-oriented JSON.

So the output file, of say `twarc search '#blacklivesmatter OR #blm to:deray' > tweets.json`, isn't technically valid JSON as a whole, but each line of the file should be valid JSON. 

I guess the idea is you read in each line of the file, and process that line as a complete chunk of JSON.

---

You could post-process the file something like this:
```bash
# Put "[" in a new file
echo "[" > tweets2.json

# Append commas to each line but the last, and append to the file
sed '$!s/$/,/' tweets.json >> tweets2.json

# Append "]" to the file
echo "]" >> tweets2.json
```

That then validates at https://jsonlint.com/ and https://jsonformatter.curiousconcept.com/.

---

It may be misleading having a .json file which isn't technically valid JSON.

A quick Google brings up the "JSON Lines" format http://jsonlines.org with a suggested *.jsonl extension. It looks like twarc output meets their three requirements.

**Comment by edsu** [comment]
Yes, perhaps it would be good to update the docs to use `.jsonl` instead of `.json` to nip confusion in the bud?

**Comment by alibama** [comment]
Wow!  Thanks for the heads up fellas - jq looks like a great tool - @hugovk that's a really helpful recommendation @edsu i like the idea a lot - i'm not very knowledgeable here, and having using jsonl does help refine the search.

Thank you both for helping me!  we're here in charlottesville parsing a stupid amount of tweets.... :)

**Comment by edsu** [comment]
I'd love to hear about what you are up to parsing the tweets. There is a group of folks who hang out in the the [Documenting the Now Slack](http://www.docnow.io/img/slack.png) where we could chat about this if it's useful.

**Comment by hugovk** [comment]
Here's a PR: https://github.com/DocNow/twarc/pull/175

**Comment by edsu** [comment]
Of course, now I notice [ndjson](https://ndjson.org) which even has a [spec](http://specs.okfnlabs.org/ndjson/) that defines a media type, which is thorough. The domain was registered a full year after jsonlines.org, so maybe jsonl is the right choice still. I'm not sure it really matters too much :-)

**Comment by edsu** [comment]
I doubt this will help, but https://twitter.com/edsu/status/902900471387521024
