### ISSUE TITLE
twarc archive

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#176]
I think it might be useful to bring the functionality that was moved out into [utils/twarc-archive.py](https://github.com/DocNow/twarc/blob/master/utils/twarc-archive.py) back into twarc itself. The functionality gets used enough that it would be useful to have it installed by default, and having two commands doesn't make much sense really. So you would run twarc archive like this:

    twarc archive blacklivesmatter /vol/tweets/blacklivesmatter

This plus #172 and the fact that twarc.py is over 1000 lines might be a good indicator that twarc should be refactored as a module with multiple submodules rather than a single file.

**Comment by igorbrigadir** [comment]
Closing some old issues, this is superseded by: 
https://github.com/DocNow/twarc-timeline-archive
