### ISSUE TITLE
twarc users & protected accounts

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#179]
When attempting to fetch user account metadata twarc will bundle up 100 ids at a time so that they can be fetched in bulk rather than one per request. The problem with this is that if 1 or more of the 100 are protected accounts a HTTP 403 error is returned, and there is no way to know which ids are protected. 

I think the solution here is to switch to going one-by-one when a 403 error is returned. Then when that batch of 100 is completed it can go back to trying in bulk again.

**Comment by peterk** [comment]
This would be a great feature. Trying it with large number of bot accounts is cumbersome right now as they disappear or become protected quickly .

**Comment by igorbrigadir** [comment]
In v2, the new response structure contains `errors` where the missing users would be referenced with a reason (suspended, deleted, etc)
