### ISSUE TITLE
Error with .text and .full_text in 2.0 version

### ISSUE THREAD

**Issue by aniol** [DocNow/twarc#180]
In 2.0 version I suppose because the API change of `.text` for `.full_text` [that you explained in the changelog](https://github.com/DocNow/twarc/releases/tag/v1.2.0), there is an error with Twarc `utils` that always show the same error when I try to execute any of the `*.py` scripts. For example:
> wall ***.jsonl > wall.html
> Traceback (most recent call last):
> File "/home/***/twarc/utils/wall.py", line 145, in <module>
> "text": tweet["text"],
> KeyError: 'text'

Only seems to work `json2csv.py` and `times.py` maybe another scripts, but `wall.py`, `wordcloud.py` or `geojson.py` not.

**Comment by lotsoaxolotls** [comment]
Fixed for wordcloud.py.

**Comment by edsu** [comment]
Two more to go :-)
