### ISSUE TITLE
Tweets from a location?

### ISSUE THREAD

**Issue by anitcd** [DocNow/twarc#182]
"twarc sample" works efficiently to capture random samples. I was wondering if I can capture random samples by specific location co-ordinates (e.g. as you used in "twarc search --geocode 38.7442,-90.3054,1mi"). Is it possible to use something like "twarc sample --geocode 38.7442,-90.3054,1mi"?

**Comment by edsu** [comment]
Unfortunately the sample stream doesn't allow you to query for a bounding box. 

    https://developer.twitter.com/en/docs/tweets/sample-realtime/api-reference/get-statuses-sample

But depending on the geographic region you may be able to collect everything within a bounding box using `filter` and `--locations`. For example this will get all the tweets for New York City you do something like this:

    twarc filter --locations '\-74,40,-73,41'

Note that the leading dash is escaped so the Unix doesn't interpret it as a command line option. Does this make sense?

**Comment by anitcd** [comment]
Thanks for your reply. Just to clarify two things:

(1) When you are using the "filter --location" option, is the geographic region information ('\-74,40,-73,41') similar to a (latitude, longitude) co-ordinate format (e.g. 38.7442,-90.3054)? It looks little different. How to get that specific geographic region/location information for different cities (e.g. London or Paris)?

(2) What is the size of the bounding box in this option (twarc filter --locations '\-74,40,-73,41'). Does it internally manage the region and collect everything from that city?

**Comment by edsu** [comment]
the --location is a [bounding box](http://wiki.openstreetmap.org/wiki/Bounding_Box) for a region rather than a point with a radius.

There are different ways of determining the bounding box, but one way is to use a tool like [this](http://boundingbox.klokantech.com/) to search for an area, and then select the CSV output. 

I searched for Paris which yielded 2.224122,48.815575,2.46976,48.902157 which I was then able to use with twarc to search for tweets geocoded Paris. You can use a tool like [jq](https://stedolan.github.io/jq/) to make sure the correct places are coming back:

```
% twarc filter --location 2.224122,48.815575,2.46976,48.902157 | jq .place.full_name
"France"
"Saint-Denis, France"
"Paris, France"
"Isla de Francia, Francia"
"Suresnes, France"
"Isla de Francia, Francia"
"Noisy-le-Sec, France"
"Paris, France"
"Puteaux, France"
"Paris, France"
"Paris, France"
"Clichy, France"
```

I hope that helps?

**Comment by anitcd** [comment]
Thanks a million for your suggestion. It works well. Only issue that I found is the reliability of the location of the tweet. It seems that the tweets are coming even from outside of the bounding box. I searched for Dublin, Ireland as follows:

twarc filter --location '\-6.551485,53.179292,-6.039047,53.495195' | jq .place.full_name
"Dublin City, Ireland"
"Dublin City, Ireland"
"Dublin City, Ireland"
"Dublin City, Ireland"
"Kildare, Ireland"
"United Kingdom"
"South Dublin, Ireland"
"Kildare, Ireland"
"Dublin City, Ireland"
"Meath, Ireland"
"England, United Kingdom"
"Wicklow, Ireland"
"Dublin City, Ireland"

Several tweets are showing the place names from the UK. Although every tweet doesn't contain the exact location point (lat, long) information but I found some tweets that are showing the place names as "United Kingdom" and the exact location point is also in the UK. Considering the place name, the percentage of tweets that are coming from outside of the bounding box is not too small.

Any suggestion/comment would be appreciated.

**Comment by edsu** [comment]
I think these questions would be better asked over in the [Twitter Developer Forum](https://twittercommunity.com/). I did look at some of those places and they are close to Dublin. So perhaps your bounding box includes them? Also, it is important to remember that Dublin is technically a part of the United Kingdom.

**Comment by hugovk** [comment]
It is [complicated](https://en.wikipedia.org/wiki/Terminology_of_the_British_Isles), I'm quite certain Dublin is not technically part of the United Kingdom!

**Comment by edsu** [comment]
Ouch my bad. I'm glad I'm just a little misinformed software developer and not a politician!

**Comment by anitcd** [comment]
:)
Main issue is still with the location and the bounding box. I found tweets with location information that are definitely coming from outside of the bounding box that I set.

**Comment by edsu** [comment]
As much as I would like to help you, I don't work at Twitter and have no insider knowledge of how the geo querying works.
