### ISSUE TITLE
Report deleted tweet ids

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#184]
It would be useful if the *hydrate* command logged any ids that were not hydrated as part of a status/lookup response.

**Comment by janLuke** [comment]
I came here because I tried to hydrate 50,000 tweets (using twarc as a library) but I got only ~35,000 tweets without receiving any warning or feedback about the missing ones. So, if I understood it well, twarc is silent about tweets that are not available anymore, right?

**Comment by janLuke** [comment]
Regarding the use of twarc as a library, **I think the developer should know what happens for each ID, including those of unavailable tweets**, so the hydrate iterator should return something for each ID in the list. One can think of multiple ways to include the outcome of a request:
1. you could add a field to the returned dictionary (e.g. ``tweet['downloaded']`` or ``tweet['status']``)
2. if the result is binary (downloaded / not downloaded), the iterator could return pairs ``(id, tweet)`` with ``tweet=None`` in case the tweet is missing.
3. the iterator could return triplets ``(id, status, tweet)``.

**Comment by edsu** [comment]
I don't like 1 because it pollutes the representation of a tweet. 2 and 3 are excellent ideas. I think I prefer 2 since it is simpler, and it's difficult for me to imagine a status that would not be reflected by the presence / absence of the tweet data.

**Comment by janLuke** [comment]
I agree with you.

> @janLuke so your use case was that you were using twarc as a library, and not on the command line?

Yes, sorry, I thought I had written it.

**Comment by edsu** [comment]
Ah you did, I just missed it.

**Comment by igorbrigadir** [comment]
Going through closing some old issues: this should be done with the new Batch Compliance API: see `twarc2 compliance-job --help`
