### ISSUE TITLE
twarc configure error

### ISSUE THREAD

**Issue by todrobbins** [DocNow/twarc#186]
I'm getting the following error when I try to run `twarc configure`:

```
➜  twarc configure
usage: twarc [-h] [--search SEARCH] [--max_id MAX_ID] [--since_id SINCE_ID]
             [--stream STREAM] [--hydrate HYDRATE] [--log LOG]
             [--consumer_key CONSUMER_KEY] [--consumer_secret CONSUMER_SECRET]
             [--access_token ACCESS_TOKEN]
             [--access_token_secret ACCESS_TOKEN_SECRET]
twarc: error: unrecognized arguments: configure
```

I installed via `pip3 install twarc` just a couple of minutes ago. Any ideas what I'm doing wrong?

**Comment by todrobbins** [comment]
Also, I can run other commands (`--search` for instance) without a hiccup with all of the key/token params filled out.

**Comment by edsu** [comment]
The `--search` is the old twarc API. Perhaps you didn't actually install it? How did you install?

**Comment by todrobbins** [comment]
Right you were! That fixed it.

PS: any plans to add `twarc -v` or `twarc --version` so I can check twarc's version? 😄

**Comment by edsu** [comment]
It uses the sub command style:

```
% twarc version
twarc v1.1.3
```

**Comment by todrobbins** [comment]
Ah! User error again! Thanks for your patience @edsu!
