### ISSUE TITLE
weird redirections by twitter (?) on deletes.py results with TWEET_OK

### ISSUE THREAD

**Issue by remagio** [DocNow/twarc#198]
I gave a try to the @justinlittman version of the new deletes.py b/c new features. I added threads and others perfs feature to the old one but commit details says it offer better insights then the previous one. Obviously I tested it with same previous deleted tweets. Kudos to @justinlittman
Despite it's very slow then previous release with threads (and other tricks to perform thousands per minutes) I noticed some weird results with "TWEET_OK" results using http-traceroute (npm pkg but the same like cURL).
Let me say I'm not saying deletes.py is wrong b/c I'm focused on Twitter responses about deleted/suspended users/tweets.
I found on my data sets almost 4 patterns getting redirections or to new tweets or to different users tweets. Also when is from a suspended user.
In my opinion you all should get similar results on your own datasets, here's just a sample of 2, I checked now to show current redirections:
```
#$ http-traceroute https://twitter.com/SofiaSales11/status/902340657175461893
[301] HTTP/1.1 HEAD https://twitter.com/SofiaSales11/status/902340657175461893 (cookies: 5) (258 ms)
[200] HTTP/1.1 HEAD https://twitter.com/Sofiadossii/status/902340657175461893 (cookies: 5) (568 ms)
Trace finished in 839 ms using 1 hop
$# http-traceroute https://twitter.com/VaiVieni/status/899587208478380032
[302] HTTP/1.1 HEAD https://twitter.com/VaiVieni/status/899587208478380032 (cookies: 5) (345 ms)
[200] HTTP/1.1 HEAD https://twitter.com/OsservPolitico/status/892798077395972098 (cookies: 5) (361 ms)
```
What makes it more funny is that some of it 20 days ago resulted with two 3xx and one 2xx but over 3 users accounts. I have many more kind of weird results but I'm sure you'll have yours too.
Any ideas about what I'm missing here?

**Comment by edsu** [comment]
I actually cannot test this without the JSON for https://twitter.com/SofiaSales11/status/90234065717546189

**Comment by remagio** [comment]
@edsu it's in your mail ;) remind it's not today json but a little bit old. I just checked today if/what changed with redirections.

**Comment by remagio** [comment]
Obviously I never thought about bugs but just a confirmation of some kind of "redirection" also if I can't find referral to it on Twitter policies. I'm interested in it b/c screen_name changes by comprog bots are used also to skip detection, reports or kinda short clean up about old twitterstorms.

I didn't find statements like "redirection supported if/when/for...": @edsu @justinlittman in your opinion could we use any policy/API descriptions to say it's not about "wrong screen_name" but "changed screen_name" to make make available old tweets by example?

**Comment by remagio** [comment]
I forgot this open, I'm sorry by that @edsu @justinlittman.
Btw I never thought about it like an issue. Sometime later I found out I needed something more specific (not just the good rewrite of deletes.py rewrite at the time) in understanding censorship & self-censorship by polbots or socketpuppets.
