### ISSUE TITLE
i normally run word clouds just like this 

### ISSUE THREAD

**Issue by akrolla** [DocNow/twarc#205]
but got weird error today 
 python3 wordcloud.py gotmits.json > gotmitscloud.html
Traceback (most recent call last):
  File "wordcloud.py", line 108, in <module>
    main()
  File "wordcloud.py", line 43, in main
    size_ratio = 100.0 / count_range
ZeroDivisionError: float division by zero

**Comment by edsu** [comment]
Thanks! It looks like you had words with all the same number of occurrences. Please try again with the updated wordcloud.py which should prevent a divide by zero.
