### ISSUE TITLE
UnicodeEncode error when writing CSV on Windows

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#207]
Via Tim Arnold. It looks like there is an encode error when writing CSV on Windows:

![capture1](https://user-images.githubusercontent.com/33829/36057420-d270f0d0-0ddb-11e8-86b9-7d254bda2263.PNG)

**Comment by edsu** [comment]
This fix caused problems for python2.7 on Unix. I'm going to revert until another fix is found.

**Comment by akrolla** [comment]
Is there a work around by any chance?

**Comment by edsu** [comment]
I believe writing to a file instead of a pipe will work:

    twarc search neveragain --output neveragain.jsonl

**Comment by igorbrigadir** [comment]
Same as #297 , this is resolved by https://github.com/DocNow/twarc/issues/297#issuecomment-549416102 or not using `>` and specifying an output file as above.
