### ISSUE TITLE
Cannot read from gzipped or bzipped input using Python 3.6

### ISSUE THREAD

**Issue by JesseTG** [DocNow/twarc#209]
It's not possible to open lists of tweet IDs if they're compressed with the `gzip` or `bz2` modules.  `command.py` passes in a mode of `rU` to `fileinput.hook_compressed`...

https://github.com/DocNow/twarc/blob/7c08264078d9ad5c28d906c7221f538c1fdd14e0/twarc/command.py#L108-L122

...but the compression modules in question [don't allow it](https://github.com/python/cpython/blob/8c65360dd0c1ea5b5d2e60a0694daf3f9df8f56b/Lib/gzip.py#L158-L159).

For Python 3.6, you can remove the `U` flag, as that's for text mode only (and `bz2`/`gzip` operate in binary mode).  I don't know if this will break Python 2.x compatibility.

**Comment by edsu** [comment]
Thanks for this, I'm seeing the same problem too. I'll work on a fix that works for 3 and 2.

**Comment by igorbrigadir** [comment]
Going through closing some old issues: I think with twarc2, you can pipe input into it, so it can handle anything. Python 2 is now not supported either.
