### ISSUE TITLE
In decorators.interruptible_sleep, use event.wait instead of polling every second

### ISSUE THREAD

**Issue by JesseTG** [DocNow/twarc#210]
It uses less CPU time.  See `event.wait` [here](https://docs.python.org/3/library/threading.html#threading.Event.wait).

https://github.com/DocNow/twarc/blob/7c08264078d9ad5c28d906c7221f538c1fdd14e0/twarc/decorators.py#L94-L106

**Comment by edsu** [comment]
Why do you think time.sleep is cpu intensive?

**Comment by JesseTG** [comment]
Not `time.sleep` itself, but the process of waking up every second and checking.  Perhaps it's not "intensive", but it *is* a quick and easy optimization (that I will take care of over the weekend).

Also, it can result in sleeping for longer than necessary if `event` gets set while sleeping.

**Comment by hugovk** [comment]
Here's a comparison. 

https://stackoverflow.com/q/29082268/724176

**Comment by JesseTG** [comment]
@hugovk Ah, forgot about the GIL.  So you're telling me that when running in Python 2 there wouldn't be as much a difference (since the sleeping is done in Python), but in Python 3 there would be?

**Comment by edsu** [comment]
Oh, I understand now. This matters when an event is supplied, and will mean that twarc will stop sleeping immediately if a supplied event has fired? It's less an issue of performance and more an issue of responsiveness.

**Comment by edsu** [comment]
If you send me a PR I will test & merge it.

**Comment by JesseTG** [comment]
> Oh, I understand now. This matters when an event is supplied, and will mean that twarc will stop sleeping immediately if a supplied event has fired? It's less an issue of performance and more an issue of responsiveness?

I was using the terms interchangeably, but yes, you could say that.  Also, sleeping this way does free up the GIL, which would be important if multi-threading of any kind was ever added.

> If you send me a PR I will test & merge it.

You got it.  Love this project, by the way.  Super convenient.
