### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#211]
To simplify the maintenance of twarc we're thinking of moving it to only supporting Python 3 instead of both Python 2 and 3. Would that severely impact any users of twarc?

**Comment by hugovk** [comment]
I'm not a heavy user of twarc, but I've switched to Python 3 first for local and server things.

Here's the pip installs for twarc from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |  48.77% |             99 |
| 2.7            |  35.47% |             72 |
| 3.5            |   8.87% |             18 |
| 3.4            |   6.90% |             14 |

Source: `pypinfo --start-date -52 --end-date -25 --percent --pip --markdown twarc pyversion`

**Comment by edsu** [comment]
I think it would be polite for us to wait on this till Social Feed Manager [are ready](https://twitter.com/justin_littman/status/978068743086661632).

**Comment by lwrubel** [comment]
Very belatedly, wanted to confirm that Social Feed Manager has been on Python 3 since summer 2018. Sorry for missing this earlier. No need to hold off removing Python 2.7 on our account.

**Comment by edsu** [comment]
Thanks for the update!

**Comment by igorbrigadir** [comment]
At this point, minimum python for twarc is 3.3 https://github.com/DocNow/twarc/blob/main/setup.py#L24 closing some old issues
