### ISSUE TITLE
using as api

### ISSUE THREAD

**Issue by akrolla** [DocNow/twarc#223]
could you be a bit more specific on some of the calls when using twarc as an api, I am having trouble passing it json or it passing json .

**Comment by akrolla** [comment]
when trying to pass the json after gathering, it  gets turned into a different object that no longer can be read by twarc further along in the code. for example, if i script a twarc search command into a os.system call it returns the json or whatever format i pick, but it isnt able to identify the json as i pass it further into the program, some of the things i am trying to use it for require me to refine the tweets to a really specific subset of tweets, and then id in theory like to pass that set of tweets to a static program for analytics instead of pulling them directly live.  also when using it directly feeding from api into the analytics, it has trouble translating the json object as well.

**Comment by edsu** [comment]
I think I understand a little bit better now, in that you are trying to filter the data you are getting back from twarc, but I'm confused about what "pass it further into the program" means.

If you can provide a short code example of what you are trying to do perhaps that would help? I'm sorry to be dense.

**Comment by akrolla** [comment]
twarc stores the info in an  unconventional way, and makes parsing difficult. The keys for tweet text get changed. and it seems i am getting json decoding errors as well, by passing further i only meant that because of the really specific subset of tweets i need, i have to filter it and id imagined being able to use twarc api  without having to have it pull tweets anytime its used, and maybe just using  it  move the data to the different ML algorithms i have further into the code. A few other of the analytics i am running i have  it iterate through tweets and determines stuff as it does, for some reason i can only get it to iterate through half of somebodys tweets as well, i couldnt find the code that completes the entire iteration through the timeline as it seems the entire iteration is split between the ratelimit function and another one.

**Comment by edsu** [comment]
I’m sorry you are continuing to have difficulty, but this is simply not true. Twarc does not change received Twitter data in any way. It simply parses it with the JSON library and passes it along. If you are able to provide specific code examples of how you are using twarc as a library please reopen this ticket.
