### ISSUE TITLE
Typo on json2csv column

### ISSUE THREAD

**Issue by slarrain** [DocNow/twarc#224]
There is a typo: 
https://github.com/DocNow/twarc/blob/b4354c1874b46c0f0feae94696a962679f953840/twarc/json2csv.py#L37

It should say: `retweet_or_quote_id`.
What is the best/fastest way to get this fixed? I thought about forking and making a PR, but perhaps is just easier for you to fix it?

Thanks!

**Comment by edsu** [comment]
Thanks for reporting this. Your change was just applied here in GitHub and was released to PyPI as [v1.4.5](https://pypi.org/project/twarc/1.4.5/#description).
