### ISSUE TITLE
Error: -bash: twarc: command not found ---- macOS High Sierra

### ISSUE THREAD

**Issue by Thiliniiw** [DocNow/twarc#231]
I have used twarc successfully with ubuntu. Recently I tried to use twarc in macOS High Sierra. At this point, I am interested in using twarc as a command line tool. Therefore I tried to run twarc configure in my terminal and this error (-bash: twarc: command not found) pops up. 
My machine came with Python 2.7.10 pre-installed and I used pip to install twarc 1.4.7. Any idea on what I should do differently on mac?
Thanks!

**Comment by hugovk** [comment]
It might help to show the output of these commands:
```
which twarc
twarc --help
which python
python --version
which pip
pip --version
pip install -U twarc
```

**Comment by Thiliniiw** [comment]
which twarc did not give any output

**username-MacBook-Air:~ username$ which twarc**
username-MacBook-Air:~ username$ 

**username-MacBook-Air:~ username$ twarc --help**
-bash: twarc: command not found

**username-MacBook-Air:~ username$ which python**
/usr/bin/python

**username-MacBook-Air:~ username$ python --version**
Python 2.7.10

**username-MacBook-Air:~ username$ which pip**
/usr/local/bin/pip

**username-MacBook-Air:~ username$ pip --version**
pip 10.0.1 from /Library/Python/2.7/site-packages/pip-10.0.1-py2.7.egg/pip (python 2.7)

**username-MacBook-Air:~ username$ pip install -U twarc**
Requirement already up-to-date: twarc in ./Library/Python/2.7/lib/python/site-packages (1.4.7)
Requirement not upgraded as not directly required: pytest in /Library/Python/2.7/site-packages (from twarc) (3.6.2)
Requirement not upgraded as not directly required: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from twarc) (1.5)
Requirement not upgraded as not directly required: requests_oauthlib in /Library/Python/2.7/site-packages (from twarc) (1.0.0)
Requirement not upgraded as not directly required: unicodecsv in /Library/Python/2.7/site-packages (from twarc) (0.14.1)
Requirement not upgraded as not directly required: mock in /Library/Python/2.7/site-packages (from twarc) (2.0.0)
Requirement not upgraded as not directly required: pluggy<0.7,>=0.5 in /Library/Python/2.7/site-packages (from pytest->twarc) (0.6.0)
Requirement not upgraded as not directly required: atomicwrites>=1.0 in /Library/Python/2.7/site-packages (from pytest->twarc) (1.1.5)
Requirement not upgraded as not directly required: more-itertools>=4.0.0 in /Library/Python/2.7/site-packages (from pytest->twarc) (4.2.0)
Requirement not upgraded as not directly required: py>=1.5.0 in /Library/Python/2.7/site-packages (from pytest->twarc) (1.5.4)
Requirement not upgraded as not directly required: attrs>=17.4.0 in /Library/Python/2.7/site-packages (from pytest->twarc) (18.1.0)
Requirement not upgraded as not directly required: funcsigs; python_version < "3.0" in /Library/Python/2.7/site-packages (from pytest->twarc) (1.0.2)
Requirement not upgraded as not directly required: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pytest->twarc) (18.5)
Requirement not upgraded as not directly required: six>=1.10.0 in ./Library/Python/2.7/lib/python/site-packages (from pytest->twarc) (1.11.0)
Requirement not upgraded as not directly required: oauthlib>=0.6.2 in /Library/Python/2.7/site-packages (from requests_oauthlib->twarc) (2.1.0)
Requirement not upgraded as not directly required: requests>=2.0.0 in /Library/Python/2.7/site-packages (from requests_oauthlib->twarc) (2.19.1)
Requirement not upgraded as not directly required: pbr>=0.11 in /Library/Python/2.7/site-packages (from mock->twarc) (4.0.4)
Requirement not upgraded as not directly required: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests>=2.0.0->requests_oauthlib->twarc) (2018.4.16)
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests>=2.0.0->requests_oauthlib->twarc) (3.0.4)
Requirement not upgraded as not directly required: urllib3<1.24,>=1.21.1 in /Library/Python/2.7/site-packages (from requests>=2.0.0->requests_oauthlib->twarc) (1.23)
Requirement not upgraded as not directly required: idna<2.8,>=2.5 in /Library/Python/2.7/site-packages (from requests>=2.0.0->requests_oauthlib->twarc) (2.7)

**Comment by edsu** [comment]
Thanks for submitting this. Can you uninstall twarc:

    pip uninstall twarc

And paste the full output, and then install twarc again and paste the full output of that?

**Comment by edsu** [comment]
Thanks for submitting this. Can you look and see if the twarc executable can be found in your home directory here?

    ~/Library/Python/2.7/bin/twarc

**Comment by Thiliniiw** [comment]
I uninstalled twarc and installed it again via pip. Now it does not throw the error.  To answer your question; I cannot find the twarc executable at the location you have specified. The executable is at **/usr/local/bin/twarc**

**username-MacBook-Air:~ username$ which twarc**
/usr/local/bin/twarc

**Comment by Thiliniiw** [comment]
I have uninstalled and reinstalled twarc using pip. The error is no more. Now the twarc executable is at: 

**username-MacBook-Air:~ username$ which twarc**
/usr/local/bin/twarc

**Comment by edsu** [comment]
Interesting, I know if I pup install with —user it goes into ~/Library/ which isn’t in the default PATH. At any rate it sounds like this is fixed for now?

**Comment by Thiliniiw** [comment]
I pip installed without the user flag and yes it seems it is fixed now. Thanks!
