### ISSUE TITLE
Timeline on twarc-archive.py

### ISSUE THREAD

**Issue by slarrain** [DocNow/twarc#238]
Hi,

Is it possible to use the `timeline` functionality on `twarc-archive.py`? It would seem that twarc-archive only uses `GET search/tweets` and not `GET statuses/user_timeline`. Is that correct? 
My use case requires to use the timeline because of the bigger requests calls per window, and I have to do it through an extended period of time, so mining only the newer tweets automatically, is exactly what I'm looking for.

Because, as far as I know, if I do:
```sh
twarc timeline slarrain > slarrain.jsonl
```
2 days in a row, it just overwrites the `slarrain.jsonl` file. And If I, instead, give it a new name, like `slarrain2.jsonl`, It will re-mine the tweets that are already on the old file. So it would seem that what I'm looking for is exactly the functionality that twarc-archive provides, but not for search (which I'm currently using) but for timelines.

Is that possible?

In any case, thank you so much for `twarc`. Is beyond awesome.

**Comment by slarrain** [comment]
Wait! It looks like it is implemented, although not mentioned (I think) in the documentation: https://github.com/DocNow/twarc/blob/6c81bf973492a02eb84716e1cd9c8b6e55731364/utils/twarc-archive.py#L116

**Comment by edsu** [comment]
Oh wow, I had forgotten about that. If you wanted to add any information to the documentation as a PR that would be great. I believe there is a ticket to try to move this functionality back into twarc proper, but I don't know when that will happen.

**Comment by slarrain** [comment]
Sure! I'll try to submit a PR for Documentation.
By the way, it went perfectly. I just changed ```from:slarrain``` to ```slarrain``` as the argument, and added the ```--twarc_command timeline``` and the ```twar-archive.py``` kept working without a hiccup, with the same accounts it was mining before. Superb.
Thanks again for this awesome package.
Closing.

**Comment by edsu** [comment]
You're welcome! Thanks for the kind words, they make everything worthwhile.

**Comment by jason-lange** [comment]
Thank you @slarrain for raising this question and resolving it. Could you share the command line syntax for getting a timeline with twarc-archive.py? 
Its not clear to me based on your explanation. I was trying the equivalent of the following with my own profile as a test. It didn't work. :(
twarc-archive.py timeline slarrain > slarrain.jsonl

**Comment by edsu** [comment]
@jason-lange can you try adding the '--twarc_command timeline` option?

    twarc-archive.py --twarc-command timeline slarrain > slarrain.jsonl

**Comment by jason-lange** [comment]
Thanks @edsu. I tried that just now and get this error:
-bash: twarc-archive.py: command not found
I'm trying out twarc (and command line) with this: tutorial https://github.com/alblaine/twarc-tutorial 
which has me using utilities via syntax like the following, which created the .gz file as intended:
    utils/twarc-archive.py tweets.json /Users/jasonlange/documents/twarc-tutorial-master/test
I tried a variation of your syntax:
     utils/twarc-archive.py --twarc-command timeline langejason /Users/jasonlange/documents/twarc-tutorial-master/test
I got this error:
     error: unrecognized arguments: --twarc-command /Users/jasonlange/documents/twarc-tutorial-master/test
It didn't seem to like either the --twarc-command or the destination argument.

**Comment by edsu** [comment]
Ahh, yes it uses underscores instead of dashes for command line options:

    utils/twarc-archive.py --twarc_command timeline langejason /Users/jasonlange/documents/twarc-tutorial-master/test

Since the utils use dashes this is somewhat jarring. I'm going to open an issue ticket to address that.

**Comment by jason-lange** [comment]
@edsu That worked! Thank you so much. This package is awesome!

**Comment by edsu** [comment]
Thank you @jason-lange -- it's always great to hear people find it useful, even if it's a bit difficult at first. Thanks also for the pointer to @alblaine's [tutorial](https://github.com/alblaine/twarc-tutorial), it had slipped my radar and points to a possible way to improve the twarc documentation.
