### ISSUE TITLE
Media column in CSV contains duplicate entries for tweets with multiple images

### ISSUE THREAD

**Issue by lotsoaxolotls** [DocNow/twarc#239]
For a tweet containing multiple images, I would expect that the media column in the hydrated CSV file would list the URLs of the images in the tweet. Instead, the column contains as many copies of a single URL as there are images in the tweet. Additionally, that URL resolves to the tweet when opened in a browser, not an image file.

For example, this tweet contains two images:
https://twitter.com/NASA/status/1026547971389775878

When I use "twarc hydrate --format csv" for the above tweet's ID, the media column contains the following URL repeated twice, separated by a space:
https://twitter.com/NASA/status/1026547971389775878/photo/1

Is there a reason why the media column in the CSV points to that URL?

I would prefer the media column to contain the two image URLs from the tweet, which are found in the JSON output under the "extended_entities" object:
http://pbs.twimg.com/media/Dj8H73dWsAAxCtV.jpg and http://pbs.twimg.com/media/Dj8H8HIXsAEJp0n.jpg

**Comment by edsu** [comment]
Nice catch, I agree. Can you give v1.5.2 (just released) a try and see if it behaves better?

**Comment by lotsoaxolotls** [comment]
Looks good. Thanks for the quick fix!
