### ISSUE TITLE
Latin characters

### ISSUE THREAD

**Issue by frbrando** [DocNow/twarc#249]
I am having problems when I try a search with Latin characters. Example: 
twarc search "@LulaOficial OR @Haddad_Fernando OR #LulaLivreJá OR #LulaéHaddad" > Haddad_Fernando14092018.jsonl
I get a message"UnicodeDecodeError: 'utf8' codec can`t decode byte 0xe1 in position 161: invalid continuation byte
Please let me know if you have a solution for this. I am sorry if this answer was already discussed elsewhere, but I couldn`t find any fix.
I tried to change my code page to UTF-8 with chcp 65001 on my cmd session, but it still didn`t work.
Thank you, Francisco Brandao

**Comment by SamHames** [comment]
Hey Francisco,

What version of Twarc, Python and operating system (windows version?) are you running? 

I think you're right to suspect the code page as being the problem, the invalid continuation byte error often comes up when latin1 encoded characters are passed to something expecting utf-8.

I won't be near a windows computer for a few days, but I'll see if I can reproduce this on Friday for you.

**Comment by frbrando** [comment]
Thank you so much for your direction, it's working now! I did what you suggested and changed my Python version to 3.7, pip installed twarc again, and added portuguese-Brasil in my language preferences. Not sure what did the trick, but it works!
In time: I use Windows 8.1, 64 bit. So glad to be using twarc again!
