### ISSUE TITLE
retweets command read tweet ids from file

### ISSUE THREAD

**Issue by JanineVH** [DocNow/twarc#255]
Hi, I was wondering if they is a way to retrieve the retweets of several tweets at the same time. That is, is it possible to work with a text file including a list of ids (similar to the hydrating) instead of retrieving the retweets for each tweet manually? Thanks in advance for your help!

**Comment by edsu** [comment]
If I'm understanding you correctly, given a file of tweet identifiers you'd like to be able to fetch all the retweets of those tweets?

**Comment by JanineVH** [comment]
Yes, exactly. It would be great if I could provide a file of tweet identifiers, fetch the retweets of those tweets, and save it to one jsonl file (I guess this could be done when using twarc as a library (like in the examples in https://github.com/ericscartier/twarc). Sorry, my programming skills are still quite limited, therefore I'm not sure how to create such a script.

**Comment by JanineVH** [comment]
I was thinking the same and tried what you suggest in the last line of code (twarc retweets tweet-ids.txt > retweets.jsonl). However, it doesn't seem to work. The twarc logfile shows this error:

<date and time>,111 WARNING 404 from Twitter API! trying again

The shell points to errors in client.py and decorators. py (various lines).
Were you able to collect retweets of a tweet using the suggested line? My problem could also be something else that I'm not aware of.

**Comment by edsu** [comment]
Correct, this functionality would need to be added.

**Comment by edsu** [comment]
Just so you know, the examples in https://github.com/ericscartier/twarc are very out of date. You'll want to look at the documentation at https://github.com/docnow/twarc

**Comment by dfreelon** [comment]
I wrote something to save the retweets of a series of tweets to a file, but whenever it encounters a missing tweet, it retries infinitely. Any easy way to get it to skip 404s instead of iterating ad infinitum? Thanks Ed. /DEEN

**Comment by edsu** [comment]
Heya @dfreelon! Thanks for connecting the dots between what you are doing and this old issue! I'll see about making it possible first using it as a library and add the ability to read retweet ids from command next.

**Comment by dfreelon** [comment]
A quick hacky way to get around this issue is to prefilter your ids using `hydrate`, which does auto-skip dead tweets, then feed the lives ones into `retweets`. Better move fast though--a single tweet removed between when you filter and when you pull retweets will stop the whole job in its tracks.

**Comment by edsu** [comment]
@dfreelon give v1.10.0 (just uploaded to pypi) a try and see if it works as expected. Note the interface to Twarc.retweets has now changed to accept a list. But the command line should work as it did before with the addition of being able to read a file of tweet ids. 404s are logged but do not throw exceptions.

**Comment by dfreelon** [comment]
Hey, works great! Thanks.
