### ISSUE TITLE
Configure: PIN unavailable

### ISSUE THREAD

**Issue by rdrainville** [DocNow/twarc#259]
Upon running twarc configure and receiving the token URL for Twitter, the user is prompted to enter the displayed PIN on Twitter's page. However, no PIN is displayed, and configuration cannot continue

**Comment by rdrainville** [comment]
Certainly, here you go (sorry for the delay):
![screenshot](https://user-images.githubusercontent.com/5984/49340055-8f6ec880-f632-11e8-8852-48f3a9b5ae05.jpg)

**Comment by rdrainville** [comment]
None of the tabs have a PIN.

**Comment by edsu** [comment]
When you run `twarc configure` it should prompt you for the consumer key and consumer secret then it will ask you to visit a URL in your browser. You should see a webpage like this, that asks for your permission to let your application use your account:

<img width="1274" alt="screen shot 2018-12-02 at 10 11 34 am" src="https://user-images.githubusercontent.com/33829/49341396-c507b780-f61a-11e8-82f9-5d9e2e5cbf70.png">

Does that not happen for you?

**Comment by rdrainville** [comment]
Yes, it does, but after I authorise it, I get no PIN. The screenshot supplied above comes from after having authorised twarc.

**Comment by rdrainville** [comment]
Yes, and I have an app ID, but no PIN. I've got consumer API keyes, an access token, and an access token secret, but no PIN.

**Comment by rdrainville** [comment]
Fantastic--that did it. Thank you!

**Comment by nmschorr** [comment]
I believe it's not showing a pin because the user already has the app set up.  Same thing just happened to me.  Configuring your own .twarc file should be in the docs if it isn't already.

**Comment by edsu** [comment]
Oh you mean the use has already approved the app to use their account before? That could be, I'd have to check.

**Comment by nmschorr** [comment]
> Oh you mean the use has already approved the app to use their account before? That could be, I'd have to check.

Yes I got my account a couple of months ago.  And its the free account so it only allows me one "app" which I already have.  So I had no opportunity to start a new app etc.

**Comment by nmschorr** [comment]
I've seen the same problem in other twitter repos that use the same config file method.

**Comment by szeyd** [comment]
Hi all, I have had an issue getting the PIN as well. I see that creating a .twarc file may solve the issue but please can anyone explain 1) how one can be created, 2)where to save it, 3) how can I get it to configure Twarc.  These are probably novice questions but I would appreciate your support. Thanks.
