### ISSUE TITLE
twarc Installed as Package

### ISSUE THREAD

**Issue by lmmonninger** [DocNow/twarc#260]
Hi there!

I'm new to twarc. I am having trouble with the initial configuration. Whenever I attempt to run `twarc configure` or, in my case, `py -m twarc configure`, I get the following error...

`No module named twarc.__main__; 'twarc' is a package and cannot be directly executed`

Is there a solution to this? Will I need to reinstall? How can I ensure twarc is installed appropriately as a module?

**Comment by edsu** [comment]
Hi @lmmonninger I'm glad you found us here. Are you not able to run this on the command line?

`% twarc configure`

Installation of the the twarc module will also give you a twarc command line utility.

**Comment by lmmonninger** [comment]
Thanks for the response!

I was able to get it working by adding the path to twarc to my system environment variables.

**Comment by edsu** [comment]
Interesting, so it wasn't on your path automatically? DId you install with *pip*, and what operating system are you using?

**Comment by lmmonninger** [comment]
I'm in Windows 10 and I used pip. It may be relevant, however, that because I had not added pip to my environment variables either, I installed twarc by calling `py -m pip install twarc`

**Comment by edsu** [comment]
Hmm ok. I haven't really used Python & Pip on Windows before. I assumed when you installed Python3 it put python and pip in your system path. But maybe not? For now I'll say this issue is closed though since it sounds like your immediate problem has been resolved.
