### ISSUE TITLE
json2csv retweet count issue

### ISSUE THREAD

**Issue by melaniewalsh** [DocNow/twarc#264]
Not sure if anyone else has experienced this problem, but when I use twarc's jscon2csv, I get a "retweet_count" column of all zeroes. Same with "favorite_count." Does anyone know what might be going on? Thanks!

**Comment by edsu** [comment]
Hi @melaniewalsh! Did you collect the data using `twarc filter`?

**Comment by melaniewalsh** [comment]
Hi @edsu! Thanks for responding. Yes I did use `twarc filter`.

**Comment by melaniewalsh** [comment]
Oh wait, are there no retweets and favorites because I'm capturing the tweets as soon as they're tweeted...?

**Comment by edsu** [comment]
Yep, that's right! You could extract the tweet ids and rehydrate them if you want to get the current retweets and favs. Let me know if you need help with that.

**Comment by melaniewalsh** [comment]
Ah that makes much more sense! Thanks for clearing it up. And sorry for thinking it was a problem!
