### ISSUE TITLE
media_urls.py chararcter encoding issues 

### ISSUE THREAD

**Issue by marmwar** [DocNow/twarc#268]
Hi, so I am unable to have twarc properly accept my consumer API keys and I have no idea why. It keeps on giving me the error that I am supplying invalid credentials. I am copy and pasting from 
![image](https://user-images.githubusercontent.com/47910111/53293088-5b232800-379b-11e9-992d-6fffefefa0d6.png) this page but it is not working. Am I doing something wrong? ~~Also I am not sure how to use the util files at all. I'm new to python and command line scripts in general so maybe I'm missing something, but trying to use the scripts that are supplied in the utils folder isn't working for me.~~ Would appreciate any assistance, thanks. 

edit: I fixed the utils issue. I got the scripts to work. But now I'm running into charset encoding errors.  I assume its because some of the tweets come from people with names in Asian languages which are encoded with latin1 or something...? Although I'm not sure why its happening when I use the ```media_url.py``` file because it should be scraping just media urls...? I've tried to fix it by going into ```cp1252.py``` and changing errors to "ignore" instead of "strict" but that doesn't seem to be changing anything. Additionally this error happens when I try to use ```wall.py``` as well. 

this is the errors im getting in command line(same in for ```wall.py```:

``` C:\Users\xxx\AppData\Local\Programs\Python\Python37-32>twarc-master\utils\media_urls.py likes.json
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\twarc-master\utils\media_urls.py", line 14, in <module>
    for line in fileinput.input():
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\fileinput.py", line 252, in __next__
    line = self._readline()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\fileinput.py", line 366, in _readline
    return self._readline()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 254: character maps to <undefined>
```

**Comment by edsu** [comment]
It looks like the media_urls.py utility is defaulting to reading JSON data using the [cp1252](https://en.wikipedia.org/wiki/Windows-1252) character set when running on Windows?

**Comment by edsu** [comment]
@marmwar please try pulling the latest version of media-urls.py from github and see if it fixes the issue you were seeing. If not please reopen this ticket with any new information you can provide--or create a new issue.
