### ISSUE TITLE
ImportError: cannot import name 'load_config' from 'twarc'

### ISSUE THREAD

**Issue by DenseLance** [DocNow/twarc#275]
I cannot import 'load_config' and 'default_config_filename' from twarc.
I have followed the following code found here at https://gwu-libraries.github.io/sfm-ui/posts/2016-11-10-twitter-interaction. Thanks if you could help

**Comment by edsu** [comment]
Those instructions are for an older version of twarc. The Twarc constructor will now look for your credentials automatically so the old code:

```python
from twarc import Twarc, load_config, default_config_filename

credentials = load_config(default_config_filename(), 'main')
t = Twarc(consumer_key=credentials['consumer_key'],
          consumer_secret=credentials['consumer_secret'],
          access_token=credentials['access_token'],
          access_token_secret=credentials['access_token_secret'])
```

can now be:

```python
from twarc import Twarc

t = Twarc()
```

As those instructions say, this assumes that your credentials are already stored in `~/.twarc`. To store them there you can run `twarc configure` on the command line.

```

**Comment by DenseLance** [comment]
Thanks @edsu for your help!
