### ISSUE TITLE
emoji.py does not capture all emoji

### ISSUE THREAD

**Issue by frederik-elwert** [DocNow/twarc#278]
Currently, the emoji counter script in utils/emoji.py does not actually capture all emoji, despite its name. It only looks for the Unicode range `\U0001f600-\U0001f650`, which corresponds to emoticons/smileys, but not other types of emoji.

**Comment by frederik-elwert** [comment]
I do have a patch ready that addresses this. However, I am not sure about the intended behaviour, so before submitting it, I’d like to clarify a few points. (Or should I submit a merge request and discuss the details there?)

My main questions:

* I thought about just changing the behaviour of the script, but I realized in some cases people might be interested in just counting emoticons. Should we have two scripts, one for all emoji and one for emoticons? Or a command line parameter?
* I would like to make use of the [emoji](https://pypi.org/project/emoji/) package. However, there’s an import clash: When I use "import emoji", the script finds itself in the search path and thus never imports the external module. I thought about renaming the script to `count_emoji.py` or something similar.

**Comment by edsu** [comment]
HI @frederik-elwert yes, please send a PR and we can discuss in that. I'm definitely open to changing the name of the script from emoji to emojis.py or something like that if it will allow the import to work.
