### ISSUE TITLE
Finding user ids of retweeters of tweets and retweets

### ISSUE THREAD

**Issue by DenseLance** [DocNow/twarc#282]
Hi, how do we find all of the user ids of retweeters of both tweets and retweets?

This is the code that I have currently for finding user ids of retweeters of tweets.

```
from twarc import Twarc

for tweet in t.retweets('1128851321350762498'):
    print(tweet['id_str'])
```

Also, can we find the replies of a tweet using Twarc? I'm a beginner at programming, so please do guide me along the way. Thank you.

**Comment by edsu** [comment]
Unfortunately twarc uses the [statuses/retweets/:id](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-retweets-id) to fetch the tweet ids for tweets that are retweets of a given tweet id. The endpoint only returns the last 100. So unless you are monitoring a tweet regularly you may not be able to get all of the retweets.

You are close to being able to print out the user ids there. Here is an example where the twitter screen name and id of the user who retweeted are printed out:

```python
from twarc import Twarc

t = Twarc()

for tweet in t.retweets('1128851321350762498'):
    print(tweet['user']['screen_name'], tweet[''user']['id_str'])
```

As for replies, there is currently no documented Twitter API call to get them. twarc does have a hack that uses the search API to try to figure out the replies, but it only works within the 7 day window that the search API allows you to search. Here's an example of using it:

```python
from twarc import Twarc

t = Twarc()

# get the tweet
tweet = t.tweet('1128851321350762498')

# get the replies to that tweet
for tweet in t.replies(tweet):
    print(tweet['id_str'])
```

The [twint](https://github.com/twintproject/twint) project takes a different approach of scraping twitter which gets around some of the limits imposed by the API. You may be interested in checking that out if you want to get replies for older tweets or more than 100 retweets at a given time.

**Comment by DenseLance** [comment]
I have checked out the twint project, and it helped me quite a bit (thanks for introducing that to me). However, I do note that there are certain limitations currently; such as being unable to obtain replies or retweets for a given tweet.
