### ISSUE TITLE
Time out on Twarc

### ISSUE THREAD

**Issue by alvinyxz** [DocNow/twarc#283]
Hi Developers,

I am collecting twitter data nonstop on my server using Twarc. But after a few days, it will stop and show this error message:

`caught read timeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=3.05)`

Then it gives me more warnings, such as:

WantReadError                             Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
    452             try:
--> 453                 cnx.do_handshake()
    454             except OpenSSL.SSL.WantReadError:

I am writing, to see if it is Twarc's problem, or my server's problem, or Twitter API's problem.

Thanks.

**Comment by edsu** [comment]
Hi @alvinyxz, 

Thanks for writing! It looks like you are using the `twarc filter` to collect from the streaming API? I've run it for months at a time and not encountered this error.

Can you confirm the version of twarc you have installed and that you are running it on Windows using the Anaconda Python package? Anaconda and Windows haven't been tested that heavily. Also does execution of twarc stop when this happens, and can you provide a full trace of the exception here?

If you are willing it could be interesting to try similar data collection on Windows with Python3.7 downloaded from python.org.

**Comment by alvinyxz** [comment]
Hi @edsu 

Thank you for the prompt reply. I am using `twarc follower` function in Jupiter Notebook. The code looks like this:

`with open("TeachForAmerica.txt","w",encoding="utf-8") as f:
        for ids in t.follower_ids(19918047):
            f.write(ids+'\n')`

The collection was smooth for 3~4 days, and twarc managed the 15-min sleep well. But then, it suddenly got cut off with the warning I pasted above.

Interestingly, it seems that all my four Twitter APIs got cut off at the same time. That's why I am also suspecting it is Twitter's problem, that it is cutting my (non-stop) API access.

What do you think?

**Comment by edsu** [comment]
Interesting, thanks @alvinyxz. I don't think it is Twitter's problem. When you say you had all four of your Twitter APIs cut off at the same time what does that mean? Were you running four different notebooks concurrently?

I'm not sure yet, but I think that this might be an error that only people who have pyopenssl installed will get. From the snippet of stack trace you provided it looks like Anaconda has pyopenssl installed. Twarc uses the python-requests library internally for all HTTP communication, and it will use optionally use pyopenssl if it is available.

Could you paste the full stack trace into this issue so I can try adding some code to Twarc to handle it? Also, if you are in a crunch to get this data I suggest installing Python3 (not from Anaconda) and using it to do the data collection.

**Comment by edsu** [comment]
I closed this because it seems to have gone stale and hasn't apparently been an issue for others. Please reopen if that's not the case!
