### ISSUE TITLE
TypeError 'NoneType' has no len()

### ISSUE THREAD

**Issue by floorperson** [DocNow/twarc#285]
Hi, fairly inexperienced with code here and getting an error message on first time trying to use the search function in Twarc:

Traceback (most recent call last):
  File "/home/USERNAME/anaconda3/bin/twarc", line 11, in <module>
    sys.exit(main())
  File "/home/USERNAME/anaconda3/lib/python3.6/site-packages/twarc/command.py", line 105, in main
    if len(args.lang) > 0:
TypeError: object of type 'NoneType' has no len()

Running python 3.6.5 on Linux Mint. Installation through Pip seemed to go OK, configured using my Twitter credentials etc. This comes up when trying to run basic Twitter search using the "Twarc search TERM > tweets.jsonl" command, but it does not affect the "twarc filter" command, which seems to be working perfectly.

Apologies if I'm missing something obvious, and thank you for any help.

**Comment by edsu** [comment]
Yes, I'm seeing the same problem here. Thanks for the report! Fix should be out momentarily.

**Comment by edsu** [comment]
A fix for this was just released as twarc v1.7.2. You should be able to upgrade with:

    pip install --upgrade twarc

Thanks again for noticing this serious problem. It was introduced in the last release when the --lang parameter was updated.

**Comment by floorperson** [comment]
Thanks for the quick response!
