### ISSUE TITLE
Getting likes using Twarc

### ISSUE THREAD

**Issue by DenseLance** [DocNow/twarc#288]
Hey there, I was just wondering if there is any module in Twarc that we can use to obtain likes, with a maximum count of 100, or even better, more than 100? I have been using urllib2 on Python 2.7 and it has only given me a maximum of 25 user ids of those who liked a particular tweet. Thanks.

**Comment by edsu** [comment]
I don't know if I've seen an API endpoint for getting the list of users who like a tweet. The count is available in the tweet metadata, and is collected by twarc. But there users aren't present in that metadata.

Were you using urllib2 with the the endpoint that the Twitter web client uses when you click on the link to see the users who have liked something? For example:

https://twitter.com/i/activity/favorited_popup?id=1135930368853499906

**Comment by DenseLance** [comment]
Indeed, I have been using urllib2 with the endpoint that the Twitter web client uses. As for twint, I believe that the only module they have for scraping likes from the tweet is the "likes_count", which wouldn't find out which user liked that particular tweet.

So for example:

```
import urllib2
import re

def get_likes(post_id):
    try:
        json_data = urllib2.urlopen('https://twitter.com/i/activity/favorited_popup?id=' + str(post_id)).read()
        found_ids = re.findall(r'data-user-id=\\"+\d+', json_data)
        unique_ids = list(set([re.findall(r'\d+', match)[0] for match in found_ids]))
        return unique_ids
    except urllib2.HTTPError:
        return False

##Example: 
##https://twitter.com/syrian_archive/status/1135930368853499906

print get_likes(1135930368853499906)
```

GET favorites/list only gives the 20 most recent tweets liked by the specified user, which is quite limited if we want to indirectly find our tweet among the user's 20 most recent liked tweets.

**Comment by edsu** [comment]
For better or worse, twarc uses Twitter's documented APIs. So if you are looking for ways to scrape information from Twitter's website you should look at twint or other tools.
