### ISSUE TITLE
Tqdm library while scraping tweets

### ISSUE THREAD

**Issue by bilalghanem** [DocNow/twarc#289]
I would like to thank the developers for the beautiful API :)

I want to suggest them to add tqdm progress_bar with hydrate function, so the user can see how much of the ID .txt file is covered, simply.

Thanks.

**Comment by edsu** [comment]
That is a great idea, thanks for the suggestion!

**Comment by igorbrigadir** [comment]
I missed this earlier, so it's the same as #437 - i'll close this one when that's done too.
