### ISSUE TITLE
Search does not return anything

### ISSUE THREAD

**Issue by ejgutierrez74** [DocNow/twarc#293]
Hello im trying to download the search:
twarc search '@EPS_UdL' > /media/Samsung/searcheps.jsonl

and in one second or two it returns to terminal, and file has nothing inside it.

I have also tried many variations:
twarc search EPS_UdL > /media/Samsung/searcheps.jsonl

When i execute the :
twarc search blacklivesmatter > /media/Samsung/search.jsonl it works well so i have the config and setup ok.

The query in twitter was: https://twitter.com/search?q=(%40EPS_UdL)&src=typed_query

Id need all the tweets that mention or appears the word EPS_Udl

Also is a way to limit the size of serach ? For example search with file result as 1Gb maximum size ? If not it could be a feature request.

Thanks

Ubuntu 18.04

**Comment by edsu** [comment]
Strange, I just ran that command and got 46 tweets.

<img width="805" alt="Screen Shot 2019-07-16 at 11 29 07 AM" src="https://user-images.githubusercontent.com/33829/61307790-f8b7dc00-a7bc-11e9-8037-2317069baea2.png">

What version of twarc do you have installed? Do you see anything interesting in your twarc.log which should be created in the directory where you ran the command?

**Comment by ejgutierrez74** [comment]
And only 46 tweets ? Seems it was a temoral error, now i can download at least 46 tweets...

Is there any config to allow download tweets till for example 1 Gb ( download tweets till you reach a limit) ?

Thanks and sorry for the inconvenience....

**Comment by edsu** [comment]
Note, Twitter's search API only returns results for the last 10 days. So if you are expecting more that's the reason why you are seeing so few. If you are looking to scrape historical data you might be interested in the [twint](https://github.com/twintproject/twint) utility.

We haven't had a need for a size limit configuration so far. JSON data, even in the millions of tweets seems to fit comfortably on disk, especially when piping to gzip e.g.:

    twarc search obama | gzip - > obama.jsonl.gz
