### ISSUE TITLE
Authentication denied for retweets

### ISSUE THREAD

**Issue by SaschaStenger** [DocNow/twarc#301]
Hi there. 
I'm trying to hydrate a scientific dataset and for that i'm using twarc as a library.
Now i was already able to load all the tweet data i needed using the `hydrate()` function.
Now i'm trying to gather all the retweets to those tweets, using:
`retweets = t.retweets(tweet_id)`
But i'm getting denied access by twitter. The message is:
`HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/1.1/statuses/retweets/937384406511005696.json?count=100&tweet_mode=extended`

And behind this message the answer is
`{"errors":[{"code":215,"message":"Bad Authentication data."}]}`

I have tried using other credentials, but so far I had no luck.

**Comment by edsu** [comment]
It looks like that one has been protected or suspended by Twitter:

https://twitter.com/i/status/937384406511005696

I guess an error indicating that would be more useful?

**Comment by SaschaStenger** [comment]
Any idea, on how i can skip those IDs, that have been protected, or suspended?
i'm currently trying:
```
            try:
                retweets = t.retweets(tweet_id)
                with open(dir, 'w+') as outfile:
                    outfile.write("\n".join(retweets) + '\n')
            except urllib.error.HTTPError as err:
                continue
                if err.code == 403:
                    print('Tweet '+ tweet + ' produced Error: ' + err.code)
```
But this doesn't catch the error for me.

**Comment by edsu** [comment]
Try catching `requests.exceptions.HTTPError`?

**Comment by SaschaStenger** [comment]
Thanks, that worked nicely. 

And i do have another question:
Writing the content of the retweets call to a file doesn't work as easy as with tweet objects. 
`TypeError: write() argument must be str, not generator`
Is there an easy way to write it to a file?

**Comment by edsu** [comment]
for tweet in t.retweets(id):
    outfile.write(json.dumps(tweet))
