### ISSUE TITLE
Dehydrated file empty

### ISSUE THREAD

**Issue by SCrockfo** [DocNow/twarc#304]
I collected tweets using twarc and then when I enter the commend dehydrate the .txt file is empty, there is no output. The result is the same with all files tried. 
![Screenshot (39)](https://user-images.githubusercontent.com/58519831/70152701-fb549880-16ad-11ea-8376-594e645c41ce.png)

**Comment by edsu** [comment]
If you look in the `twarc.log` file do you see any decode errors? I think this could be related to #297

**Comment by SCrockfo** [comment]
I do see an error but it looks different to #297 Maybe there was an error in verifying my credentials?
![Screenshot (40)](https://user-images.githubusercontent.com/58519831/70233697-614d2880-175f-11ea-8b92-9fbf866fcf6e.png)

**Comment by edsu** [comment]
Actually, that's what I expected to see. I just tested dehydrate on Windows too and see the same.

The problem is that the default encoding in Powershell on Windows is not UTF8 (which is kind of astounding since it is the standard text encoding today). This means that twarc is unable to properly read the JSON. As I indicated over in #297 there is a solution. I hope to get to it in the next few days, but in the meantime there is a fix you could try.

If you install [Git](https://git-scm.com/) on Windows you will also get a bash shell. This is similar to powershell except it's an actual proper Unix shell. It also uses UTF-8 as the default character encoding. Your twarc command should behave properly if you run it in Bash. At least it appears to work fine for me in my test Windows environment.

<img width="930" alt="Screen Shot 2019-12-05 at 7 17 01 AM" src="https://user-images.githubusercontent.com/33829/70234724-45ca2980-172f-11ea-883d-bd5c152fc047.png">

**Comment by SCrockfo** [comment]
Ok, I'll install Git, as I just tried the fix and there's no UTF-8 option in my system locale and didn't have any luck with the startup commands. Thanks!

**Comment by edsu** [comment]
Yeah, modifying system level stuff in Windows give me the fear. I think the Git solution should work for now until twarc is modified to force reading with utf-8.

**Comment by SCrockfo** [comment]
I still get an error with Bash though about incomplete credentials provided.
![Screenshot (41)](https://user-images.githubusercontent.com/58519831/70237104-b04a8c00-1766-11ea-93db-0241d73c665b.png)

**Comment by edsu** [comment]
Hmm weird. Do you see a similar error when you generated the `jediism_tweets.jsonl`?

**Comment by SCrockfo** [comment]
Nope. It generates without any errors. But same error created on dehydrating on all the different .jsonl files I've tried.

**Comment by edsu** [comment]
Very strange. What version of twarc are you running? `twarc version` should tell you.

**Comment by SCrockfo** [comment]
twarc v1.7.3

**Comment by edsu** [comment]
Could you try running `twarc configure` again?

I'm honestly at a loss trying to understand how `search` would work and `dehydrate` wouldn't, when it comes to the keys.

**Comment by SCrockfo** [comment]
I ran configure again and I noticed that it didn't tell me where my twitter credentials were saved, nor did it say 'happy twarcing' - does this mean something has gone wrong with the configuration?
![Screenshot (42)](https://user-images.githubusercontent.com/58519831/70238929-98750700-176a-11ea-8b29-d477ec27bbdb.png) 

Also search does not work in Bash, same error
![Screenshot (43)](https://user-images.githubusercontent.com/58519831/70239013-bd697a00-176a-11ea-86b7-0f089ad3ea79.png)

**Comment by edsu** [comment]
Oh good, I'm glad search isn't working. It would be very strange if the credentials worked for one command and not another.

Do you see a line like this in your `twarc.log`? 

    2019-12-05 10:57:14,208 INFO loading None profile from config /Users/edsu/.twarc

**Comment by edsu** [comment]
PS. I deleted your comment that contained your twitter keys in the image. Just for your own peace of mind.

**Comment by SCrockfo** [comment]
Yep...

2019-12-03 14:50:14,407 INFO loading None profile from config C:\Users\scrockfo\.twarc

And thanks for deleting that! I was going to after you replied and you saved me the trouble, I appreciate it.

**Comment by edsu** [comment]
Interesting, so does the file `C:\Users\scrockfo.twarc` exist?

**Comment by SCrockfo** [comment]
Yes, it does!

This is what it says in the twarc log for when I configured in Bash:

2019-12-05 13:51:00,941 INFO loading None profile from config H:\.twarc

Which suggests it's trying to run from the h: drive (which is not where twarc is)

**Comment by SCrockfo** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/58519831/70390960-2f8ec880-19d0-11ea-88eb-56d47e1140de.png)

**Comment by edsu** [comment]
I'm not quite sure why twarc isn't finding your config file predictably. If you want you can explicitly tell twarc what configuration to use. See if these steps work for you:

    twarc --config twarc.conf configure

This should have created a `twarc.conf` file in your current working directory. You can put it wherever you want as long as you consistently refer to it. So for example then you could run a search operation using your config file:

    twarc --config twarc.conf search obama

**Comment by SCrockfo** [comment]
Ok! I just tried it and it worked without an error. I think the problem is the H: drive. It's my personal drive on the university server and I'm off site today, so not connected to it, H: isn't available, and it's worked. Searched and dehydrated without any errors!

**Comment by edsu** [comment]
Ahah, that makes total sense. Is H: set as your home directory on Windows?

**Comment by SCrockfo** [comment]
Yes, and I can't change it because university bureaucracy

**Comment by edsu** [comment]
This is really good to know. Thanks for taking the time to help figure it out. I imagine others can be in similar situations. I'll leave this ticket open as a reminder to update the README.md to mention that the config file can be explicitly set.

**Comment by SCrockfo** [comment]
No problem. Thanks for helping me, I appreciate it. One more question: what's the command for utils in Bash? I tried % and it doesn't recognise

**Comment by edsu** [comment]
That's a confusing artifact of the documentation. It's supposed to indicate the command line prompt. You can remove it?

**Comment by SCrockfo** [comment]
oh so I'm meant to be in utils file when I run this?

**Comment by SCrockfo** [comment]
I tried the same line with the % and it just said no such file or directory

**Comment by SCrockfo** [comment]
*without the %

**Comment by edsu** [comment]
Ah, sorry. The utils are not installed when you `pip install twarc`. They are a collection of little Python programs people have contributed for working with collected Twitter data. At the moment the only way to get them is to either:

    git clone https://github.com/docnow/twarc

Or to download the twarc source code from:

    https://github.com/DocNow/twarc/archive/v1.7.5.zip

In either case this will give you a directory called `utils` that contains the programs.

**Comment by SCrockfo** [comment]
Yep, I have them installed from github already. Do I need to be in utils directory in Bash to run them?

**Comment by edsu** [comment]
Yes, if you are in the utils directory you should be able to run them directly there. For example:

    python3 urls.py tweets.jsonl

**Comment by SCrockfo** [comment]
Ok I found I had to put the jsonl file into the utils folder to get these to work. 

But now I have! Success! :)

**Comment by edsu** [comment]
Great, you should be able to reference the data where it happens to be, by using its full path.

**Comment by edsu** [comment]
I think this got resolved satisfactorily? If not please feel free to reopen.
