### ISSUE TITLE
Normalize dashes and underscores in command line arguments.

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#305]
It would be good to make sure that the twarc utilities (and twarc itself) use a consistent style for command line options with respect to underscores and dashes. For example, this is confusing:

    utils/twarc-archive.py --twarc_command timeline edsu data

I haven't done an extensive look but for backwards compatibility we should probably support both if there is a lot of divergence in the naming.

**Comment by igorbrigadir** [comment]
On a quick look, i think the way it now is fine - except `twarc` uses underscores `_` https://github.com/DocNow/twarc/blob/main/twarc/command.py while `twarc2` uses `-` dashes https://github.com/DocNow/twarc/blob/main/twarc/command2.py

**Comment by edsu** [comment]
I think since things are consistent in twarc2 and twarc2 will replace twarc, this can be closed.
