### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#306]
@alblaine has created a useful [tutorial](https://github.com/alblaine/twarc-tutorial) for using twarc. It might be good to think about how something like this could live in the twarc repository itself, or if the existing docs could be improved to address ease of use.

**Comment by csantanaes** [comment]
> @alblaine has created a useful [tutorial](https://github.com/alblaine/twarc-tutorial) for using twarc. It might be good to think about how something like this could live in the twarc repository itself, or if the existing docs could be improved to address ease of use.

@edsu can you help for Twarc anda Twitter full archive?

**Comment by igorbrigadir** [comment]
It's a few years old but there's still some useful bits in here - the way to integrate this would be to edit a new page in the wiki https://github.com/DocNow/twarc/wiki or directly make a PR for a page in the docs https://github.com/DocNow/twarc/tree/main/docs
