### ISSUE TITLE
search by tweet source

### ISSUE THREAD

**Issue by akrolla** [DocNow/twarc#309]
is it possible?

**Comment by edsu** [comment]
After consulting @igorbrigadir's excellent reference [Advanced Search on Twitter](https://github.com/igorbrigadir/twitter-advanced-search/blob/master/README.md) it appears YES!

The trick is you need to combine the source with another term. So for example: [`obama source:twitter_for_iphone`](https://twitter.com/search?q=obama%20source%3Atwitter_for_iphone&src=typed_query), which can work in twarc:

    twarc search 'obama source:twitter_for_iphone' > tweets.jsonl

One thing to note when looking at the results is that this will match the source of the retweet when a retweet is present.

**Comment by akrolla** [comment]
nice thank you. what about by api is there a reference there?

**Comment by edsu** [comment]
I dont understand the question.

**Comment by akrolla** [comment]
so if i were to code something using 

for tweet in t.search('obama source:twitter_for_iphone'):

       print(tweet["full_text"])

**Comment by edsu** [comment]
Yep!

**Comment by akrolla** [comment]
excellent. thank you !
