### ISSUE TITLE
can I limit the time for the replies?

### ISSUE THREAD

**Issue by MeixianWang2** [DocNow/twarc#317]
From the twarc, I can get the replies back ward to 7 days, could I get the replies start from specific time ?

**Comment by Galang23** [comment]
Twitter public search API limits its function to search only tweets in the past 7 days. You can get replies that is posted in the last 7 days or in between it. No more than 7 days.

**Comment by MeixianWang2** [comment]
> Twitter public search API limits its function to search only tweets in the past 7 days. You can get replies that is posted in the last 7 days or in between it. No more than 7 days.

**Comment by MeixianWang2** [comment]
> Twitter public search API limits its function to search only tweets in the past 7 days. You can get replies that is posted in the last 7 days or in between it. No more than 7 days.

Thanks a lot! I assume I will use the paid twitter API.
