### ISSUE TITLE
Parse_stream() returns NULL when using twarc hydrated tweets .json

### ISSUE THREAD

**Issue by aroberts394** [DocNow/twarc#322]
I hydrate a txt file of Tweet IDs using:
`twarc hydrate tweet-id.txt > tweet-id.jsonl
`
After which I try to parse the .jsonl file into a R data frame but the function returns a NULL. I used this:
`tweetdf <- parse_stream("tweet-id.jsonl")
`
I even tried hydrating into a .json file but I still get a NULL when I try to parse it. I'm not sure what the problem may be.

**Comment by ecalvo68** [comment]
Indeed. It is easy to select variables and load them to a dataframe using a function such as this:

twList<- function(tw=tw){
	test<- tryCatch(fromJSON(tw), error=function(e) NULL)
	 out<- c(test$id_str,
    ifelse(is.null(test$text)==TRUE,test$full_text,test$text),
    test$user$screen_name, 
ifelse(is.null(test$user$verified)==TRUE,"",test$user$verified),
ifelse(is.null(test$user$friends_count)==TRUE,"",test$user$friends_count),
ifelse(is.null(test$user$followers_count)==TRUE,"",test$user$followers_count),
ifelse(is.null(test$user$location)==TRUE,"",test$user$location),
ifelse(is.null(test$created_at)==TRUE,"",test$created_at),
ifelse(is.null(test$retweeted_status$user$screen_name)==TRUE,"", test$retweeted_status$user$screen_name),
ifelse(is.null(test$retweeted_status$user$verified)==TRUE,"", test$retweeted_status$user$verified),
ifelse(is.null(test$retweeted_status$user$friends_count)==TRUE,"", test$retweeted_status$user$friends_count),
ifelse(is.null(test$retweeted_status$user$followers_count)==TRUE,"", test$retweeted_status$user$followers_count),
ifelse(is.null(test$retweeted_status$user$location)==TRUE,"", test$retweeted_status$user$location),
ifelse(is.null(test$retweeted_status$created_at)==TRUE,"", test$retweeted_status$created_at),
ifelse(is.null(test$retweeted_status$favorite_count)==TRUE,"", test$retweeted_status$favorite_count),
ifelse(is.null(test$retweeted_status$id_str)==TRUE,"", test$retweeted_status$id_str),
ifelse(is.null(test$lang)==TRUE,"", test$lang),
ifelse(is.null(test$source)==TRUE,"", test$source),
ifelse(is.null(test$user$id_str)==TRUE,"", test$user$id_str),
ifelse(is.null(test$retweeted_status$user$id_str)==TRUE,"", test$retweeted_status$user$id_str),
ifelse(is.null(test$in_reply_to_status_id_str)==TRUE,"", test$in_reply_to_status_id_str),
ifelse(is.null(test$in_reply_to_screen_name)==TRUE,"", test$in_reply_to_screen_name),
ifelse(is.null(test$retweeted_status$in_reply_to_screen_name)==TRUE,"", test$retweeted_status$in_reply_to_screen_name),
ifelse(is.null(test$user$created_at)==TRUE,"", test$user$created_at))
	out2<- c(tryCatch(ifelse(is.null(test$entities$urls[[1]]$url)==TRUE,"",test$entities$urls[[1]]$expanded_url), error=function(e) NULL))
	out2<-ifelse(is.null(out2)==TRUE,"",out2)
	out.f<-c(out,out2)
	out.f
  			     }

The tryCatch function is generally good enough to handle errors in loading. I have been using this function for several years without any problems.
E.

**Comment by aroberts394** [comment]
@edsu thanks! the for loop parses through the jsonl file but it then sends it as a list but I'm looking to save it as a data frame just like the parse_stream() function from the rtweet package. 

Also, it looks like there are a lot of variables missing compared to the number of variables that are available when using the stream_tweets() function in the rtweet package using the Twitter API.

**Comment by edsu** [comment]
Yeah, unfortunately parsing JSON in R isn't something we can help you with here. But if you'd rather not use the JSON and want to use CSV instead you could use the [json2csv.py utility] to convert existing data you've collected, or simply write CSV when you are hydrating:

     twarc --format csv hydrate tweet-id.txt > tweets.csv

As you say, there is a lot more detail in the JSON that can be easily represented in a table. But I think you will find twarc's CSV output to be pretty rich.
