### ISSUE TITLE
I rehydrated using user ids. How can I change jsonl file to CSV file?

### ISSUE THREAD

**Issue by WonKim-Stat** [DocNow/twarc#324]
Hello all, 

I am struggling to convert the Jsonl file to CSV file.. I looked up on Google but I can only found converting Json file not Jsonl file. Anyone can Help me please?

I have list of jsonl files such as "coronavirus-tweet-id-2020-01-21-22.jsonl"

**Comment by WonKim-Stat** [comment]
Thank in advance for all your valuable advice!

**Comment by edsu** [comment]
There is not one canonical way to convert JSONL (line oriented JSON) or JSON to CSV. But you may want to try this utility from the twarc github repository:

https://github.com/DocNow/twarc/blob/master/utils/json2csv.py
