### ISSUE TITLE
Getting geolocation question

### ISSUE THREAD

**Issue by WonKim-Stat** [DocNow/twarc#328]
Hi, it would be a silly question, but Is there any way to get geolocation data using tweet Ids?
I exported full data set by hydrating ids file, but it seems like it only includes columns of "geo_enabled", "geo", and "location". This gives me no specific geolocation I am looking for.

**Comment by lavarthan** [comment]
@WonKim-Stat 
why did you close without a single comment?

**Comment by edsu** [comment]
Please reopen if you still have a question about this @WonKim-Stat.
