### ISSUE TITLE
Suggestion: Provide directive to users getting started by-example

### ISSUE THREAD

**Issue by machawk1** [DocNow/twarc#330]
I have used twarc in the past, but came across a command while on a new machine, so reinstalled via `pip` and immediately ran a command like `twarc filter --folow ...` and was provided this response:

```py
Traceback (most recent call last):
  File "/usr/local/bin/twarc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/twarc/command.py", line 104, in main
    app_auth=args.app_auth
  File "/usr/local/lib/python3.7/site-packages/twarc/client.py", line 76, in __init__
    self.validate_keys()
  File "/usr/local/lib/python3.7/site-packages/twarc/client.py", line 839, in validate_keys
    raise RuntimeError('Incomplete credentials provided.')
RuntimeError: Incomplete credentials provided.
```

I understand what needs to be done to get up-and-running, or at least can refer to the documentation, but a more user friendly directive/message here like `Please first run twarc configure` would be less "scary" for those new to the tool or intimidated by stack traces and verbose command-line output.

**Comment by edsu** [comment]
Great idea, thanks for taking the time to jot it down. If you had the time/inclination to code it up I would happily merge it. But if not, we'll get to it.

**Comment by machawk1** [comment]
@edsu, PR sent in #331
