### ISSUE TITLE
Invalid credentials after 1.9.1 upgrade

### ISSUE THREAD

**Issue by aborruso** [DocNow/twarc#334]
Hi,
I have updatet twarc to 1.9.1 and now I have `RuntimeError: Invalid credentials provided.`

If I run `configure` and insert again credentials, I have `Error: invalid credentials.
Please check that you are copying and pasting correctly and try again.`

Thank you

**Comment by edsu** [comment]
Hi @aborruso can you paste the command you are running to help debug? I'm not observing the same problem here.

I'm also curious if downgrading to your previous version makes the problem go away?

**Comment by aborruso** [comment]
hi @edsu also after downgrading

I have

```
Traceback (most recent call last):
  File "/home/aborruso/.local/lib/python3.7/site-packages/twarc/client.py", line 831, in validate_keys
    self.get(url)
  File "/home/aborruso/.local/lib/python3.7/site-packages/twarc/decorators.py", line 31, in new_f
    resp.raise_for_status()
  File "/home/aborruso/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Authorization Required for url: https://api.twitter.com/1.1/account/verify_credentials.json?tweet_mode=extended
This is a protected or locked account, or the credentials provided are no longer valid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aborruso/.local/bin/twarc", line 8, in <module>
    sys.exit(main())
  File "/home/aborruso/.local/lib/python3.7/site-packages/twarc/command.py", line 104, in main
    app_auth=args.app_auth
  File "/home/aborruso/.local/lib/python3.7/site-packages/twarc/client.py", line 76, in __init__
    self.validate_keys()
  File "/home/aborruso/.local/lib/python3.7/site-packages/twarc/client.py", line 835, in validate_keys
    raise RuntimeError('Invalid credentials provided.')
RuntimeError: Invalid credentials provided.
```

I have a `/home/aborruso/.twarc` file with the right data :(

**Comment by edsu** [comment]
Hmm, maybe visit the developer.twitter.com and make sure the app is still there and that the keys are correct? Is the Twitter account you are using to authorize still active?

If you like you can also remove your .twarc (or move it somewhere as a backup) and rerun `twarc configure` to see if the key handshake works?

**Comment by aborruso** [comment]
mmm :(

The Twitter account I'm  using to authorize is still active. I have deleted the twarc file, after configuring I have

```
Error: invalid credentials.
Please check that you are copying and pasting correctly and try again.
```

**Comment by edsu** [comment]
Do you get that error message when you run `twarc configure` ?

**Comment by aborruso** [comment]
yes, after inserting Consumer API keys

**Comment by edsu** [comment]
Weird! Well assuming there is no copy/paste error perhaps try creating a new app and getting a new pair of consumer keys?

**Comment by aborruso** [comment]
> Weird! Well assuming there is no copy/paste error perhaps try creating a new app and getting a new pair of consumer keys?

I try, but I think I will have the same :(

Thank you

**Comment by edsu** [comment]
If you have the same error can you paste the output of `pip3 freeze` here? I'm assuming you are running python3?

**Comment by aborruso** [comment]
@edsu something very strange: I must apply again for a developer account.

It's very strange because I have already 6 apps. Now I must wait for approval

**Comment by edsu** [comment]
Ugh, I was worried that might be what was happening. I imagine all the apps are no longer functional. Please let me know what happens with this, but I'm going to close this issue since it doesn't appear to be related to twarc itself.
