### ISSUE TITLE
Save each user to file while retrieving a large following?

### ISSUE THREAD

**Issue by mspanish** [DocNow/twarc#335]
Hey this is amazing!  I see you have the ability to output files - but I don't see any example of how to do that with the module rather than the terminal. Could you post an example? In particular I'd like to save each user as it comes in, as an account with 50,000 followers might time out and it would be nice to resume where it left off and have the data saved!  Thanks again this is a fantastic library.

**Comment by mspanish** [comment]
I figured out how to save to JSON, but the file is HUGE for a guy w/ 100,000 followers! So now I'm looking at trying to retrieve only the important data for each follower, and write to CSV. Will try to post that update as I figure it out :)

 file_dir = 'twitter_data'
    file_name = f"{screen_name}_followers.json"
    file_write = os.path.join(file_dir,file_name)
 
    t = Twarc(consumer_key, consumer_secret, access_token, access_token_secret)
    
    follower_ids = t.follower_ids(screen_name)

    #print(user['screen_name'])

    with open(file_write,'w') as writefile:    
        for user in t.user_lookup(follower_ids):
            line = json.dumps(user)
            #writing tweet to file
            writefile.write(line)

**Comment by edsu** [comment]
I'm glad you figured it out @mspanish! As your code shows `follower_ids()` is a generator that you can then pass to `user_lookup()`.

I personally find it useful to write the big JSON file and then write other programs to extract the things I need rather than having to go back and do the data collection from Twitter when I want to extract something new. But if you come up with a good utility for serializing users as CSV definitely submit it as a pull request.

**Comment by mspanish** [comment]
Sorry don't have a great utility but I'm going to work both on sending the right command to avoid getting the extended stuff in the user objects, as well as writing only the fields I want - but here is the super naive version that just grabs the stuff and outputs each line to csv instead of json!

    file_dir = 'twitter_data'
    file_name = f"{screen_name}_followers.csv"    
    file_write = os.path.join(file_dir,file_name)
 
    t = Twarc(consumer_key, consumer_secret, access_token, access_token_secret)
    
    follower_ids = t.follower_ids(screen_name)

    #print(user['screen_name'])

    with open(file_write,'a') as writefile:    
        for user in t.user_lookup(follower_ids):
            line = json.dumps(user)
            csvWriter = csv.writer(writefile)
            header = user.keys()
            values = user.values()
            csvWriter.writerow(header)
            csvWriter.writerow(values)
