### ISSUE TITLE
utils/wall.py redownloading the profile photo of the same user

### ISSUE THREAD

**Issue by tddschn** [DocNow/twarc#338]
When executing `python3 utils/wall.py timeline.jsonl > timeline.html`, the wall.py script was downloading the profile photo of the same user from the same url `http://pbs.twimg.com/profile_images/*******/<profile_photo>.jpg` for hundreds of times, which is not necessary. 

It took 1 min on my machine to generate the `timeline.html` file for a twitter timeline of 700 tweets. 

Is it possible to use the local cache in `img` directory to speed up the HTML generation? Thanks!

**Comment by edsu** [comment]
@tddschn thanks for noticing this! I think your solution is a good idea, and should be relatively easy to implement. Do you want to give it a try and send a pull request?

**Comment by tddschn** [comment]
Thanks for the quick reply!
I'd love to do it and file a PR, but I'm new to python and I'm afraid I'm not able to do it :(
