### ISSUE TITLE
No response after inputing the command 

### ISSUE THREAD

**Issue by zyx-csu** [DocNow/twarc#339]
When I input the command,there was no response at the command line .I noticed a new file has been generated under the specified file folder,but the content of the file has always been empty.

**Comment by edsu** [comment]
Hi @zyx-csu do you see a twarc.log file?

**Comment by zyx-csu** [comment]
thank you very much for answering my question! I have known my problem now!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DocNow/twarc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 下午5:45
收件人:&nbsp;"DocNow/twarc"<twarc@noreply.github.com&gt;;
抄送:&nbsp;"地信1701钟宇翔"<495878719@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [DocNow/twarc] No response after inputing the command  (#339)





 
Hi @zyx-csu do you see a twarc.log file?
