### ISSUE TITLE
from_date or until_date

### ISSUE THREAD

**Issue by jincio** [DocNow/twarc#340]
Hi, 

Thanks for your amazing work. I'm trying to get tweets from a specific period. 
For instance, I tried:  

`twarc search '(from:jlincio) until:2017-09-01 since:2017-04-01' > search.jsonl `

`twarc search @jlincio\
  --from_date 2017-04-01 \
  --to_date 2017-09-01 \
  --limit 1000 \
  > tweets.jsonl`

@jlincio is my account. In either case, I get an empty file.  

If I use: 

`twarc search 'from:jlincio until:2017-09-01' > search.jsonl`

I get data but the query doesn't use the date. 

I would highly appreciate any help, 

Thanks.

**Comment by SamHames** [comment]
Unfortunately the free Twitter search API that twarc uses for that command only makes the last 7 days of tweets available (searching further back through the API requires the paid premium access).

If you're only interested in your own tweets you might be able to retrieve your own timeline: `twarc timeline > my_tweets.jsonl`  (assuming twarc is authenticated as the jlincio user), or the [twitter archive download](https://help.twitter.com/en/managing-your-account/how-to-download-your-twitter-archive) when that comes back online.

**Comment by edsu** [comment]
And if you are looking for someone else's tweets (or your own) you can use [twint](https://github.com/twintproject/twint) which scrapes the web interface, so YMMV:

    twint --search 'from:jlincio until:2017-09-01 since:2017-04-01' --output csv --csv --output tweets.csv

**Comment by jincio** [comment]
> Unfortunately the free Twitter search API that twarc uses for that command only makes the last 7 days of tweets available (searching further back through the API requires the paid premium access).
> 
> If you're only interested in your own tweets you might be able to retrieve your own timeline: `twarc timeline > my_tweets.jsonl` (assuming twarc is authenticated as the jlincio user), or the [twitter archive download](https://help.twitter.com/en/managing-your-account/how-to-download-your-twitter-archive) when that comes back online.

Thanks so much for your answer. For a project, I  need to get tweets from different accounts for different periods. Correct me if I'm wrong, but the best way to do it (no paying) is first to get tweets' ids and then use twarc to hydrated those ids. Would that work?

**Comment by jincio** [comment]
> And if you are looking for someone else's tweets (or your own) you can use [twint](https://github.com/twintproject/twint) which scrapes the web interface, so YMMV:
> 
> ```
> twint --search 'from:jlincio until:2017-09-01 since:2017-04-01' --csv --output tweets.csv
> ```

It works well! Thanks so much.

**Comment by igorbrigadir** [comment]
Full archive search is now supported in `twarc2 search --archive` https://twarc-project.readthedocs.io/en/latest/twarc2/#search so it's possible to get old tweets like this:

```
twarc2 search --archive --start-time "2017-04-01" --end-time "2017-09-01" "(from:jlincio)" search.jsonl
```

and to turn it into a CSV, 

```
pip install twarc-csv
```

and 

```
twarc2 csv search.jsonl tweets.csv
```
