### ISSUE TITLE
How to only get tweet text while hydrating tweet id?

### ISSUE THREAD

**Issue by zarasash** [DocNow/twarc#341]
Hello, that might be an easy question but I am very new using twarc.
I was wondering if there is any way to only get tweetID and tweet text while hydrating tweets.
I use twarc but in the output file, it gives me a bunch of stuff which I do not need. 
I wanted to know if I can only get specific columns such as tweet text or not.

**Comment by edsu** [comment]
Hi @zarasash. It's actually not an easy question and gets to the heart of what twarc is built for. twarc really is focused on getting what Twitter thinks a tweet is as JSON out as a file. From there you can modify it into something that suits your needs. One exception to that is the CVS output option in twarc. A tweet has a lot of structure, and hierarchy to it that don't lend it to serialization as a CSV, but still you can get some useful things out of the JSON and into a CSV for viewing in a spreasheet tool like Google Sheets or Excel.

If you only want the tweet id and tweet text I recommend you use the csv output and then just cut out the columns from the resulting file with something like [csvkit](https://csvkit.readthedocs.io/en/latest/). So something like this:

```
twarc timeline barackobama --format csv --output tweets.csv
csvcut -c id,text tweets.csv > id-text.csv
```

Or you could even connect twarc and csvcut with a pipe:

```
twarc timeline barackobama --format csv | csvcut -c 'id,text' > tweets.csv
```

Does that help?

**Comment by zarasash** [comment]
yes, thank you that make sense.  that was great help.

**Comment by zarasash** [comment]
Hello, sorry for bothering you again,
I was using the code you gave me but for hydrating 

`twarc hydrate id.txt --format csv --output tweets.csv
csvcut -c id,text tweets.csv > id-text.csv`

**Comment by edsu** [comment]
@zarasash are you doing the two commands at once? You will need to do them separately, or connect them with a pipe.

Here are the commands executed separately, which creates an intermediary file `tweets.csv`. Note: you would type <enter> at the end of each line in your terminal.

    twarc hydrate id.txt --format csv --output tweets.csv
    csvcut -c id,text tweets.csv > id-text.csv

And here they are connected with a pipe, which connects the output of the first command to the input of the second. Note this does not create the intermediary `tweets.csv` file.

    twarc hydrate id.txt --format csv  | csvcut -c 'id,text' > id-text.csv

**Comment by zarasash** [comment]
yes, i did both ways.
for the first one, it creates the tweet.csv file but the id_text file is empty (it does only create that and show the header of id and text column).

for the second one it says that 'id does not exist. i have change ' to " but still the same result.
the first result:
![d](https://user-images.githubusercontent.com/69239918/89674395-f6508480-d8df-11ea-865f-4bb9434aa828.jpg)
the second result:
![f](https://user-images.githubusercontent.com/69239918/89674397-f781b180-d8df-11ea-9bdd-d7604b9b5e87.jpg)
output:
![g](https://user-images.githubusercontent.com/69239918/89674779-9dcdb700-d8e0-11ea-872f-19c985e3430f.jpg)

**Comment by edsu** [comment]
Hmm, in the first case it looks like you are getting an encoding error. Windows somewhat annoyingly does not use UTF-8 as its default encoding, which can complicate working at the command line sometimes.

Does it help if you try the first way again but explicitly set the encoding when calling csvcut?

```
twarc hydrate id.txt --format csv --output tweets.csv
csvcut -e utf8 -c id,text tweets.csv > id-text.csv
```

**Comment by zarasash** [comment]
hi again.
 I guess still not working. i may get the file and select the two column by python command.

![image](https://user-images.githubusercontent.com/69239918/89816324-4593f080-db3e-11ea-97ba-6eeeb8fc568f.png)

thank you so much anyway.

**Comment by edsu** [comment]
Yes, I think you are right. FIghting with the default encoding on Windows is not fun. Creating a little Python program is the way to go:

```python
import csv

out = csv.writer(open('tweets-short.csv', encoding='utf8')
out.writerow(['id', 'text'])

for row in csv.DictReader(open('tweets.csv', encoding='utf8')):
    out.writerow([row['id'], row['text']])
```

**Comment by zarasash** [comment]
Thank you. i will do that:)
