### ISSUE TITLE
problem when running hydrate.py: json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 397902 (char 397901)

### ISSUE THREAD

**Issue by yuki-yue** [DocNow/twarc#342]
![error](https://user-images.githubusercontent.com/68763881/90997338-e0d39e00-e5f3-11ea-8876-a4466ae79db3.JPG)
when i run hydrate.py ,problems occur as JSONDecodeError and i can't fetch tweets any more.How can i handle this?

**Comment by edsu** [comment]
Hi @yuki-yue Are you looking at hydrate.py in this repository? https://github.com/echen102/COVID-19-TweetIDs

**Comment by yuki-yue** [comment]
yes




On 08/24/2020 17:59, Ed Summers wrote:

Hi @yuki-yue Are you looking at hydrate.py in this repository? https://github.com/echen102/COVID-19-TweetIDs

**Comment by yuki-yue** [comment]
I've tried "twarc hydrate XXX.txt> XXX.jsonl  " also and this error still occurred after running several hours .It's like a ticking time bomb, I don't know when this error will stop the process.




On 08/24/2020 18:03, yuki-yue wrote:
yes




On 08/24/2020 17:59, Ed Summers wrote:

Hi @yuki-yue Are you looking at hydrate.py in this repository? https://github.com/echen102/COVID-19-TweetIDs

**Comment by edsu** [comment]
Interesting. It looks like you are getting truncated JSON data from the Twitter API. Perhaps something is disrupting your network connection?

**Comment by yuki-yue** [comment]
When the network is unstable, it indicates a "connection error ".It  reconnects in a few seconds and continues to crawl. I think the problem may be related to the json format? But i don't know how to handle this. It's an error that seldom occurs ,usually after i running the hydrate.py few hours, Do you think it's ok to skip this error by adding "pass" into the try-exception in decoder.py file and make it continue to work?

**Comment by igorbrigadir** [comment]
Yeah, adding a `pass` there may help to recover. If you still have trouble with the original repo, may e an issue here would be better https://github.com/echen102/COVID-19-TweetIDs/issues

Otherwise, I would recommend using the new `twarc2 hydrate` command on the files
