### ISSUE TITLE
'twarc search' retrevieing slightly different results compared to 'rtweet::search_tweets()'?

### ISSUE THREAD

**Issue by jeffcsauer** [DocNow/twarc#345]
Hi all,

Trying to get off the ground with the Twitter API and doing some sanity checks for basic calls across different API wrappers. I really like `twarc` and `rtweet`, and it has been a pretty straightforward experience so far! Before running larger calls, I'm trying to wrap my head around the basic functionality of the API, especially around geocoded calls. As my baseline, I am trying to pull **all** the tweets in a two-mile area around College Park, MD, in the last 7 days. 

Here is the `twarc` command I am using:

```bash
twarc search --geocode 38.987202,-76.945999,2mi > tweets.jsonl
```

Which returned 3594 records. Shortly thereafter, I tried the following command in `rtweet`:

```r
rt2mi <- search_tweets(
  geocode = "38.987202,-76.945999,2mi",
  retryonratelimit = TRUE,
  n = 10000
)
```

Which returns about 3610 tweets. 

Surface-level checks indicate that they are indeed pulling the same tweets, but I'm coming up a bit short using `twarc`. 

Are there any obvious reasons for this discrepancy? Or perhaps I'm missing something about the underlying twitter API? I am using the same API keys and access tokens.

**Comment by edsu** [comment]
Hmm, I'm not sure. Did you just run this test? I tried it with twarc and got 3612 tweets which is very  similar to watch you saw with rtweet. I've attached the ids here: 

[ids.txt](https://github.com/DocNow/twarc/files/5250164/ids.txt)

**Comment by jeffcsauer** [comment]
Hey! Thanks for the quick response. Might I ask how you are counting the number of tweets?

I think the issue is actually how I am parsing the .jsonl file, rather than anything wrong with `twarc`. I'll close for now!

**Comment by edsu** [comment]
Yes, that's a good question. The twarc command line outputs each tweet on a line so you can count the number of lines in the file. On Unix/OSX you can:

    twarc search --geocode 38.987202,-76.945999,2mi > tweets.jsonl
    wc -l tweets.jsonl

Does that make sense?

**Comment by jeffcsauer** [comment]
Definitely! They are now matching nearly identically (n=3611 with `twarc`, n=3613 with `rtweet`). I'll work on refining my parser for the .jsonl files. 

Really enjoying `twarc` - thanks again for the quick response! 😄

**Comment by edsu** [comment]
If you figure out a good way to read line-oriented-jsonl from R please let us know as it's a question that has come up here periodically, e.g. #322
