### ISSUE TITLE
Limit on number of active twarc filter requests?

### ISSUE THREAD

**Issue by jeffcsauer** [DocNow/twarc#350]
Hi all, 

I had a couple of quick questions regarding the `twarc filter` command - the first might be considered an issue but the second is a usage question that wasn't readily apparent from the docs. 

1. It seems that the limit of `twarc filter` commands that can be running on a single machine at a given time in two. The third (or fourth, etc) seem to execute and hang, but the file remains empty. Is it possible to run more than two `twarc filters` at a time? 

2. When using `twarc filter`, how should phrases that have a space in them be handled? For example, if I wanted to get Tweets on the "Mars Rover", would it be `twarc filter mars-rover`? Although this seems to force a hyphen in the search. 

Been using `twarc` for a couple of weeks now and I really enjoy it! Will make sure that it is accredited properly in any publicly facing results.

**Comment by SamHames** [comment]
Hi Jeff,

1. The number of filter streams is a Twitter imposed API limitation - you can have one stream active per authenticated user/application and *per IP* - you could have a search going in parallel to the filter though.
2. Unlike the search API, I don't think the filter endpoint supports phrases - if you want to find phrases then you would need to filter for tweets that contain all the terms in the phrase, then do a post processing operation to find which actually contain the phrase of interest.

**Comment by edsu** [comment]
1. The filter limit of 2 per access token is a limit imposed by Twitter and not by twarc.
2. If you do a `twarc filter "mars rover"` the keyword `mars rover` will be sent to the Twitter API. You can confirm this by looking in your twarc.log file where you should see something like:

    2020-09-29 22:48:18,200 INFO posting ('https://stream.twitter.com/1.1/statuses/filter.json', {'stall_warning': True, 'include_ext_alt_text': True, 'track': 'mars rover'}) {'headers': {'accept-encoding': 'deflate, gzip'}, 'stream': True}

Please see the section labeled *Track* in the documentation at https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/guides/basic-stream-parameters for the semantics of the filter stream phrases. 

> A comma-separated list of phrases which will be used to determine what Tweets will be delivered on the stream. A phrase may be one or more terms separated by spaces, and a phrase will match if all of the terms in the phrase are present in the Tweet, regardless of order and ignoring case. By this model, you can think of commas as logical ORs, while spaces are equivalent to logical ANDs (e.g. ‘the twitter’ is the AND twitter, and ‘the,twitter’ is the OR twitter).

**Comment by jeffcsauer** [comment]
Makes total sense! Thanks so much for answering and closing.
