### ISSUE TITLE
Sometimes hashtags are missing when using "twarc hydrate" in CSV format

### ISSUE THREAD

**Issue by lotsoaxolotls** [DocNow/twarc#351]
It seems that a twarc-hydrated file in CSV format (extended tweet_mode) populates the hashtags column inconsistently, as seen in the attached screen shot. I've circled in red the hashtags that should have appeared in the hashtags column.

![missing_hashtags](https://user-images.githubusercontent.com/31898424/96081073-82ee6480-0e86-11eb-8725-12484d688f9e.png)

**Comment by SamHames** [comment]
Ahhh, I think I know what that one is - I'm guessing those are retweets? For whatever reason even in extended format retweet objects are truncated at the top level leading to missing hashtags - to get the full hashtag information you have to inspect the embedded original tweet...

I might be able to put together a pull request - I don't think it's a big change.

**Comment by edsu** [comment]
Thanks for the report @lotsoaxolotls and for the diagnosis/fix @SamHames. v1.10.2 was just released which should fix this.

**Comment by lotsoaxolotls** [comment]
Thank you!
