### ISSUE TITLE
Can't get past authentication

### ISSUE THREAD

**Issue by glocalglocal** [DocNow/twarc#358]
Not sure if twitter authentication changed recently, but twitter gives me three things rather than four: an API key, an API secret key and a Bearer token. So, I can't configure twarc. 

When twarc asked me for my consumer key and consumer secret, I tried to enter my user ID and password hoping that twarc would somehow bypass the problem, but it complains with 'Error: invalid credentials' (option 1: 'generate access keys by visiting Twitter') and 'ValueError: invalid interpolation syntax in 'my_twitter_password' at position 7' (option 2: 'manually enter your access token and secret'). Is there something that needs updating or am I doing something wrong?

**Comment by edsu** [comment]
Did you try entering your API Key and API Secret Key, and then selecting 1?

**Comment by glocalglocal** [comment]
> Did you try entering your API Key and API Secret Key, and then selecting 1?

This did work. Many thanks.
