### ISSUE TITLE
Got "MissingKeys" error using app-only auth

### ISSUE THREAD

**Issue by JiA1996** [DocNow/twarc#362]
I was trying to use app-only auth to download big amount of tweets.
I set app_auth = true and I did not provide any access_token and access_token_secret.
And then I got MissingKeys error.

After reading the source code I assigned some arbitrary value to access_token and access_token_secret and everything works fine.
But app-only auth shoudn't require access_token and access_token_secret right?

**Comment by edsu** [comment]
Do you have the app keys set?

**Comment by JiA1996** [comment]
> Do you have the app keys set?

I have both my consumer_key and consumer_secret set.

update: If I only provide consumer_key and consumer_secret to the twarc, it works on my computer running python 3.8.
However I still get key error on linux running python 2.x.
I'm not sure if it is my problem or not.

**Comment by edsu** [comment]
Are you testing with Python 2 and 3 on the same computer?

**Comment by JiA1996** [comment]
> Are you testing with Python 2 and 3 on the same computer?

Python 3 on my computer and Python 2 on remote linux server

**Comment by edsu** [comment]
Is the same version of twarc installed on both?

```
twarc version
```

**Comment by JiA1996** [comment]
yes

**Comment by edsu** [comment]
Can you send me the contents of your twarc.log from your server environment?

**Comment by igorbrigadir** [comment]
Python 2 is no longer supported, going to close this old one - if it's still a problem, feel free to reopen!
