### ISSUE TITLE
Does twarc support collecting all tweets from one user?

### ISSUE THREAD

**Issue by axhiao** [DocNow/twarc#363]
Does twarc support collecting all tweets from one user? Or this is limited by twitter API?

**Comment by edsu** [comment]
Yes:

    twarc timeline jack

But unless you are collecting the tweets of the user you have authenticated as you will be limited to the 3200 tweets by the API.

**Comment by edsu** [comment]
Yes if you have archive access you can collect the tweets from the search API instead:

```
twarc timeline --use-search jack
```

**Comment by miguelwon** [comment]
Ok, I see. And is it possible to add that parameter when using the library? I was just trying but without success.
Thanks
