### ISSUE TITLE
Capitalization inconsistency in English readme. 

### ISSUE THREAD

**Issue by rongpenl** [DocNow/twarc#369]
For example,

**Twarc** will handle
Twitter API's [rate limits](https://dev.twitter.com/rest/public/rate-limiting)
for you. In addition to letting you collect tweets Twarc can also help you
collect users, trends and hydrate tweet ids.

**twarc** was developed as part of the [Documenting the Now](http://www.docnow.io)
project which was funded by the [Mellon Foundation](https://mellon.org/).

**Comment by edsu** [comment]
Yes, I tend to prefer `twarc`. I can take a pass at fixing that.
