### ISSUE TITLE
click

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#378]
The twarc command line has gotten quite muddled as it has accreted options and functionality. The [click](https://click.palletsprojects.com/en/7.x/) module should not only provide some modularity for cleaning it up, while also providing an extension mechanism for twarc plugins using pclick-plugins](https://pypi.org/project/click-plugins/) for processing collected Twitter data. This ticket is to replace the current twarc/command.py module with one that uses click while keeping the command line interface the same.

**Comment by SamHames** [comment]
We can probably close this one now?
