### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rongpenl** [DocNow/twarc#381]
It would be nice to have some accessible documentation for twarc that is separate from the GitHub view of the README.md. Since twarc's README is available in multiple languages it would be good to see what support there is for translations.

Options include (at least) the following:

1. readthedoc. Example: [requests](https://requests.readthedocs.io/en/master/).
2. GitHub project page. Example: [square](https://square.github.io), source [code](https://github.com/square/square.github.io).

**Comment by jeffcsauer** [comment]
Thanks for opening this, @rongpenl! 

I'm going to spend some time looking into Github pages. 

Additional thoughts:
- Multi-language support is available in both [readthedocs](https://docs.readthedocs.io/en/stable/guides/manage-translations.html) and GitHub pages (in [various flavors](https://github.com/kurtsson/jekyll-multiple-languages-plugin))
- If we went with Github pages we would need a separate, dedicated repo?
- [Feature comparison readthedoc and Github pages](https://github.com/pmd/pmd/issues/405)

I will be attending the meetings but have limited time to contribute code until mid-March. Will keep looking into it!

**Comment by danielverd** [comment]
Hopefully that's outdated because those Github Pages example are pretty janky.

[Here's](https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/) a potential upside to using github pages. We can use a docs folder off the main repo to host the page. As opposed to readthedocs, which I couldn't exactly figure out by skimming the landing page you posted.

**Comment by edsu** [comment]
I'm leaning towards giving readthedocs a try just to see what things look like there. Unfortunately it looks like someone has already claimed the twarc namespace with a fork of the docnow/twarc repository that is now 3 years old:

https://readthedocs.org/projects/twarc/

I wonder @py3in might be able to help us here? I tried to find an email address to get in touch or a twitter handle and I came up empty handed. But maybe pinging @py3in on here will send an little update their way?

**Comment by edsu** [comment]
After asking and not getting a response in #readthedocs IRC I just submitted a support request at https://readthedocs.org/support/ I'll keep this ticket updated with anything I hear back.

**Comment by edsu** [comment]
I did hear back from RTD support:

> We have a policy for abandoned projects that you can read at https://docs.readthedocs.io/en/stable/abandoned-projects.html
> 
> I can start this process now if you confirm. Take into account that it could take up to 6 weeks if the user does not respond. Let me know.

I responded that it would be great to start the process. I can always experiment with a temporary namespace until we hear back.

**Comment by jeffcsauer** [comment]
Sounds good! Thanks for filling and following up on the report. I will start looking into readthedocs structure and setup. Planning to attend next v2 meeting.

**Comment by edsu** [comment]
I've got an initial version of the documentation that I'm pretty happy with. It uses readthedocs with [mkdocs](https://www.mkdocs.org/) which I found to be nice and simple for markdown, and also has a little ecosystem of plugins like [mkdocs-click](https://github.com/DataDog/mkdocs-click) which generates a page of documentation for our twarc2 command line interface.

**Comment by edsu** [comment]
Here's a first cut at what the results looks like, which is currently being generated from the [docs](https://github.com/docnow/twarc/tree/v2) branch:

https://twarc-project.readthedocs.io/en/latest/

**Comment by jeffcsauer** [comment]
This is looking awesome! Thanks for getting it up and running!

**Comment by edsu** [comment]
Thanks, I was pleasantly surprised at how it came together...especially the translated README docs.

**Comment by edsu** [comment]
I think if the twarc readthedocs namespace issue ever gets resolved I can delete the twarc-project one and reconfigure twarc. But for now I think we can let the docs live at https://twarc-project.readthedocs.io without causing too much difficulty?

**Comment by edsu** [comment]
We will want to continue adjusting & improving the docs going forward, but I think we can call this done for now.
