### ISSUE TITLE
Barebones prototype of the twarc2 client

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#382]
Just to get the ball rolling on the parts that talk to the V2 API.

We'll flesh this out a bit more as we start making progress.

**Comment by edsu** [comment]
I've recreated the v2 branch as a clean branch off of main instead of the previous branch that had some things removed.

**Comment by edsu** [comment]
I think we can call this done for now since the barebones client is there?

**Comment by SamHames** [comment]
Agreed - I'll close this, when I get a minute I'll make tickets for the other endpoints likely to be of interest.
