### ISSUE TITLE
webarchives.py

### ISSUE THREAD

**Issue by ameliameyer** [DocNow/twarc#384]
I'm not sure why this issue is coming up, but when I run webarchives.py, I get this error: 

NameError: name 'done' is not defined

But it's clearly defined in the code?

**Comment by edsu** [comment]
Ah yes. The trouble is it only is defined if the line contains a web archive. I've just pushed up a slightly modified version that should fix this problem?

**Comment by edsu** [comment]
Please reopen if you are still having trouble with it!
