### ISSUE TITLE
Twitter Academic Research Updates

### ISSUE THREAD

**Issue by cgb37** [DocNow/twarc#385]
Do you have plans to update the Twarc library because of the changes/updates to the Twitter Academic Research Updates? https://developer.twitter.com/en/solutions/academic-research

**Comment by igorbrigadir** [comment]
Yep! The new Academic Access is based on v2 of the API, and that's being worked on: https://github.com/DocNow/twarc/wiki/twarc2

**Comment by edsu** [comment]
Subscribe to #372 for updates.
