### ISSUE TITLE
Python 3.9.1 and TWARC

### ISSUE THREAD

**Issue by shamreeza** [DocNow/twarc#386]
Hi,
I am interested to learn TWARC with zero background knowledge. I have downloaded recent version of python to learn from TWARC tutorial but cannot figure out the problem. Please see attached screenshot and advice what I need to do? Should I download python 3.8 if 3.9 is unable to find PIP? Thanks

**Comment by shamreeza** [comment]
![Screen Shot 2021-02-19 at 9 12 20 am](https://user-images.githubusercontent.com/74222100/108444552-9717f780-72a6-11eb-9f82-6b9819451313.png)

**Comment by edsu** [comment]
Do you have pip3?

    pip3 install twarc

**Comment by shamreeza** [comment]
Thank you very much.
