### ISSUE TITLE
Partially OT: what's the license of twarc output?

### ISSUE THREAD

**Issue by aborruso** [DocNow/twarc#389]
Hi all,
imagine I have a script that use that run twarc everyday to accumulate some twitter search.

What's the twarc output, the free twitter data API output, license? Can I apply to the output a CC-BY 4.0 license?
Or is this data with a closed license?

Thank you

**Comment by edsu** [comment]
When using twarc you need to get keys from Twitter. When you get your keys you agree to the [developer's terms of service](https://developer.twitter.com/en/developer-terms/agreement-and-policy). You will want to look at that to determine what you choose to do. To apply a CC-BY license you need to own copyright, and I'm not a lawyer, but I don't think you have copyright on those collected tweets. As a project we have only ever distributed tweet identifiers, not the raw JSON data. We have made the metadata for those files available with CC licenses, but that's not the tweets themselves. I hope this helps.
