### ISSUE TITLE
Inject metadata about when a tweet was retrieved 

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#390]
One thing that isn't present in Twitter API responses is any information about *when* the tweet was retrieved/the call was made. This is important metadata, and critical to some use cases (for example, if you're looking at engagement metrics, there's a big difference between a tweet collected one minute after compare to one day after). This information is currently stored in the collection log, but that isn't super friendly because any programmatic use requires parsing the log

I propose we inject an ISO8601 string representing the time the call was made into either the existing `meta` dictionary of some API responses, or (maybe less likely to collide), a top level key like `collection_meta`, or `_twarc`. This avoids needing to manage a sidechannel of information such as through the log file, and also stores the data exactly where it's needed for processing.

**Comment by edsu** [comment]
I agree it is super important context. It feels like a bit of a departure from our design principles, but maybe a __datetime key could be used?

**Comment by SamHames** [comment]
Yeah, agree that it's not completely consistent - though I would argue that injecting metadata is less invasive than rearranging the responses for the flattening operation. 

Another piece of information that might be useful in the same context is how, or which endpoint and params were used to retrieve the data, but that might be going too far down the rabbit hole.

**Comment by SamHames** [comment]
I like the double under idea - maybe ` __retrieved_at` at the top level to be slightly more descriptive?

**Comment by edsu** [comment]
I was going to say, it's a slippery slope, but I kinda like it. It almost starts to remind me of work that GWU was doing to write Twitter Data using the WARC format, which wraps the HTTP response in WARC Record which has metadata and is linked to an HTTP Request. That's definitely one end of the spectrum. I think they switched away from doing that because it made downstream processing more difficult. 

I like the idea of a top level property `__twarc` that is an object which contains whatever we deem relevant. Maybe with the version of twarc that was used?

**Comment by edsu** [comment]
This might be a good agenda item for next week's meeting too.

**Comment by betsybookwyrm** [comment]
I think minimal metadata is pretty useful. I like the `__twarc` object (or `__twarc_metadata`?) plan.

A time retrieved timestamp is essential.

I can't think of anything else right now that's necessary when looking back at the data later. If it didn't automatically filter out locked tweets anyway we'd need the authenticating twitter account in there too, but we don't.

**Comment by igorbrigadir** [comment]
> I like the __twarc object (or __twarc_metadata?) plan.

Yep, +1 for this way

```
{
...
original json
...
  "__twarc": {
      "retrieved_at": "1614682805158",
      "project": "label_or_tag_or_something",
      "user": "twitter_or_twarc_account"
      "future_metadata": "foobar",
    }
}
```

Millisecond timestamp just because - i'm open to alternatives. "user" is just a daydream for collaborative crawls or something.. just to give the idea of extra metadata.

**Comment by lwrubel** [comment]
Catching up on this, documenting the request also brought to mind the WARC approach we're using in SFM. We're still using that approach, but it does indeed introduce overhead. 

The WARC request records provide documentation of when the HTTP request was made, which API was called, the query parameters, auth info and more. But I think the info about which API called and when the WARC was created are the pieces of info we use the most and are most relevant to twarc. So, agreed it is helpful/necessary to know when the request was made, in case you want to only work with data captured in a certain timeframe or want the context of the metrics, as mentioned above.

**Comment by edsu** [comment]
Thanks for those details @lwrubel they are *very* helpful!

**Comment by betsybookwyrm** [comment]
Yes, which endpoint and the query string / whatever appropriate for the endpoint would be great for accountability and traceability.

**Comment by SamHames** [comment]
There's a very basic implementation on the V2 branch now, injecting a top level __twarc object like so:
```
{
  "url": "https://api.twitter.com/2/tweets/sample/stream",
  "retrieved_at": "2021-03-10T07:17:17+00:00"
}
```
The current design is a bit basic - if we want to include params and other things then we might need to refactor the logic a bit so it isn't spread everywhere. I think most of the endpoints not yet covered will use get_paginated, so they should just work.

**Comment by SamHames** [comment]
I'm going to close this, if anybody has some metadata they want to add we can open another ticket.
