### ISSUE TITLE
Twarc2 client support for additional V2 Endpoints

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#394]
The following endpoints are available in the standard track but are not yet supported:

- [x] User timeline (tweet)
- [x] Mention timeline (tweet)
- [x] Filtered stream (tweet)
- [x] Follows lookup (user)

The following endpoint is available in the academic track:
- [x] Full archive search (tweet)

These should all be implementable using the same patterns as what is currently implemented in the V2 client, with the exception of the filtered stream which will require a bit more thinking around the API.

There is some additional functionality available in the V2 API that I think is out of scope for twarc - things like managing hidden replies to a tweet and managing follows.

**Comment by edsu** [comment]
I agree on the things that are out of scope. Apart from needing to write to the API for filter management I think twarc should be read only. People can use tweepy for these types of operations.

**Comment by edsu** [comment]
I ended up addressing the stream and archive search. But I'll leave this open for the other endpoints if we want to address them.

**Comment by SamHames** [comment]
They shouldn't take too long to add, the ones that are left are all paginated so shouldn't be too complicated, I can probably do them as a batch when I get a minute.

**Comment by SamHames** [comment]
Just pushed the last of the endpoints on that list.
