### ISSUE TITLE
Add V2 support for user context authentication

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#395]
This is also a good time to explore how to handle the different auth contexts in the V2 API.

**Comment by igorbrigadir** [comment]
Yeah, i haven't got a good way to do this yet but i was thinking it should definitely use both the App only and User context for some endpoints to take advantage of the extra rate limits that offers. I was hoping i could mess with this wrapper function only https://github.com/DocNow/twarc/blob/main/twarc/decorators.py#L12 to make it aware of each endpoint that's available and if it can fall back on App only auth for extra calls. Still thinking / haven't implemented anything yet.

**Comment by edsu** [comment]
At the moment twarc2 is configured just with the bearer_token. But this can be adjusted when we start to need to authenticate as a user.

**Comment by edsu** [comment]
With the restrictive app wide quotas I'm not sure that it is that urgent to rapidly search for tweets by cycling through app/user authentication. It ought to be pretty easy to max out the 500k limit within the 7 day window for recent tweets, and Academic Search users who have the ability to search the whole archive won't be in a huge rush to collect?

But hydrating tweets and users I think the quotas are quite different for users, and I could see wanting to be able to do that faster mostly as a convenience when working with large amounts of ids. 

Here is a list of endpoints that support user authentication. I've struck out ones that I don't think are in scope for twarc2 (but I'm happy to unstrike them if you think there's a use case).

* [GET /2/tweets/search/recent](https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent)
* [GET /2/users/:id/mentions](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets)
* [GET /2/tweets](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets)
* ~~[GET /2/tweets/:id](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id)~~
* ~~[DELETE /2/users/:source_user_id/following/:target_user_id](https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/delete-users-source_id-following)~~
* [GET /2/users/:id/followers](https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/get-users-id-followers)
* [GET /2/users/:id/following](https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/get-users-id-following)
* ~~[POST /2/users/:source_user_id/following](https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/get-users-id-following)~~
* ~~[GET /2/users](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users)~~
* [GET /2/users/:id](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-id)
* [GET /2/users/by](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-by)
* ~~[GET /2/users/by/username/:username](https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-by-username-username)~~

**Comment by igorbrigadir** [comment]
That's a good point - yes. Thanks for highlighting the most relevant endpoints!

A separate reason for wanting user context auth is being able to crawl data from private accounts (if the authenticating user has access to a locked account, it can request tweets from the locked account in v1.1 and i'm pretty sure this is the same for v2 as far as i can tell, but i'll double check that)

**Comment by edsu** [comment]
I've added support to Twarc2 for user authentication. The constructor no longer takes a `bearer_token` as it is created with the `consumer_key/secret`. Internally both user and app auth clients are created for use by the relevant endpoints--although at the moment only the app auth client is being used.

**Comment by edsu** [comment]
I'm going to break out the endpoints that should be implemented into separate tickets if that's ok.

**Comment by SamHames** [comment]
I'm not super keen on the ergonomics for this one. I think it adds complexity to the client that is better covered by the layers above it. 

I also think it's a step back not to use the bearer_token for application authentication, as the Twitter developer console and examples heavily emphasise this approach, and I think it adds a burden to new users if we take the less beaten path. Not saying we shouldn't have the option, or that's it's a lot of extra work for users, but one secret is always going to be easier to deal with than 4 different secrets.

That being said I can work through some options for how to configure this, as there are some benefits to always having both around.

**Comment by igorbrigadir** [comment]
Yeah, the idea to use both Bearer Auth and User Auth is to take advantage of the higher rate limits on some endpoints, but not to force people to use a particular way to authenticate. I really like how it's handled here: https://github.com/sns-sdks/python-twitter/blob/master/pytwitter/rate_limit.py

I agree about ergonomics - ideally, you should be able to specify either: Bearer token only, or Consumer Key & Secret (twarc generates a bearer for you), or Consumer key & Secret, and Access Token & Secret (and twarc generates bearer token and user auth for you). As an end user, i prefer having `.env` file i can specify this in, not command line switches but that's just my personal preference.

**Comment by edsu** [comment]
@SamHames whose usability are you thinking about here? The command line user or the library user? For the command line I think the twarc1 behavior will be preserved, which seems good to me. For the library user we could, as @igorbrigadir says, make the the consumer/access key pairs optional if a bearer token is supplied? That would mean the client would be unable to issue user auth API requests.

I'm open to ideas and PRs on how to improve it.

**Comment by edsu** [comment]
And finally, I like .env files too. When using pipenv .env variables are put into your environment automatically where twarc will pick them up. For people working outside of pipenv environments we could add python-dotenv as a dependency and load it?

**Comment by SamHames** [comment]
I just pushed the logic for this:
- the client now chooses between app auth and user auth based on what keys are passed in, supporting both bearer tokens and the Oauth related features
- there's a simple toggle flag --app-auth/--user-auth in the CLI to switch between the two, with app auth the default.

There's still a couple of rough edges in the CLI that I will raise separate tickets for.
