### ISSUE TITLE
Move flattening out of Twarc2 client

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#398]
I think there was general consensus that the client should work with the raw data from the API and not perform the flattening operations itself. The command line can, if asked, flatten data.

**Comment by igorbrigadir** [comment]
In that case, maybe the flattening can be a bit smarter and try to load *all* the expansions across requests - so that if an expansion exists in one "page", it can also be included to expand a tweet on a previous or subsequent page?

**Comment by edsu** [comment]
I'm not sure I understand fuly @igorbrigadir but take a look at the latest code with flattening pulled out into a separate command line option for sample, and also as a separate subcommand:

    twarc2 sample --flatten > tweets.jsonl

or:

    twarc2 sample > tweets.jsonl
    twarc2 flatten tweets.jsonl > tweets-flattened.jsonl

I actually was wondering if flattening at the command line should result in line oriented json, which simplifies some downstream processing I think?

Of course feel free to add new tickets that capture what you think needs to be done, but I'm going to close this for now.
