### ISSUE TITLE
Configuration options for the CLI using the V2 API

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#400]
So currently if you use the `twarc` CLI entrypoint, it will read from the .twarc configuration file and "automagically" set things up for you. On the other hand if you want to use the `twarc2` entrypoint you need to explicitly pass in the authentication information. For an initial pass this is fine, but I certainly don't want to be schlepping tokens around forever.

Key questions:
- Can we reuse (at least parts of) the existing configuration functionality, including the .twarc configuration file? Or would it be safer and less confusing to migrate to something else given the next point?
- How do we test and handle failures? For example, existing credentials will work for V1.1 but not V2, perhaps leading to some surprising failures if someone is already using twarc, or commands that work on V1.1 failing on V2.
- Architecturally, where do we want this functionality to live?

Suggestions:
- For the third point at least, I'd suggest we have the configuration as a function, rather than directly coupled to the client object. This is more explicit about which credentials are being used, and leads to fewer surprises when using twarc as a library. For the CLI I would hope this can work similar to now.

``` python
import twarc

credentials = twarc.load_configuration(profile='test_credential')
client = twarc.Twarc2(**credentials)
```

**Comment by edsu** [comment]
That is a good point about them needing to be separste because of different permissions. Maybe we could move to a .twarc2 yaml file? I do like the idea of storing consumer key/secret and generating a bearer token as needed. Or can you only have one bearer token active per app at one time? If you are feeling inspired give something a try and we can see if it works?

**Comment by SamHames** [comment]
I'll have a look at some point next week. `.twarc2` sounds like a good idea to me, hopefully less cross API version issues.

According to the documentation, https://developer.twitter.com/en/docs/authentication/api-reference/token :

> Only one bearer token may exist outstanding for an application, and repeated requests to this method will yield the same already-existent token until it has been invalidated.

So for application authentication it seems like it would be simpler to just keep the bearer token around?

**Comment by edsu** [comment]
I'm going to take a look at [click-config-file](https://pypi.org/project/click-config-file/) to see if it might be helpful here since we really only need the config for the command line?

**Comment by edsu** [comment]
I took a pass at just persisting the bearer_token for now using click-config-file. Give it a try and let me know what you think!
