### ISSUE TITLE
At what point do we make the first release including V2 functionality?

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#401]
We currently have:

- A basic client for the V2 API supporting some endpoints.
- CLI support for the same

What minimum other functionality do we need to consider a release?

**Comment by edsu** [comment]
I was thinking the same thing. I've almost got the stream operations working. Maybe archive search would be good too?

**Comment by SamHames** [comment]
Now that I think about it: we definitely need more documentation before a release. At the very least something in the readme giving examples for the new functionality (even if that's only temporary).

**Comment by edsu** [comment]
I agree. Let's make addressing #381 a dependency for an initial release?

**Comment by edsu** [comment]
Other than #381 I think after some cli testting amongst ourselves we could try a new release soon? I really like how the old twarc functionality is still there -- that was an awesome idea @SamHames.

**Comment by edsu** [comment]
Now that we've verified things work on Windows and we have some documentation are we ready to merge v2 into main for a release?

**Comment by igorbrigadir** [comment]
I think so yes, the docs will be easier to append and update as people start using it.

**Comment by SamHames** [comment]
I'm hoping to get one last little thing around the sqlite/data processing in: but if I can't get that going by early next week then release sounds great.

**Comment by edsu** [comment]
v2 has been merged with main! release imminent.
