### ISSUE TITLE
Quota

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#402]
It would be nice to be able to check your quota from the command line:

      $ twarc2 quota
      123,453 out of 500,000 / month

**Comment by igorbrigadir** [comment]
It's possible to scrape this from the Dashboard https://developer.twitter.com/en/portal/dashboard but not sure how easy or hacky it will be - need the Browser cookie to authenticate: https://developer.twitter.com/api/accounts/[id]/usage?interval=past returns a json

**Comment by edsu** [comment]
Yeah, I wonder if we can fetch one tweet and see if there is any indication in the headers about how many requests are remaining? I suspect not, but maybe?

**Comment by igorbrigadir** [comment]
I looked and unfortunately no, there's nothing about that monthly limit anywhere in normal requests.

**Comment by edsu** [comment]
Bummer. Well I've added --limit options to `search` and `stream` so hopefully those will help people manage their quotas.
