### ISSUE TITLE
Thread

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#404]
I think it would be useful to have a command like this:

    twarc2 thread {tweet-url | tweet_id}

This would fetch a tweet thread by first looking up the conversation-id for a tweet and then issuing the appropriate search . An optional `--archive` parameter could indicate whether to use the Academic Search endpoint.

**Comment by igorbrigadir** [comment]
> optional --archive parameter could indicate whether to use the Academic Search endpoint.

Definitely leave this in but currently `conversation_id:` is not supported in the full archive academic search https://twittercommunity.com/t/unable-to-scrape-filtered-stream-using-conversation-id/146971/2?u=igorbrigadir (limited to last 7 days)

**Comment by edsu** [comment]
Dangit, I was hoping that an archive search for conversation_id:1026872652290379776 would work. But your right, it doesn't. This is a curious constraint, since it seems to be more about how they have implemented it rather than a business decision.

**Comment by edsu** [comment]
@igorbrigadir is the conversation_id just the tweet_id of the head of the thread?

**Comment by igorbrigadir** [comment]
> conversation_id just the tweet_id of the head of the thread?

Yes, and even replies to a reply get the original head tweet as the `conversation_id`

**Comment by edsu** [comment]
Got it, so there's no need to "look up" the conversation id. This makes me think of other handy search aliases that might be useful for twarc2 to have. Are there any others that come to mind?

**Comment by igorbrigadir** [comment]
Actually, i got that wrong, according to someone else the `conversation_id` parameter works: https://twittercommunity.com/t/embedded-conversation-conversation-id-tweet-id/150802/4?u=igorbrigadir

**Comment by edsu** [comment]
Hmm, I don't know if that person is mistaken or has elevated privileges? With Academic Search I can search for historical tweets like @jack's:

```
$ twarc2 search --flatten --archive --start-time 2006-03-21 --end-time 2006-03-24 from:jack  | jq '.created_at + " " + .text'

"2006-03-23T23:08:50.000Z wondering why noah didn't bring his stomach to lunch"
"2006-03-23T18:48:54.000Z overheard in South Park: \"Dogs don't belong in cages. Maybe kids do.\""
"2006-03-23T17:44:51.000Z changing my status again for florian"
"2006-03-23T17:38:08.000Z the ants make me think of Florian. i'm not sure why. everything: florian."
"2006-03-23T16:58:02.000Z at work.  with the ants."
"2006-03-23T16:01:36.000Z f train (boston train) to work"
"2006-03-23T01:22:42.000Z off to yoga. no love from simplewire"
"2006-03-23T00:38:04.000Z wondering when Mer is going to show up"
"2006-03-22T02:16:23.000Z drawing naked people"
"2006-03-22T01:07:11.000Z on my way to drawing class"
"2006-03-21T20:50:14.000Z just setting up my twttr"
```

But `conversation_id` doesn't seem to work with the historical search, e.g. this one [822446982648201216](https://twitter.com/POTUS44/status/822446982648201216):

```
$ twarc2 search --flatten conversation_id:822446982648201216
```
Nada

**Comment by SamHames** [comment]
I'm a big fan of the CLI exposing functionality like this. Even if it's 'just' a wrapper around specific search syntax, I think it's super useful for discoverability and a good vehicle for documentation.

**Comment by edsu** [comment]
I went with *conversation* instead of *thread* because that's what Twitter calls them, and that's the id name that is used.

**Comment by sabrina981** [comment]
Where is my money at joe snow llc tow truck from the Apache owner of GitHub is very disappointed in his servers, seems to be a virus amongusoutXx he has sent me to conduct investigation on charges of harassment bullying fraud bill payment code for tracking. Do you know children are the future of the world! Peace love harmony
