### ISSUE TITLE
Handle InvalidAuthError raised from the client in the CLI

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#406]
Currently, if you do the following:

`twarc2 --user-auth sample'

You will get an exception traceback ending in:

`twarc.decorators.InvalidAuthType: This endpoint only works with application authentication`

This is the correct behaviour because the stream endpoints only work in app auth mode, but we can probably catch and handle that specific error more nicely in the CLI. It would be especially nice if click had a way to setup general purpose error handling, that way we only have to worry about raising the right thing in the client rather than special cases in the CLI.

**Comment by edsu** [comment]
I don't know if it helps but I did add a decorator (as a class) for handling command line errors in [docrators](https://github.com/DocNow/twarc/blob/v2/twarc/decorators.py#L154-L176). Could that be adapted to do what you are talking about?

**Comment by SamHames** [comment]
Ah, I missed that one -  I will take a closer look.

**Comment by SamHames** [comment]
Yep, does exactly what I needed, thanks! Already done this one.
