### ISSUE TITLE
Twarc2 on Windows

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc#407]
Currently taking notes on running twarc2 on Windows, for #381

This issue is just for keeping track of the small issues that need attention in either docs or bugs in code.

Feel free to add your own if you've tried running twarc2 on Windows!

**Comment by igorbrigadir** [comment]
Depending on how you installed Python, you may have to manually add the `Scripts` folder to `PATH` for `twarc2` to work as a command line tool. 

If it's Python from the official installer, it will be something like `C:\Users\<user>\AppData\Local\Programs\Python\Python39\Scripts` or if you used Windows App store: `C:\Users\<user>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts`

**Comment by igorbrigadir** [comment]
It will work in either Command Prompt or PowerShell, but both of these fail to display the emoji characters from the CLI. It works with the emoji in Windows Terminal Preview https://www.microsoft.com/en-us/p/windows-terminal-preview/9n8g5rfz9xk3?activetab=pivot:overviewtab

**Comment by igorbrigadir** [comment]
The `--limit` command does not limit anything to less than 100 (the default number of results per request). This is also only working for multiples of 100 for the same reason. Not sure if it's something worth changing, so you can request <100 tweets or just add a note to say that it's "Multiples of 100".

**Comment by igorbrigadir** [comment]
A separate issue with `__twarc` metadata not being included, fix in #408

**Comment by igorbrigadir** [comment]
Another separate fix for `flatten` command 24332199f3abb7330321f1218fb2834734436d63

**Comment by igorbrigadir** [comment]
All the notes are in https://github.com/DocNow/twarc/wiki/twarc2-on-Windows-10

**Comment by igorbrigadir** [comment]
It seems to work perfectly fine on windows, with the exception of setting up your PATH variable depending on how you installed python. I think it's enough to document these and we don't need any code changes to make it work on Windows.

**Comment by edsu** [comment]
Thanks for all this work @igorbrigadir much appreciated! Did the ermoji not display or did they display with noisy errors?

**Comment by igorbrigadir** [comment]
With default fonts and settings they displayed as ☒ the box thing, but they work if you mess with the appearance in PowerShell or command prompt.

**Comment by edsu** [comment]
Is it worth figuring out a way to turn off the icons on windows or consider turning them off completely?

**Comment by igorbrigadir** [comment]
Yeah - I don't have a strong opinion on that - my solution was just to mention:

> twarc2 CLI works best through [Windows Terminal Preview](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n8g5rfz9xk3?activetab=pivot:overviewtab)

and leave it at that.
