### ISSUE TITLE
Document Common V2 usecase: Crawl archive tweets, flatten, export to CSV

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc#411]
Add instructions and update https://github.com/DocNow/twarc/blob/main/utils/json2csv.py or add a new one that does a commonly required operation: Crawl some tweets, process the expansions, and export a CSV for further data analysis in another tool.

**Comment by edsu** [comment]
I was wondering if we might want to encourage users to collect the JSON data and then convert with twarc2?

    twarc search auspol > tweets.jsonl
    twarc csv tweets.jsonl > tweets.csv

Were you thinking along the same lines?

**Comment by edsu** [comment]
I'd also love to see this example as part of the documentation. Maybe that's what you had in mind @igorbrigadir ?

**Comment by igorbrigadir** [comment]
Yes - that's exactly the "pipeline" i want to document a bit better. This use case has come up a few times now from different people on the Twitter dev forums.

Currently, a rough idea is to have this:

```
twarc2 search auspol > tweets.jsonl # saves original responses with all the expansions by default
twarc2 csv tweets.jsonl > tweets.csv # flattens everything by default, and or selects a subset of useful features
```

The selecting useful features part is somewhat related to #379 

There's also a separate useful thing to try:

Flatten everything from *multiple* requests, so if 1 "page" has place ids or users that may enrich another request it can do that. 

This usually affects the referenced tweets as opposed to the tweets in data, since all the data tweets should already have all the relevant includes. 

This is a rough snippet that does the above:

```
import json
import expansions  # copy expansions.py
from jsonmerge import Merger # pip install jsonmerge

schema = {
    "properties": {
        "data": {"mergeStrategy": "append"},
        "expansions": {"mergeStrategy": "append"},
    }
}

merger = Merger(schema)

dataset = {}

with open("one_result_per_line.jsonl", "r") as f:
    for line in f.readlines():
        dataset = merger.merge(dataset, json.loads(line))

dataset = expansions.flatten(dataset)

with open("expanded.json", "w") as f:
    f.write(json.dumps(dataset))
```

It's not very memory efficient, since it load everything in all at once, but it does the job.

What i haven't tried yet is to see just how beneficial it is - is it even worth using includes from one request, to expand tweets in a different request? If it's just a couple of users or places or something else it may not be worth doing it this way, or just leaving a separate script in utils that does this is enough.

**Comment by edsu** [comment]
Just an aside: I wrote a doc page about plugins if you decide to go that route.

https://twarc-project.readthedocs.io/en/latest/plugins/

**Comment by igorbrigadir** [comment]
Yeah - that's a good idea - i might try making this a plugin instead!

**Comment by edsu** [comment]
@igorbrigadir I'm a bit confused about why merging data across requests is needed. Shouldn't each request be self contained and have everything it needs for flattening to work completely? What am I missing here?

**Comment by edsu** [comment]
Also, I'm not opposed to continue to have canonical CSV functionality as part of the core module. I think you're right it's probably the first thing anyone wants to do with the data, especially for use in a spreadsheet or Data Frame. But I guess one could imagine different types of CSV, but maybe those could done as modules?

**Comment by SamHames** [comment]
One of the reasons we're proposing SQLite as an intermediary before CSV and other operations is to solve the problems of people needing slightly different things: it's a more friendly baseline for data processing and formatting then a stream of tweets, and means you can solve problems like deduplication and entity expansion once on ingest, rather than every single time you need to do something with the tweets.

I'd also support this being a core plugin as well: we know people need this, and also it would be good to have a fully fleshed out example plugin within twarc itself for people to refer to in addition to the documentation.

**Comment by igorbrigadir** [comment]
> @igorbrigadir I'm a bit confused about why merging data across requests is needed. Shouldn't each request be self contained and have everything it needs for flattening to work completely? What am I missing here?

I'm still on the fence as to how useful this is but the rationale is:

Each request has all the `includes` relevant to the `data`. They are self contained. However, the tweets in `includes` (retweets, quoted tweets) can themselves have elements like places or polls or users that are not included for the result set. Merging different result pages together, we can extract slightly more data: What tends to happen is that more `places` are filled in referenced tweets, which is sometimes very useful.

**Comment by edsu** [comment]
I get it now. A view of data across responses does seem like perfect territory for a sqlite db.

**Comment by igorbrigadir** [comment]
Implementation for this is going to be in https://github.com/DocNow/twarc-csv

**Comment by igorbrigadir** [comment]
As far as documentation goes, i think linking to https://github.com/twitterdev/getting-started-with-the-twitter-api-v2-for-academic-research this would satisfy this issue. The tutorial series from twitter uses twarc as the python example.

**Comment by edsu** [comment]
Its too bad Twitters guide is do focused on writing code when some of the tasks could easily be solved with one command at the command line. Or did I miss those examoles?

**Comment by igorbrigadir** [comment]
Ah yes, you're right - we should still link that guide in the docs, but also give the command line versions. So gonna keep this issue open as a todo for the docs.
