### ISSUE TITLE
Blog post about v2

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#414]
I want to write a blog post about twarc v2 that highlights the work that has been done by people who have been attending the calls and contributing to the the project. I also want the post to briefly describe what is changing in v2 and include a little video demo of using twarc2 from the command line.

I'll share a URL for the draft in here for others to look at and suggest edits to so that I get people's affiliation and roles correct. Here's a rough outline:

## Intro

* Some kind of banner image?
* TLDR; (there's a new version of twarc to work with the v2 & academic search api! contributors names/institutions, jump forwards if you just want the details)
* Video of using twarc2 at the command line

## Twitter v2 API

* Twitter's announcement of v2 API and sunsetting of v1.1 (missing ability to Post in v2 api?!)
* Difference in the JSON representation of a tweet (more on this in a moment)
* Rate limits in v2 as compared to v1: a graph visualization?
* Benefits of v2 for Academic research
* A bit about the application process

## twarc v2

* Design philosophy
* Installing twarc2
* Running a search
* Collecting from the Stream
* The JSON data: expansions
* Flattening: for stream processing
* Plugins are the new utils: twarc-ids, twarc-videos
* Potential new areas of work twarc-sqlite, twarc-activitystreams

**Comment by SamHames** [comment]
Sounds look a good plan to me, especially good to have the design philosophy written down somewhere.

Have you thought about a publication in https://joss.theoj.org/ as well (maybe for a little further down the line?)

**Comment by edsu** [comment]
That's a great idea re: JOSS. Maybe we could treat this blog post as a first draft of something a bit more formal with us all as authors?

**Comment by edsu** [comment]
I noodled around in a [notebook](https://github.com/edsu/notebooks/blob/master/Twitter%20API%20Quotas.ipynb) to create a visual comparison of the number of tweets that can be collected over a month from the v1 and v2 search/stream APIs. 

![app-search](https://user-images.githubusercontent.com/33829/112707270-81d35180-8e80-11eb-8e18-60e6311072e5.png)
![user-search](https://user-images.githubusercontent.com/33829/112707272-81d35180-8e80-11eb-9d67-5c0dfe79be29.png)
![stream](https://user-images.githubusercontent.com/33829/112707271-81d35180-8e80-11eb-890a-c20e3dde1e76.png)

**Comment by csantanaes** [comment]
very good!

**Comment by igorbrigadir** [comment]
A thought that occurred to me: The twarc data gathering philosophy and Twitter API philosophy are somewhat at odds. Twitter's approach is to give you an API to gather the minimally required data, suitable for use in production for example. Twarc defaults to gathering Everything by default, which reminds me of issues raised in this previous article https://gwu-libraries.github.io/sfm-ui/posts/2017-05-18-twitter-policy-change that platforms and researchers are always going to be somewhat at odds.

**Comment by edsu** [comment]
Thanks for that @igorbrigadir I tihnk you are right to point out this inherent tension. Lets see how we can work it in to the text. I should have an initial draft in the next couple days.

**Comment by jeffcsauer** [comment]
Can't speak for everyone but I really appreciate that the current twarc setup provides everything and allows me to curate what is needed. Recently tried out a variety of gathering software with the Academic API - rtweet, tweetr, tweepy, the official search-tweets-python - and twarc was by the far the easiest to actually implement in a workflow. Totally agree that this 'tension' is quite evident and would be worth recognizing 👍

**Comment by edsu** [comment]
The working draft is here: https://medium.com/@edsu/twarc2-779278e66ea0

Unfortunately I don't think Medium allows editing, but you can leave comments which I can address. Also I'm happy for you to leave feedback here if you prefer.

I'm still putting together a short video to include, and would welcome ideas for a header image.
