### ISSUE TITLE
can only hydrate less than 1% tweets from tweetIDs 

### ISSUE THREAD

**Issue by yuki-yue** [DocNow/twarc#417]
![error](https://user-images.githubusercontent.com/68763881/112848584-d1ad5500-90da-11eb-9de2-1d6acdc3f9b1.JPG)
The image attatched shows the problem i encounter when hydrating tweets from tweetIDs of September 2020.It's really strange that line 127 shows the hydrating process for 2020-09-05 is not finished because it only gets 120 tweets (It should get 125640 tweets in all). The  hydrating process for 2020-09-05 just stopped and turned to hydrate for 2020-09-10. The same error occurs. I can't figure out the reason of this. Everything worked fine few weeks ago when hydtrating tweets from March to July.

**Comment by igorbrigadir** [comment]
Same as #418, following there.
