### ISSUE TITLE
Error: can only hydrate less than 1% tweets from TweetIDs

### ISSUE THREAD

**Issue by yuki-yue** [DocNow/twarc#418]
The image attatched shows the problem i encounter when hydrating tweets from tweetIDs of September 2020.It's really strange that line 127 shows the hydrating process for 2020-09-05 is not finished because it only gets 120 tweets (It should get 125640 tweets in all). The  hydrating process for 2020-09-05 just stopped and turned to hydrate for 2020-09-10. The same error occurs. I can't figure out the reason of this. Everything worked fine few weeks ago when hydtrating tweets from March to July.
![error](https://user-images.githubusercontent.com/68763881/112850023-374e1100-90dc-11eb-9fe5-7da2966c06d8.JPG)

**Comment by yuki-yue** [comment]
Hope someone can help me with this. It's so confusing.

**Comment by SamHames** [comment]
I would start by double checking your source data is still good. I've seen
this before  when a program (such as Excel or a JavaScript library) mangles
the 64 bit tweet ids. If all your tweet ids end in 00 that's likely the
problem.

**Comment by igorbrigadir** [comment]
Separately to the issue with broken ids:

> The hydrating process for 2020-09-05 just stopped and turned to hydrate for 2020-09-10.

Are you executing multiple processes or how are you running this exactly?

Sometimes the issue is in the order of the filenames, and it will do them out of natural order because of how files are listed by some other tool (it's almost random with python's `glob`).

**Comment by yuki-yue** [comment]
I have found the reason.Something gets wrong when i download the tweetIDs file.
