### ISSUE TITLE
wall.py

### ISSUE THREAD

**Issue by ameliameyer** [DocNow/twarc#419]
Is there a way to customize the title output in command line i.e. without going into the code and physically altering what the title is?

**Comment by igorbrigadir** [comment]
Unfortunately no, the html is hard coded https://github.com/DocNow/twarc/blob/main/utils/wall.py so it will have to be changed in the script

**Comment by edsu** [comment]
I'd like to prioritize rewriting wall.py as the twarc-wall plugin.

**Comment by ameliameyer** [comment]
Sounds good. I've been working on a sort of guide to Twarc utilities for mostly non-technical users so I was hoping they wouldn't have to go into the file itself to change the title but since it's not customizable, I'll just have then edit it within the file. Thanks!

**Comment by igorbrigadir** [comment]
> I've been working on a sort of guide to Twarc utilities for mostly non-technical users

@ameliameyer this sounds great! If you think it would be useful for others, we should try and integrate it with the twarc Docs on https://twarc-project.readthedocs.io/

**Comment by ameliameyer** [comment]
> @ameliameyer this sounds great! If you think it would be useful for others, we should try and integrate it with the twarc Docs on https://twarc-project.readthedocs.io/

That would be great! It's still in the experimental phase as I'm working out all the kinks, but you can check out what's been done so far: https://ucsb-collaboratory.github.io/twarc/

**Comment by edsu** [comment]
Hey, nice! The more documentation the better, especially from particular areas of practice.

**Comment by igorbrigadir** [comment]
Going through closing some old issues: anything to do with `utils` is for the old v1.1 API and will stop working, so anything new should be for v2 as a plugin https://twarc-project.readthedocs.io/en/latest/plugins/
