### ISSUE TITLE
Client forbidden

### ISSUE THREAD

**Issue by toledobastos** [DocNow/twarc#430]
Hi guys,

I'm getting "Client forbidden" when querying the full-archive endpoint. Config files are properly set with bearer token. See below for the output:

twarc2 search blacklivesmatter --archive --start-time 2014-08-04 --end-time 2014-08-05 --limit 100 > test.json
⚡ Client Forbidden

Notice that the following query works as expected:

twarc2 search blacklivesmatter --start-time 2021-04-03 --end-time 2021-04-04 --limit 5 > tweets.test.1.jsonl

Also note that I've been using this account/bearer token with to query the full-archive endpoint since Twitter's announcement. It's been working fine on curl, but it doesn't seem to work with twarc.

Cheers,
Marco

**Comment by edsu** [comment]
@toledobastos thanks for the question! The first query works for me just fine, so I think something is wrong with your keys. Other people have confirmed historical search works for them with twarc2 as well. Troubleshooting keys in public on GitHub isn't advisable, but perhaps we could set up a zoom call to take a look?

**Comment by edsu** [comment]
Here's the output I *can* share though:

```
twarc2 search blacklivesmatter --archive --start-time 2014-08-04 --end-time 2014-08-05 --limit 100 --flatten | jq '.created_at + " " + .text'
"2014-08-04T23:36:18.000Z @Toni_Fields thanks so much for supporting RJAC! #blacklivesmatter #snapco"
"2014-08-04T21:12:47.000Z RT @RJActionCenter: RT @FIERCENYC: \"Ally is not an identity it's an action\" http://t.co/kaYaa6VA5G” #girlslikeus #mfom14  #blacklivesmatter…"
"2014-08-04T19:10:14.000Z Rise Up!\n\nWhat will it take? How many more people must die? ... \n\n____\n#streetintell #blacklivesmatter #reality... http://t.co/WNMLfe6WV9"
"2014-08-04T17:02:35.000Z RT @RJActionCenter: RT @FIERCENYC: \"Ally is not an identity it's an action\" http://t.co/kaYaa6VA5G” #girlslikeus #mfom14  #blacklivesmatter…"
"2014-08-04T16:45:18.000Z RT @RJActionCenter: RT @FIERCENYC: \"Ally is not an identity it's an action\" http://t.co/kaYaa6VA5G” #girlslikeus #mfom14  #blacklivesmatter…"
"2014-08-04T16:41:46.000Z RT @RJActionCenter: RT @FIERCENYC: \"Ally is not an identity it's an action\" http://t.co/kaYaa6VA5G” #girlslikeus #mfom14  #blacklivesmatter…"
"2014-08-04T16:30:58.000Z RT @RJActionCenter: RT @FIERCENYC: \"Ally is not an identity it's an action\" http://t.co/kaYaa6VA5G” #girlslikeus #mfom14  #blacklivesmatter…"
"2014-08-04T15:26:35.000Z #truth #createyourown #takeaction #tabislove #blacklivesmatter #blackisbeautiful #blackpanthers… http://t.co/eN8AtP8BE2"
```

**Comment by toledobastos** [comment]
Sorry. Didn’t mean to suggest we should post keys publicly on GitHub. I saw on the slack channel that that query is working fine for Jeff. I don’t think it’s the keys because they’re working fine with curl, but it seems clear the problem is with my twarc install. I’ll look into this during the weekend. Thanks for that!

-- 
Marco T. Bastos

**Comment by edsu** [comment]
Yeah, it's pretty weird that the bearer token works ok with curl but not twarc. Maybe there is a hint about what's going wrong in the `twarc.log`. Otherwise we could spend some time helping you debug next week? It would be great to get you up and running with twarc2. Thanks for taking the time to engage, this will make the experience better for others.

**Comment by toledobastos** [comment]
It’s weird alright, but I’ve seen weirder. It’s been my pleasure; twarc is a nifty little tool. Happy to talk next week. If I get a few hours to go over the logs I should figure out the problem.

**Comment by edsu** [comment]
I think this turned out to be a environmental problem and not related to twarc. If that's not the case please reopen!

**Comment by tperka** [comment]
Could you guys share the solution please? Got the same problem

**Comment by toledobastos** [comment]
Can't remember what the problem was. Maybe yet another issue with OpenSSL/TLS? Try running the query on a Linux machine. Off the top of my head, I'd guess it's some Windows DLL that got compiled with some ancient OpenSSL.

**Comment by tperka** [comment]
I'm running on Linux VM now and when I add `--archive` I get the error but when I omit that I can scrape (let's say, becuase then I'm getting an error `start date must be on or after 2022-03-01` wtf?)

**Comment by toledobastos** [comment]
Sounds familiar, but when I was troubleshooting this only Our Lorb and I knew what I was doing. Now only Our Lorb knows.

**Comment by igorbrigadir** [comment]
> when I add --archive I get the error

The issue is most likely with https://developer.twitter.com/en/portal/dashboard - you must be using a bearer token from an app attached to an `Academic` project, not `Elevated` or `Basic`. Elevated / basic gives you access to 7 day search, academic access is the full archive, and a different endpoint. `--archive` enables full archive search, but only for academic access https://twarc-project.readthedocs.io/en/latest/twitter-developer-access/ .  Hope that helps!
