### ISSUE TITLE
user geolocation

### ISSUE THREAD

**Issue by luisignaciomenendez** [DocNow/twarc#432]
Hello

I am currently trying to obtain the information of exact geolocation for a list of users ( 'geo.coordinates.coordinates'). I initially found this information by using the command:

`twarc2 flatten output.json output_flat.json`
`twarc2 csv output.json blm2_python.csv`

One error that I am getting is that a lot of the coordinates are exactly the same for a lot of users (I tried to build the same using an R command and this did not happen).

On a previous file that I built with a query. From this info, I am trying to use a similar procedure on a list of users `user.txt` as follows:

`twarc2 users --flatten user.txt >user2.json`

Here is where I am facing the issues, this does not give information on geolocation and neither can't be converted to a proper csv file but I have seen some studies using users to obtain geolocation so am I making an error somewhere?

Thanks a lot in advance!

**Comment by edsu** [comment]
I don't think [User objects](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/user) include geolocation in the v2 API. However tweets can have a place associated with them if you request the [geo field](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet) (twarc2 will automatically request this field). Note, these are not precise locations but are bounding boxes for places like Paris, France or Brooklyn, New York, USA.

I don't know if that helps you or not. If you have users and you want to get places associated with them you will need to look at their tweets I think?

**Comment by luisignaciomenendez** [comment]
> I don't think [User objects](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/user) include geolocation in the v2 API. However tweets can have a place associated with them if you request the [geo field](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet) (twarc2 will automatically request this field). Note, these are not precise locations but are bounding boxes for places like Paris, France or Brooklyn, New York, USA.
> 
> I don't know if that helps you or not. If you have users and you want to get places associated with them you will need to look at their tweets I think?

Right, sorry, what I want is to obtain the history of tweets for a user and tweets' geolocation. I thought the `twarc2 users` was given the history of tweets but maybe I am wrong. Do you now how to do this?

**Comment by edsu** [comment]
If you have a username or user_id and you would like their timeline you can:

    twarc2 jack > jack.jsonl

**Comment by edsu** [comment]
I think the addition of the [twarc-timelines](https://github.com/docnow/twarc-timelines) plugin helps solved @luisignaciomenendez issue. Please reopen if not!
