### ISSUE TITLE
youtubedl.py

### ISSUE THREAD

**Issue by ameliameyer** [DocNow/twarc#433]
```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by edsu** [comment]
Can you make sure you are running the latest version of the youtubedl.py utility? Since these utilities are not versioned the only way to do this is to download the latest version, either directly or by doing a `git pull` if you have cloned the repository. This is something that twarc2's [plugin architecture](https://twarc-project.readthedocs.io/en/latest/plugins/) should improve.

**Comment by edsu** [comment]
Without more information I'm not sure it's possible to help more with this one.

**Comment by ameliameyer** [comment]
I checked and I'm using the latest version of youtubedl.py and youtube-dl. I'm no longer getting the error from above, but now it returns the errors below. 

![Screenshot (379)](https://user-images.githubusercontent.com/52171886/116603216-86f14980-a8e1-11eb-9270-56af545bf7dc.png)

Do you have a small sample dataset I could test the utility on? I'm not sure if the problem is with the current one I'm working on.

**Comment by edsu** [comment]
I should say that we are now encouraging people to migrate to using twarc2 which comes with a plugin for extracting videos. For example if you have Academic Search turned on for your account you can search for [Antonio French](https://twitter.com/antoniofrench)'s tweets from the Ferguson protests in 2014 and then download the videos:

```
% pip install twarc-videos
% twarc2 search 'from:antoniofrench' --start-time 2014-08-03 --end-time 2014-08-17 --archive antoniofrench.jsonl
% twarc2 videos antoniofrench.jsonl
% ls videos
archive.txt  CNN  generic  mapping.tsv  Vine  youtube
% ls videos/Vine 
M3a7Wq6d3vX  M3aBvuW1PWh  M3aKd67vJ3Y  M3aWxOujVUq  M3b76Ix5vZV  M3bZQLpAHP0  M3uT5wH9b7t  M3zQwXiiU1u
M3aaEW2636p  M3AEaLnYXlr  M3aqzhWl7ze  M3aWZd22b0K  M3b7aFArnT9  M3q7jmIYTJB  M3zl913ZKqj  M3zY0EgLpUw
M3aalzgmErO  M3ag7nuj3z5  M3aUgh9dmtq  M3az7bneHbg  M3bmAOa7pQI  M3q7L27vUE6  M3zldQn9nrm  M3zYOvmv2ah
M3abhX65O67  M3aK9pJLQnr  M3awxFJ6TYQ  M3aZre1Kahp  M3bmvAYTW2b  M3uJiYKlteV  M3zQJh2aLEH  MYwnLqwDLD2
% ls videos/Vine/M3aKd67vJ3Y
Protestors_blocking_into_Beauty_Supply_Store.info.json
Protestors_blocking_into_Beauty_Supply_Store.mp4
```

**Comment by ameliameyer** [comment]
So I ran youtubedl.py again and the directory appeared this time. Thank you!

**Comment by edsu** [comment]
Great!
