### ISSUE TITLE
Academic Search results truncated?

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#434]
I'm noticing that I can only get a months worth of results back from the `/2/tweets/search/all` endpoint. But I can get more as long as I use `--end-time`. 

For example searching for `from:barackobama` yields tweets back to 2021-03-17 and then twarc stops:

```
twarc2 search from:barackobama --archive --flatten | jq .created_at
...
"2021-03-19T17:01:07.000Z"
"2021-03-18T13:00:08.000Z"
"2021-03-17T14:23:01.000Z"
"2021-03-17T14:23:01.000Z"
"2021-03-17T14:23:01.000Z"
```

But if I ask for more tweets I can get another month:

```
twarc2 search from:barackobama --archive --end-time 2021-03-17 --flatten | jq .created_at
...
"2021-02-19T21:04:07.000Z"
"2021-02-18T22:53:52.000Z"
"2021-02-18T19:02:40.000Z"
"2021-02-17T21:15:27.000Z"
"2021-02-15T21:13:15.000Z"
```

I would expect both commands to keep retrieving tweets back to barackobama's first tweets? I don't know if this is a problem in twarc or this is some kind of limitation of the API. Any insights would be welcome.

**Comment by edsu** [comment]
Oh interesting, it looks like if start time is not supplied it defaults to one month from the current time or one month from the supplied `--end-time`?

For example this will work to get all of barackobama's tweets, since Twitter started on 2006-03-21:

```
twarc2 search from:barackobama --archive --end-time 2006-03-21 --flatten | jq .created_at
...
"2007-05-31T20:46:37.000Z"
"2007-05-19T17:57:28.000Z"
"2007-05-16T19:47:37.000Z"
"2007-05-14T17:25:24.000Z"
"2007-05-11T01:15:18.000Z"
"2007-05-08T21:01:32.000Z"
"2007-05-07T15:52:28.000Z"
```

The [documentation](https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/paginate) says:

> Making requests for a period of data is the default mode of the recent search endpoint. If a search request does not specify a start_time, end_time, or since_id request parameter, the end_time will default to "now" (actually 30 seconds before the time of query) and the start_time will default to seven days ago.

Which makes it sound like the default start-time is seven days ago where I think I was seeing a default of one month. At ay rate for usability I wonder if we should have twarc default --start-time to Twitter Epoch Time (2006-03-21) when --archive is being used and --start-time is not specified?

**Comment by edsu** [comment]
I created a Twitter Community Forum post to see if I'm interpreting things correctly:

https://twittercommunity.com/t/academic-search-results-truncated-after-the-last-month/152742

**Comment by edsu** [comment]
I learned over in the forum post that it is documented that the the `start_time` has this default:

https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-all

Unless there objections I'm going to update twarc to default start_time to Twitter Epoch Time time (2006-03-21 00:00:00) to avoid confusion from users.

**Comment by SamHames** [comment]
No objections here - I think that's the least surprising. One thing I do worry about is people accidentally using all their quota, but maybe there are better ways to address that?

**Comment by edsu** [comment]
Yes, I think it's a legit worry. But depending on your query you could max it out searching a month window too. I guess I was hoping people would get in the habit of using `--limit` to control how much data they get at once?

**Comment by edsu** [comment]
I'm going to put the default in the command line with the understanding that people who are using the Twarc2 client directly will know what they are doing.
