### ISSUE TITLE
Normalize flatten

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#435]
I think it would greatly simplify downstream usage of [twarc.expansions.flatten](https://github.com/DocNow/twarc/blob/main/twarc/expansions.py#L116) in plugins if flatten() always returned a list of tweet objects regardless of whether it was passed a bundled tweet `{"data": {}}`, a bundled list of tweets `{"data": [{...}]}` or an already flattened tweet `{"id": "..."}`.

**Comment by SamHames** [comment]
Wait, when does the first form (`{"data": ""}`) happen?

If we're going down this route I'd suggest that maybe what's really wanted is an ensure_flattened function, so that downstream consumers can rely on the data format?

In the context of #412 and #387 - maybe this would also be a good time to think about a common schema for v1.1 and v2? Or maybe I'm over thinking it.

**Comment by edsu** [comment]
Whoops, that was a typo, I meant `{"data": {}}`. I'd like to keep flattening distinct from a common representation of v1 and v2 data. But maybe that's mistaken?

**Comment by SamHames** [comment]
Ah, it might be a separate consideration, but if the aim is to help plugin authors then handling both formats would mean that they don't have to worry about the distinction at all.

**Comment by igorbrigadir** [comment]
Oh, I thought the flatten function already did this? It should gracefully handle any json and expand if it finds anything worth expanding. Which part is missing? I can have a look later

**Comment by edsu** [comment]
Because it is seen as additive, not destructive, I'm pretty sure flatten() returns the same structure it was given, e.g `{"data": []}` or `{"data": {}}`. It can be a bit tedious to have to unpack that in plugins, and I found myself copy pasting the same code.

After a night's sleep I think @SamHames is right and that flatten should be left as non-destructive, and what is needed is something new that will create a singular JSON representation based off of either the v1 or v2 representation. So I'm going to close this and focus on #412 instead. It's just a bigger job because I need to read the standard more closely.

**Comment by igorbrigadir** [comment]
I feel like there's definitely some loose ends and room for clarifying discussions on formats still. On a related note, the same discussions and concerns like we have in #412, #379, come up elsewhere - by twitter for example https://github.com/twitterdev/search-tweets-python/discussions/123 and https://github.com/twitterdev/search-tweets-python/discussions/116

**Comment by edsu** [comment]
Thanks for those pointers @igorbrigadir -- it would be great if they solved this problem for us. But I think we should move forward with our own solution until it materializes.
