### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc#437]
There are some functions that may benefit from a progress bar: search (because start and end time is known, and we can extract dates from metadata to update) and flatten (file size is known) 

Tqdm is a good one. It's an extra dependency though, good to keep those to a minimum but maybe worth it?

**Comment by edsu** [comment]
I'm a happy user of tqdm and would welcome the addition of progress bars for activities where an endpoint is known. I guess they would have to only work when not writing to stdout.

**Comment by igorbrigadir** [comment]
Yes - i assume i can tell click to behave appropriately, but i haven't tried this yet.

**Comment by igorbrigadir** [comment]
The progress bar works well in twarc-csv - so i think i'll add it to twarc2 later, basing it on the dates / since id ranges.

**Comment by edsu** [comment]
I don't know if you used it but click has progress bar support too.

**Comment by igorbrigadir** [comment]
Thanks! I didn't know that! I will go ahead and use that instead, and remove the tqdm dependency from twarc-csv later too.

**Comment by igorbrigadir** [comment]
Turns out `tqdm` is easier to customize and looks nicer, so i stayed with that instead of click progress bar. If it matters, there's a way to optionally depend on tqdm - but adding it as a dependency shouldn't be a problem: https://github.com/tqdm/tqdm/blob/master/examples/include_no_requirements.py

**Comment by igorbrigadir** [comment]
#490 is almost done, but still needs a few extra things for the other endpoints
