### ISSUE TITLE
hydrate read from stdin

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#44]
It would be nice if it were possible to have twarc read a stream of ids from stdin rather than requiring them to be in an uncompressed file:

```
zcat ids.txt.gz | twarc.py --hydrate | gzip - > tweets.json.tz
```

This would make it similar to the various scripts in utils.

**Comment by dimazest** [comment]
or to read an archive

**Comment by edsu** [comment]
@dimazest do you mean a .gz file?

**Comment by dimazest** [comment]
Yes. please see #110

**Comment by pnasrat** [comment]
This is old and appears to be supported via stdin using `-` and can probably closed. Tested using 

`
echo 501064188211765249 | twarc hydrate -
`

**Comment by edsu** [comment]
Awesome, thanks!
