### ISSUE TITLE
missing JSONDecodeError import

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc#447]
JSONDecodeError is not imported in decorators.py, so when an error happens, Requests throws either a `json.decoder.JSONDecodeError` or, `simplejson.errors.JSONDecodeError` which is ambiguous.

https://github.com/DocNow/twarc/blob/main/twarc/decorators.py#L187

This causes a "NameError: name 'JSONDecodeError' is not defined" for a few people, for example #441 which won't solve their problem but gives it a weird message.

**Comment by edsu** [comment]
Yes, this is my bad. U added that exception having but could not test since I haven't been able to replicate the problem yet.
