### ISSUE TITLE
gender.py

### ISSUE THREAD

**Issue by ameliameyer** [DocNow/twarc#450]
When using gender.py, I get the error

`from normalizr import Normalizr
ModuleNotFoundError: No module named 'normalizr' `

Is [this](https://github.com/paularmstrong/normalizr) the documentation for the normalizr module being used in this utility?

**Comment by edsu** [comment]
Definitely keep a critical eye on any results that gender.py generates. That said I'm not sure where you found that line. It doesn't appear in gender.py.

It was a while ago, but I think the library that the script relies on is [genderator](https://github.com/bmuller/genderator)
