### ISSUE TITLE
Retweet text cutoff in twarc v2

### ISSUE THREAD

**Issue by santoshbs** [DocNow/twarc#452]
I am using twarc v2 search command to fetch tweets. The retweet texts are cut off. Is there a way to fetch the full text for retweets?

**Comment by lxcode** [comment]
The API itself delivers those tweets truncated, but you can find the full retweeted text inside the ```text``` field of the ```referenced_tweets``` object.

**Comment by edsu** [comment]
Good call @lxcode. It can be much easier to see the `referenced_tweets` if you flatten your data, either after the fact:

    twarc2 search 'obama is:retweet' > tweets.jsonl
    twarc2 flatten tweets.jsonl > tweets-flat.jsonl

or as part of the initial data collection:

    twarc2 search 'obama is:retweet' --flatten > tweets.jsonl

**Comment by edsu** [comment]
Please reopen the ticket if you have trouble locating the tweet text @santoshbs
