### ISSUE TITLE
saving twarc2 data to CSV

### ISSUE THREAD

**Issue by Shaimaai** [DocNow/twarc#458]
Hi everyone,

I would like to ask about the way of saving the twarc2 Twitter data to CSV format, I had an issue with saving the data to this format. If anyone could help me, I would be thankful.

Regards,

**Comment by igorbrigadir** [comment]
What were the exact commands you ran and what were the issues?

**Comment by Shaimaai** [comment]
> What were the exact commands you ran and what were the issues?

Hi,
Thanks for your reply :)

I am using these commands https://twarc-project.readthedocs.io/en/latest/twarc2/ 

The issue is, I could not understand how can I save the data to CSV, it is not clear enough to me, if you know the exact command of saving data, I will be much thankful and greatful.

**Comment by Shaimaai** [comment]
> What were the exact commands you ran and what were the issues?

P.S. I run this in Mac terminal

**Comment by igorbrigadir** [comment]
Yeah those docs don't have the CSV commands because `twarc-csv` is a plugin, those commands are here: https://github.com/docnow/twarc-csv 

Make sure `twarc-csv` is installed:

```
pip3 install --upgrade twarc twarc-csv
```

After you run some command to get tweets and saved a file, `twarc2 csv` is a separate command that runs, for example:

```
twarc2 search --limit 500 "blacklivesmatter" tweets.jsonl # collect some tweets
twarc2 csv tweets.jsonl tweets.csv # convert to CSV
```

**Comment by Shaimaai** [comment]
> Yeah those docs don't have the CSV commands because `twarc-csv` is a plugin, those commands are here: https://github.com/docnow/twarc-csv
> 
> Make sure `twarc-csv` is installed:
> 
> ```
> pip3 install --upgrade twarc twarc-csv
> ```
> 
> After you run some command to get tweets and saved a file, `twarc2 csv` is a separate command that runs, for example:
> 
> ```
> twarc2 search --limit 500 "blacklivesmatter" tweets.jsonl # collect some tweets
> twarc2 csv tweets.jsonl tweets.csv # convert to CSV
> ```

Great, I think I did it :)
but I did not know where it saved (see the image below) 

<img width="569" alt="Screen Shot 2021-05-15 at 9 48 53 PM" src="https://user-images.githubusercontent.com/75612098/118373405-b1bcec80-b5c7-11eb-9729-fd3d67e898d0.png">

**Comment by igorbrigadir** [comment]
if the command you ran is 

```
twarc2 csv tweets.jsonl tweets.csv
```

`tweets.csv` will be in the folder that the terminal is open in. You can make the terminal output the folder name with `pwd` command

**Comment by Shaimaai** [comment]
found it 👍 
Many Many thanks, this is much helpful.
