### ISSUE TITLE
issue in pulling tweets by using twarc2

### ISSUE THREAD

**Issue by Shaimaai** [DocNow/twarc#460]
Hi again, 
I know, I asked too much these days :)

I have another issue in twarc2, when I use Arabic hashtag like this (below)

(twarc2 search "lang:ar (#كوفيد)" --archive

I got tweets about "blacklivesmatters", I tried another hashtag, I got the same tweets of the first hashtag, both hashtags are totally different and I got tweets from (blacklivesmatter)'s hashtag 

P.S I used this command to save the tweets (twarc2 csv tweets.jsonl tweets.csv)

anyone can help?

Thanks

**Comment by edsu** [comment]
I don't see any blacklivesmatter content when I run `twarc2 search "lang:ar (#كوفيد)" --archive`. Perhaps you are confused about your output files?

**Comment by Shaimaai** [comment]
<img width="1261" alt="Screen Shot 2021-05-16 at 8 03 32 PM" src="https://user-images.githubusercontent.com/75612098/118404465-0756cf00-b684-11eb-8ef9-7a39776dbab8.png">

<img width="1320" alt="Screen Shot 2021-05-16 at 8 04 17 PM" src="https://user-images.githubusercontent.com/75612098/118404469-0cb41980-b684-11eb-99ce-1efe80d28b41.png"


This is what I got
