### ISSUE TITLE
twarc2: csv file deleting some tweets

### ISSUE THREAD

**Issue by santoshbs** [DocNow/twarc#463]
I tried the following commands:

```
twarc2 search from:Bidumequetrefe --archive tmp.jsonl
twarc2 csv tmp.jsonl CSV_tmp.csv
```

The csv file has 6 tweets whereas the jsonl has 7 tweets.  As you can see from https://twitter.com/Bidumequetrefe, the correct number of tweets should have been 7. Not sure what is happening. Is this a known issue?

**Comment by igorbrigadir** [comment]
I recently fixed https://github.com/DocNow/twarc-csv/issues/15

try updating to the latest version with:

```
pip install --upgrade twarc-csv
```

and run the conversion again. If it's still an error - please reopen it here and i'l check it out!
