### ISSUE TITLE
twarc2: csv creating extra row/tweet

### ISSUE THREAD

**Issue by santoshbs** [DocNow/twarc#465]
@igorbrigadir   - thank you for addressing the  #463.

But, there seems to be a different error after upgrading. For the following Twitter handle, twarc-csv creates 7 rows when the handle has only 6 tweets:
Handle: shamilabrek
URL: https://twitter.com/shamilabrek

**Comment by igorbrigadir** [comment]
Thanks - Yes, this is also expected:

There are 6 original tweets from `shamilabrek`, one of which is a retweet. The extra tweet is the original tweet that was retweeted.

If you do not want to include retweeted tweets in the CSV, you can specify `--no-inline-referenced-tweets` but be aware that this means that RTs will look "truncated" as they are their own separate tweets with their own metadata.

If you only want original tweets from the user, you can either filter them yourself in the CSV or specify `from:shamilabrek -is:retweet` as the search query.

Hope that clears it up!
