### ISSUE TITLE
Likes endpoint

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc#466]
New likes endpoint gets you 100 latest users who liked a tweet: 
https://twittercommunity.com/t/blocks-and-likes-endpoints-are-now-complete-on-the-twitter-api-v2/154434

I think it's a useful one to have, even if it's limited. 

For example: 
```
twarc2 likes [tweet id] users.jsonl
```

**Comment by cosmicoptima** [comment]
I'm working on this now

**Comment by cosmicoptima** [comment]
ah, I forgot about this, sorry - well, I will tomorrow

That's a good idea @lxcode

**Comment by igorbrigadir** [comment]
Fyi, the likes endpoint now returns all likes instead of the last 100 https://twittercommunity.com/t/updates-to-retweets-lookup-and-likes-lookup-endpoints/165327?u=igorbrigadir
