### ISSUE TITLE
python -m twarc2 not working

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#470]
It is not possible to use twarc indirectly using:

    python -m twarc2 search blahblahblah

I get a module not found error on Windows10 and Linux.

I did notice that `python -m twarc` works. 

```
➜  ~ python -m twarc         
usage: twarc [-h] [--log LOG] [--consumer_key CONSUMER_KEY] [--consumer_secret CONSUMER_SECRET]
             [--access_token ACCESS_TOKEN] [--access_token_secret ACCESS_TOKEN_SECRET]
             [--config CONFIG] [--profile PROFILE] [--warnings]
             [--connection_errors CONNECTION_ERRORS] [--http_errors HTTP_ERRORS]
             [--max_id MAX_ID] [--since_id SINCE_ID] [--result_type {mixed,recent,popular}]
             [--lang LANG] [--geocode GEOCODE] [--locations LOCATIONS] [--follow FOLLOW]
             [--recursive] [--tweet_mode {compat,extended}] [--protected] [--output OUTPUT]
             [--format {json,csv,csv-excel}] [--split SPLIT] [--skip_key_validation]
             [--app_auth] [--gnip_auth] [--30day THIRTYDAY] [--fullarchive FULLARCHIVE]
             [--gnip_fullarchive GNIP_FULLARCHIVE] [--from_date FROM_DATE] [--to_date TO_DATE]
             [--limit LIMIT] [--sandbox]
             {configure,dehydrate,filter,followers,friends,help,hydrate,replies,retweets,sample,search,timeline,trends,tweet,users,listmembers,version}
             [query]
twarc: error: the following arguments are required: command
```

**Comment by igorbrigadir** [comment]
Not sure why it would fail - i've ubuntu and python and twarc is in a virtualenv, activated with pyenv. Maybe there's something about my setup that makes it work and fail elsewhere.

**Comment by igorbrigadir** [comment]
Does it work if you change `python` here for `python.exe` or `python3` ? https://github.com/DocNow/twarc/blob/main/twarc2.py#L4

**Comment by edsu** [comment]
Interesting, `python -mtwarc2` works for me in a pipenv, but not outside of a pipenv?!

**Comment by edsu** [comment]
Hmm, I think we may need to add `twarc2.py` to the MANIFEST.in so that it gets bundled for PyPI. I noticed the tarball doesn't currently include it?

https://pypi.org/project/twarc/#files

**Comment by edsu** [comment]
@igorbrigadir I did try the update you tried above without a significant change. Have you tried `python -m twarc2` outside of a virtualenv? It works for me fine inside of a virtualenv, but it's outside that fails.
