### ISSUE TITLE
conversations command

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#472]
It might be nice to have a sub command (maybe a plugin) that let you fetch conversation threads for tweets in a file. Kind of like the process that Ryan is suggesting here:

https://twitter.com/ryanjgallag/status/1390727713082728448

    twarc2 search blacklivesmatter > tweets.jsonl
    twarc2 conversations tweets.jsonl > convesations.jsonl

**Comment by edsu** [comment]
I added a `conversation` subcommand. I'm not sure if `conversations` belongs in core twarc or in a plugin. I guess it won't have any crazy dependencies so maybe in the core?

**Comment by igorbrigadir** [comment]
Yes, I think it fits into core - incidentally I think timelines https://github.com/DocNow/twarc-timelines does too, and so does IDs https://github.com/DocNow/twarc-ids but they also make excellent minimal examples of a plugin

**Comment by edsu** [comment]
I've added conversations and moved twarc-timelines into twarc itself, although in a slightly minimal form, It can read the usernames to fetch timelines for from a file of tweets or a file of user ids or usernames each on a line. I left the more complex behavior of writing to a directory of different files, and using since_id to only fetch new data, to a renamed plugin [twarc-timeline-archive](https://github.com/docnow/twarc-timeline-archive).
