### ISSUE TITLE
File not found error encountered while trying to configure twarc2 from command-prompt in windows.

### ISSUE THREAD

**Issue by ShivaniParekh** [DocNow/twarc#481]
While using `twarc2 configure`   , after entering bearer token , I am encountering 
`FileNotFoundError: [Errno 2] No such file or directory: [FILENAME] `

I am using python 3.8.2 version in windows platform. It is installed in C:\Python\Python382 folder , It has write permissions but it is failing to create the config file.
Attaching screenshot of the error I am receiving.
![Screenshot (55)](https://user-images.githubusercontent.com/49021983/121846290-6b60c780-cd04-11eb-8168-be7309a33ff4.png)

**Comment by edsu** [comment]
Thanks for reporting this @ShivaniParekh. The code to create the config directory when not present was accidentally removed and has now been reinstated in twarc v2.1.7. Please upgrade with `pip install --upgrade twarc` and reopen this ticket if you still are having trouble.
