### ISSUE TITLE
Conversations hangs

### ISSUE THREAD

**Issue by JanaLasser** [DocNow/twarc#482]
I have been trying to download conversations using the twarc2 conversations functionality and supplying a list of 1000 conversation IDs. I have academic research API access. This is the command I used:

`twarc2 conversations conversation_IDs/batch_0_to_1000.txt conversations/batch_0_to_1000.jsonl`

It works fine for the first batch of 1000 IDs. For the second batch, the command just hangs and no output file is created. I waited for >1 hour and the command still did not execute. 

It's hard to figure out what is going on. Using `--verbose` also doesn't give me any hints on what's happening. My suspicion is, that it has something to do with the API's rate limits. If that is the case, some warning in stdout would be nice. That doesn't explain, why the command doesn't execute after ~15 min have passed, though...

**Comment by edsu** [comment]
Do you see any information in the twarc.log file?

**Comment by JanaLasser** [comment]
Indeed: I see "rate limit exceeded, sleeping for XXX seconds" warnings. 

I just tried to recreate the behaviour with the 2.1.7 version (I believe when I first encountered this I was using 2.1.5). Now a file gets created after the sleeping is finished. I will let it run and see if it finishes executing overnight.

**Comment by JanaLasser** [comment]
Update: conversations now works for me, fetching all conversations and properly closing the file once it is done again.

**Comment by edsu** [comment]
Great, thanks for confirming @JanaLasser!
