### ISSUE TITLE
Shorter default rates and backoff on 503 errors

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#495]
Since it seems like we've got some Twitter API instability affecting people, can I suggest a less invasive short term workaround is to:

- Lower the default wait on 503 errors
- For the academic search endpoint, backoff on both the pagesize and the wait time - that is on 503 error, halve the number of tweets retrieved in a page

**Comment by edsu** [comment]
I like this idea, would the backoff in pagesize and wait time ease back again?

**Comment by SamHames** [comment]
I don't have an academic access to check against, but something like this should work:

https://github.com/DocNow/twarc/compare/503_search_all_workaround?expand=1

This will reset the max_results back  to the maximum after every successful request - a more sophisticated implementation might try to keep track of the last successful page size and only gradually increase that, but that requires keeping track of that state somewhere as currently each request is totally independent.

**Comment by edsu** [comment]
@SamHames did you mean to send a PR for that? Also, message me if you want some keys to test Academic.

**Comment by edsu** [comment]
This was part of #499
