### ISSUE TITLE
Wrong timestamps in `__twarc` metadata

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc#507]
Via DM, will investigate wrong timestamps being included in the `__twarc` metadata. Not sure if this is introduced in some processing or somewhere else.

**Comment by SamHames** [comment]
How far are they wrong? My first thought was timezones, my second thought
was to confirm the system time is correct.

**Comment by igorbrigadir** [comment]
Ok, I double checked, and it seems that the data was not coming directly from `__twarc` - the errors were in the timestamp values as integers, not as a string like `__twarc` writes it `2021-07-13T18:56:46+00:00` so whatever custom code was parsing these must have had a bug, not twarc.
