### ISSUE TITLE
Unable to convert to csv and other problems... oh! I must just flatten before

### ISSUE THREAD

**Issue by numeroteca** [DocNow/twarc#508]
I recently downloaded tweets with this command:

`twarc2 search 'cifuentes' --start-time 2018-04-05T14:41:19 --end-time 2018-04-08T16:35:20 --archive --max-results 100 > original-to-compare/cifuentes_0_compare-w-thoarder.jsonl`

When I try to see the content with `head cifuentes_0_compare-w-thoarder.jsonl | jq .text` I get:
```
null
null
null
null
```

When I try to convert it to csv `twarc2 csv cifuentes_0_compare-w-thoarder.jsonl cifuentes_0_compare-w-thoarder.csv` I get this error and doesn't work:
```

  0%|                                                      0.00/1.49G [00:00<?, ?B/s]Traceback (most recent call last):
  File "/home/numeroteca/.pyenv/versions/3.8.1/bin/twarc2", line 11, in <module>
    load_entry_point('twarc==2.3.10', 'console_scripts', 'twarc2')()
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc_csv.py", line 251, in csv
    converter.process()
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc_csv.py", line 202, in process
    self._write_output(self._process_batch(batch), first_batch)
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc_csv.py", line 169, in _process_batch
    _df = pd.json_normalize([tweet for tweet in tweet_batch])
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc_csv.py", line 169, in <listcomp>
    _df = pd.json_normalize([tweet for tweet in tweet_batch])
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc_csv.py", line 164, in <genexpr>
    tweet_batch = itertools.chain.from_iterable(
  File "/home/numeroteca/.pyenv/versions/3.8.1/lib/python3.8/site-packages/twarc_csv.py", line 81, in _handle_formats
    for i in flatten(item)["data"]:
TypeError: list indices must be integers or slices, not str
  0%|                                                                   
```

It seems the beginning of the file is different from the ones I got earlier. 
Current file:
`{"data": [{"created_at": "2018-04-08T16:35:19.000Z", "conversation_id": "983020473377329154", "lang": "es", "text": "RT @FranciscoIgea: Tan cerca de Cifuentes...tan lejos de los espa\u00f1oles. Una ovaci\u00f3n cerrada al privilegio. Perdonen que no me levante https\u2026", "id": "983020473377329154", "public_metrics": {"retweet_count": 249, "reply_count": 0, "like_count": 0, "quote_count": 0}, "author_id": "189441166", "source": "Twitter for Android", "referenced_tweets": [{"type": "retweeted",`

Previous file downloaded weeks ago (with `twarc2 search 'cifuentes' --start-time 2018-03-20 --end-time 2018-03-21 --archive --flatten > test-cifuentes.jsonl`, I see now that --flatten does not work anymore!).
`{"created_at": "2018-04-07T23:59:59.000Z", "author_id": "1263263179", "attachments": {"media_keys": ["3_982769988237910016"], "media": [{"width": 1024, "url": "https://pbs.twimg.com/media/DaOAGOzV4AAMIOm.jpg", "height": 576, "type": "photo", "media_key": "3_982769988237910016"}]}, "possibly_sensitive": false, "public_metrics": {"retweet_count": 0, "reply_count": 0, "like_count": 0, "quote_count": 0}, "reply_settings": `

So I see that the current one is in a array "data" and the other "flattened" has all its tweets one per line. So I just need to flatten to make the `jq` or the convert to `csv` work: `twarc2 flatten cifuentes_0_compare-w-thoarder.jsonl cifuentes_0_compare-w-thoarder_flatten.jsonl`

I suggest to add this as an example in the documentation (https://twarc-project.readthedocs.io/en/latest/twarc2/#flatten) anda sentence explaining why:

Example:
`twarc2 flatten input_file_name.jsonl output_file_name.jsonl`
Flatten the jsonl file is needed to convert to csv, for example.

**Comment by igorbrigadir** [comment]
`--flatten` (and the need to flatten) was removed a while ago in v2.2.1 - what versions of twarc and twarc-csv come up for you if you run `pip list` ?

It should be:

```
twarc                      2.3.10
twarc-csv                  0.3.6
```

If older, upgrade with 

```
pip install --upgrade twarc twarc-csv
```

`--max-results 100` is also redundant because that's the default now.

Using `>` is generally ok but not recommended on windows, as this can sometimes make an awkwardly formatted file with a byte order mark (BOM) instead of utf8 file which makes reading the file error prone.

I can successfully run (i added `--limit 1000` just to get a sample):

```
twarc2 search 'cifuentes' --start-time 2018-04-05T14:41:19 --end-time 2018-04-08T16:35:20 --archive --limit 1000 cifuentes_0_compare-w-thoarder.jsonl
```

and 

```
twarc2 csv cifuentes_0_compare-w-thoarder.jsonl cifuentes_0_compare-w-thoarder.csv
```

gives me a correct csv.

To get the `jq` command to work, it should be `jq '.data[].text'`:

```
head cifuentes_0_compare-w-thoarder.jsonl | jq '.data[].text'
```

Or if you need 1 tweet per line like the old `--flatten` output, the flatten command still works so you can pipe it:

```
head cifuentes_0_compare-w-thoarder.jsonl | twarc2 flatten | jq '.text'
```

Does that help? (Agreed on need to add more to the docs about this)

**Comment by numeroteca** [comment]
That is very helpful. I had and old version of twarc-csv (0.1.0). Everything works well now.
I am glad to help with the documentation and provide examples and mini-tutorials if you think that helps. This issue, for example, would be of great help while starting.

I am still using the notes I took in the introduction you gave on Twitch.

**Comment by igorbrigadir** [comment]
Sure! Feel free to edit https://github.com/DocNow/twarc/tree/main/docs in a new pull request for docs!

**Comment by edsu** [comment]
I think this can be closed? Please reopen if that's not the case!
