### ISSUE TITLE
Organize twarc/command2.py

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#514]
twarc/command2.py is at 1346 lines. In principle I kind of like Python modules that are in one file. But I wonder if it's getting unwieldy and we should break them out into separate, subcommand specific files inside a command2 directory? Do you have thoughts? Talk me down from this cliff.

**Comment by SamHames** [comment]
If the only reason is to make the files smaller I'd say leave it how it is.
I do appreciate the simple structure, even if it does makes for a long
file.

That being said, if I were to start breaking down the file I'd start seeing
if there are any logical breakdowns of the existing functionality (from an
implementation perspective - users shouldn't have to worry about that of
course).

**Comment by igorbrigadir** [comment]
There's definitely room to refactor things - it's not too bad i don't think - but maybe a way that might be good is to split it like this:

Keep all the "command line" boiler plate together - like this https://github.com/DocNow/twarc/blob/main/twarc/command2.py#L269-L330 in one file, and the actual functionality like https://github.com/DocNow/twarc/blob/main/twarc/command2.py#L207-L266 separately? 

Just thinking out loud, haven't thought this through for long.

**Comment by edsu** [comment]
Thanks for talking me down from it. I'm actually fine with things being in the same file but wasn't sure what you both thought. I do like the idea of separating the command specific boilerplate from some of the internal functions. I'll rename this accordingly.

**Comment by edsu** [comment]
This seems not so important anymore. I'm closing it to reduce the clutter.
