### ISSUE TITLE
How can I reduce sleeping time?

### ISSUE THREAD

**Issue by yanhuibin315** [DocNow/twarc#521]
I use python code to ```Twarc.hydrate```. But sometimes I got this WARNING: ```WARNING:twarc:rate limit exceeded: sleeping 362.15412998199463 secs```. Sleeping time always from 100~600secs and that is so slowly to me. Can I set any config can reduce this sleeping time or set a timeout secs?

This is my code:
```python
from twarc import Twarc

t = Twarc(consumer_key, consumer_secret, access_token, access_token_secret)
hyd = t.hydrate(need_get_id_list)
writer = jsonlines.open(save_file_name, "w")

writer.write_all(hyd)
```

**Comment by SamHames** [comment]
The sleep is to avoid hitting the Twitter API rate limit - there is no way
to avoid it, sorry.

Attempting to evade the rate limits can also lead to your API keys being
blocked permanently.
