### ISSUE TITLE
Merging conversation API responses?

### ISSUE THREAD

**Issue by edent** [DocNow/twarc#522]
Thanks for the great tool - works perfectly at getting long conversations. But I'm not sure if I'm using the tool correctly.

Is there a way using `twarc2` to merge the `data` and `includes` arrays?

If I get a thread which requires multiple API calls, it seems like each API response is stored on a different line, rather than being merged. For example: `twarc2 conversation 1428438081871433731 bus.json` returns a file which looks like:

```
{"data": [{"referenced_tweets": [{"type": "replied_to", "id": "1428438081871433731"}], "id": "1429187026692235269", "entities": {"mentions": [{"start": 0, "e>
{"data": [{"id": "1429120066470166532", "created_at": "2021-08-21T16:35:50.000Z", "lang": "en", "reply_settings": "everyone", "possibly_sensitive": false, "p>
{"data": [{"conversation_id": "1428438081871433731", "entities": {"mentions": [{"start": 0, "end": 15, "username": "politic_animal", "id": "59532544"}]}, "cr>
{"data": [{"reply_settings": "everyone", "conversation_id": "1428438081871433731", "geo": {"place_id": "36a9a9013f769192"}, "source": "Twitter for iPhone", ">
{"data": [{"lang": "en", "entities": {"mentions": [{"start": 0, "end": 15, "username": "politic_animal", "id": "59532544"}], "annotations": [{"start": 190, ">
{"data": [{"reply_settings": "everyone", "entities": {"mentions": [{"start": 0, "end": 15, "username": "politic_animal", "id": "59532544"}]}, "id": "14290328>
{"data": [{"in_reply_to_user_id": "136185481", "lang": "und", "author_id": "34715179", "entities": {"urls": [{"start": 65, "end": 88, "url": "https://t.co/tn>
```

Each individual line is valid JSON, and I can use it in my projects. But the twarc file as a whole isn't valid JSON.

Does `twarc2` supported merging the `data` and `includes` arrays from multiple API calls?

Thanks.

**Comment by edsu** [comment]
twarc uses [JSON lines](https://jsonlines.org/) wherever it can. This allows people to read a line from a file, parse it as JSON, do something with the data, and then move on to the next line. Taking thousands or millions of objects and slamming them into the same JSON object can be quite problematic since it requires all the data to be loaded into memory.

Are you having difficulty reading the file? What programming language are you using?

**Comment by edsu** [comment]
One thing you might be interested in doing is converting the data to CSV with the [twarc-csv](https://github.com/docnow/twarc-csv). Then you can probably process it much easier?

**Comment by edent** [comment]
Ah, I see! That's me not quite understanding how the tool works :-)

I'm doing some visualisations of Twitter conversations - so it's generally easier if I have one large array to work with. But that's something I can fix at my end.

Thanks for the swift reply. Have a great weekend.

**Comment by igorbrigadir** [comment]
```
twarc2 flatten input.json output.json
```

Will give you 1 tweet per line if that helps, and everything from includes will be inside the tweet. (Like referenced tweets, places etc)
