### ISSUE TITLE
Getting Tweets within a particular location?

### ISSUE THREAD

**Issue by joseph-allen** [DocNow/twarc#524]
Is there any way to get tweets within a particular city, or latlon with a radius?

I've been using this, particularly the --geocode flag as used in the twarc docs.

`twarc2 search --archive --max-results 100 --start-time "2019-01-01" --end-time "2019-01-30" "vegan OR plant-based OR plant based OR veganism -is:retweet --geocode 53.763208,-2.699540,3mi" dataPreston.jsonl`

It seems to get data from all over the place, over 1.2 million tweets for that month.

**Comment by SamHames** [comment]
To answer your question - I don't think we have any specific examples in the docs yet - if you can think of something to add that would have helped you it would be very welcome :)

**Comment by joseph-allen** [comment]
I did both a place search, and a point search in the end

```
twarc2 search --archive --start-time "2019-01-01" --end-time "2019-01-30" '(vegan OR plant-based OR "plant based" OR veganism) point_radius:[-0.127758 51.507351 5mi]' londonGeoPointRadius.jsonl
twarc2 search --archive --start-time "2019-01-01" --end-time "2019-01-30" '(vegan OR plant-based OR "plant based" OR veganism) place:london' londonGeoPlace.jsonl
```

We could add a simpler
```
twarc2 search --archive vegan point_radius:[-0.127758 51.507351 5mi]' londonGeoPointRadius.jsonl
twarc2 search --archive 'vegan place:london' londonGeoPlace.jsonl
```

**Comment by igorbrigadir** [comment]
@joseph-allen the query:

```
"vegan OR vegetarian OR plant-based point_radius:[-0.127758 51.507351 5mi] -is:retweet"
```

is ambiguous because of how `OR` clauses are interpreted - a space is an implicit AND, so you need to surround the OR clauses with () parentheses, see https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query#order-of-operations

Your query should be:

```
"(vegan OR vegetarian OR plant-based) point_radius:[-0.127758 51.507351 5mi] -is:retweet"
```
