### ISSUE TITLE
counts truncated?

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#525]
I was running this `counts` command and noticed that the results were truncated at `2016-11-22`:

    twarc2 counts '(vegan OR plant-based OR "plant based" OR veganism) point_radius:[-0.127758 51.507351 25mi]' --archive --csv --granularity day counts.csv

Looking at the log it appears that the code might be assuming there are no more results when a response comes back with no `data` stanza in the JSON payload?

    2021-08-26 08:11:11,802 INFO Retrieved an empty page of results.
    2021-08-26 08:11:11,803 INFO No more results for search (vegan OR plant-based OR "plant based" OR veganism) point_radius:[-0.127758 51.507351 25mi].

**Comment by SamHames** [comment]
Have you run into this again? I can't say I've seen it yet, but I haven't been going that deep into archives lately.

**Comment by edsu** [comment]
I think this was fixed as part of #602
