### ISSUE TITLE
Is it possible to use regular expressions while collecting tweets with Twarc?

### ISSUE THREAD

**Issue by Michael-Gauthier** [DocNow/twarc#527]
Hello again,

Following my previous post, but with a different question this time... 

I plan to collect historical tweets using the academic track, and I am mainly going to focus on specific key terms. However, I would like to know if an option exists that would allow me to use regular expressions. For example, let's say I want to collect all tweets containing the terms "climate change", I would also like to collect tweets containing expressions like "climate-change-related events". So essentially I would need to be able to process the regular expression corresponding to: 

`twarc2 search --archive '("climate?change")`

Is there any way to do that?

Lastly, are twarc keyword searches of the kind case insensitive?

Thanks again in advance for any help anyone could offer! : )

**Comment by SamHames** [comment]
Regular expressions aren't supported bt the Twitter API, and twarc is a
wrapper for that, so unfortunately that won't work. (you probably wouldn't
want to wait for a regex on the Twitter archive either)

However, you can have up to 1024 characters in the query, so you might
approach that with a group of phrase searches like '"climate change" OR
climatechange OR "global warming"'. If your search doesn't fit into that
limit you could run multiple searches and then merge the different results
but that's more fiddly. You'd also have to check how hyphenation is handled
(ie in a search for "climate-change", I think it might be treated as two
separate words)

Twitter search is always case insensitive.

**Comment by edsu** [comment]
Also the regular expression `climate?change` would match `climat change` or `climatechange`. 

I think your best bet is to use OR to collect as many relevant terms as you can think of. You can use regular expressions when analyzing the collected data.
