### ISSUE TITLE
CLI entrypoint for running multiple searches

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#528]
There are a few common use cases that can be boiled down to "run many searches" - think of retrieving the mentions for lots of different accounts, or searching for lots of keywords or phrases that wouldn't otherwise fit into a single search.

It would be nice if there were a `twarc2 searches` command that works similarly to the timelines command, taking an input file with one line per query, and working through the list to retrieve everything.

It would be even nicer if it batched and concatenated queries up to the character limit, to minimise the number of API calls made.

**Comment by edsu** [comment]
This sounds *very* useful. I wonder if like timelines it could be run repetitively without needing to refetch the same data again? This is kind of the way that the old [twarc-archive.py](https://github.com/DocNow/twarc/blob/main/utils/twarc-archive.py) utility worked.

**Comment by igorbrigadir** [comment]
This is a great idea! Especially the batching queries part, if we specify the input as a textfile where it's 1 query per line it could work and not get too complicated
