### ISSUE TITLE
Updating definition of "following" in twarc2 docs?

### ISSUE THREAD

**Issue by jwyg** [DocNow/twarc#531]
Currently the definition of following in [twarc2 docs](https://twarc-project.readthedocs.io/en/latest/twarc2/) is:

> **following**
> Get the users who are following a given user.

But presuming this corresponds to ```GET friends/list``` in [Twitter API](https://developer.twitter.com/en/docs/twitter-api/users/follows/introduction) perhaps it might be clearer if this read:

> **following**
> Get the users who are followed by a given user.

**Comment by igorbrigadir** [comment]
The reason why is that `twarc2` aligns with the v2 API, while `twarc` implements v1.1, so it keeps the naming for endpoints and resources from the API:

In v2 API:

*following* in twarc2 https://twarc-project.readthedocs.io/en/latest/twarc2/#following calls https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/get-users-id-following

*followers* in twarc2 https://twarc-project.readthedocs.io/en/latest/twarc2/#followers calls https://developer.twitter.com/en/docs/twitter-api/users/follows/api-reference/get-users-id-followers

In v1.1 API for `twarc`:

*friends* (draws on the same data as _following_) above
https://twarc-project.readthedocs.io/en/latest/#friends calls the https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friends-ids endpoint, not the `/list` one.

And *followers* https://twarc-project.readthedocs.io/en/latest/#followers in v1.1 calls https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-followers-ids

Hope that helps!

**Comment by edsu** [comment]
I always have to remind myself of the difference between followers and following. If there's a better way to explain the difference in the docs please let us know!

**Comment by igorbrigadir** [comment]
Maybe i'll update the docs linking to the API endpoints after all - like the client docs do: https://twarc-project.readthedocs.io/en/latest/api/client2/#twarc.client2.Twarc2.following

**Comment by jwyg** [comment]
Thanks for the background!
In case useful the rewording that I was proposing was from the current:

> following
> Get the users **who are following** a given user.

to:

> following
> Get the users **who are followed** by a given user.

As far as I understand I think the latter is a more accurate description of the data that is being returned (I did a test with my own Twitter account to confirm this!).

**Comment by igorbrigadir** [comment]
Ah ok - i see what you mean - that makes more sense!

**Comment by edsu** [comment]
I'm not sure why, but this fits my brain better:

> following
> Get the users that a given user is **following**.

Maybe because it ties the name of the subcommand to the description?

**Comment by jwyg** [comment]
Perfect :-)

**Comment by edsu** [comment]
Future twarc users thank you @jwyg!
