### ISSUE TITLE
Document iterating through pages of results with the client library as a way to limit API calls.

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#532]
As raised in #530 the CLI exposes a --limit option, which is a convenient but rough way to avoid making too many API calls. When using the client though, I think it makes more sense to use the one API call per yielded response model exposed by the generators for each method on the client to control the pagination.

There's no reason to consume all of the results of a call if you don't need them - but I'm not quite sure where we would fit this in the docs. I think the section heading is "Controlling the number of API calls you make via the client", and it doesn't fit in the docstrings themselves, more a guide that sits alongside?

**Comment by igorbrigadir** [comment]
I think there's room for a "Using twarc as a library" page, under "Library API" with all these examples, same place as the expansions  https://github.com/DocNow/twarc/blob/main/mkdocs.yml#L32 - last time though, I added a page I forgot about that yaml and it took me ages to figure out why it wasn't showing 😅

**Comment by igorbrigadir** [comment]
I added a page with examples here as a start: https://twarc-project.readthedocs.io/en/latest/api/library/

**Comment by igorbrigadir** [comment]
I think that page gives a good explanation, but feel free to make edits to the docs!
