### ISSUE TITLE
Installation of twarc2 using pip doesn't checks for requirements version

### ISSUE THREAD

**Issue by zenquiorra** [DocNow/twarc#533]
I installed twarc on Windows using
`python -m pip install twarc`

and while running the twarc2 associated commands, I received an error that said:

No method found: some method name in `click`, 

Then I checked my `click` package, and it didn't have this method that twarc2 uses, because the version of my `click` package was not the latest one and lacked the required method.

After upgrading `click`, I was able to run twarc2 associated commands without any bugs, which led me to wonder if twarc installation using `pip` checks for the version of required dependencies or not because if it did, then my `click` package should have been upgraded too as a part of the requirements check during twarc installation. 

So, a version check of the requirements while installing using pip can solve this issue for others.

**Comment by edsu** [comment]
Thanks for taking the time to sort through this @zenquiorra -- you're right, we should pin the dependencies!
