### ISSUE TITLE
Would be handy to have a progressbar that uses the number of lines in the file, not the bytes

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#541]
FileSizeProgressBar isn't quite right for line based inputs like hydration, timelines and the searches functionality proposed in #540 

Ideally we'd have a LinesInFileProgressBar for those cases.

**Comment by igorbrigadir** [comment]
Yeah - i can add one of those - when it first implemented it, i went with bytes to avoid reading huge files just to get a count of the lines, but maybe there's a fast way to do that or only use it for smaller files (< 1 GB)
