### ISSUE TITLE
twarc2 docs

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#544]
At this stage I think it makes sense to cycle out the twarc examples in docs/README.md for twarc2 equivalents, and then copy the old page to to docs/README_v1 ? I have an immediate need because I'm doing a small workshop and would like to point users to https://twarc-project.readthedocs.org to get started. The translations of course would need to be updated too, but that will be easier once there is something to translate :-)

**Comment by igorbrigadir** [comment]
Yep, agreed. I'll try to help with that if I can

**Comment by numeroteca** [comment]
I agree, that's what I'd expect to see as main documentation.
I opened a subsection in the wiki to complete the "End to End Example Twitter Study" https://github.com/DocNow/twarc/wiki/End-to-End-Example-Twitter-Study#a-simple-step-by-step-twitter-analysis-guide-with-twarc2

**Comment by edsu** [comment]
This is partly done now, see https://twarc-project.readthedocs.org ... I think the twarc2 page could use some more information but I'm going to close this for now, and we can add more to it as we need to.
