### ISSUE TITLE
twarc2 Broken Data (search query)

### ISSUE THREAD

**Issue by desperateBeginner7** [DocNow/twarc#546]
Hello,

I am using the academic API v2 and twarc2. It is the first time I am using twarc but something seems to be broken.

I am doing the following commands:

`twarc2 search "cats" cats.jsonl #collecting some tweets`

It collects the tweets and everything seems fine.

`twarc2 csv cats.jsonl cats.csv #converting to csv`

Now I get the following error:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\Scripts\twarc2-script.py", line 11, in <module>
    load_entry_point('twarc==2.5.0', 'console_scripts', 'twarc2')()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\twarc_csv.py", line 44, in csv
    na_action="ignore",
TypeError: applymap() got an unexpected keyword argument 'na_action'

So I tried to convert the json file via an online json-to-csv converter. That kind of works but there are a lot of empty rows and missing information in the csv when I open it with Excel. So I am assuming something is wrong with the data that twarc2 collects for me. 

What I tried to do:
- Update twarc and twarc csv (did not help)
- Flattening the data (did not help either)

I am really desperate right now and would appreciate any kind of help! 
I need to finish my academic project within a given time frame and this is a serious problem for me :(

**Comment by edsu** [comment]
Hi @desperateBeginner7  It looks like you might have a version of pandas installed that doesn't have the `na_action` option on `DataFrame.applymap()`. 

The latest version of twarc-csv specifies the version that's required. Did you try updating twarc-csv this way?

    pip3 install --upgrade twarc-csv

**Comment by desperateBeginner7** [comment]
Thank you @edsu for answering!

Yes, I already tried that. This is what the response looks like:

`C:\Users\User>pip3 install --upgrade twarc-csv
Requirement already satisfied: twarc-csv in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (0.0.1)
Collecting twarc-csv
  Using cached twarc-csv-0.3.8.tar.gz (6.3 kB)
Requirement already satisfied: twarc>=2.4.0 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from twarc-csv) (2.5.0)
  Using cached twarc-csv-0.3.7.tar.gz (6.2 kB)
  Using cached twarc-csv-0.3.6.tar.gz (6.2 kB)
  Using cached twarc-csv-0.3.5.tar.gz (6.1 kB)
  Using cached twarc-csv-0.3.4.tar.gz (6.2 kB)
  Using cached twarc-csv-0.3.3.tar.gz (6.4 kB)
  Using cached twarc-csv-0.3.2.tar.gz (6.7 kB)
  Using cached twarc-csv-0.3.1.tar.gz (6.4 kB)
  Using cached twarc-csv-0.3.0.tar.gz (6.4 kB)
  Using cached twarc-csv-0.2.0.tar.gz (6.4 kB)
  Using cached twarc-csv-0.1.0.tar.gz (4.4 kB)
  Using cached twarc-csv-0.0.2.tar.gz (2.5 kB)
Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from twarc-csv) (1.1.5)
Requirement already satisfied: pytz>=2017.2 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from pandas->twarc-csv) (2021.1)
Requirement already satisfied: numpy>=1.15.4 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from pandas->twarc-csv) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from pandas->twarc-csv) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from python-dateutil>=2.7.3->pandas->twarc-csv) (1.15.0)
Requirement already satisfied: click<9,>=7 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from twarc>=2.4.0->twarc-csv) (8.0.1)
Requirement already satisfied: click-config-file>=0.6 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from twarc>=2.4.0->twarc-csv) (0.6.0)
Requirement already satisfied: click-plugins>=1 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from twarc>=2.4.0->twarc-csv) (1.1.1)
Requirement already satisfied: humanize>=3.9 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from twarc>=2.4.0->twarc-csv) (3.11.0)
Requirement already satisfied: requests_oauthlib>=1.3 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from twarc>=2.4.0->twarc-csv) (1.3.0)
Requirement already satisfied: tqdm>=4.62 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from twarc>=2.4.0->twarc-csv) (4.62.3)
Requirement already satisfied: importlib-metadata in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from click<9,>=7->twarc>=2.4.0->twarc-csv) (4.2.0)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from click<9,>=7->twarc>=2.4.0->twarc-csv) (0.4.4)
Requirement already satisfied: configobj>=5.0.6 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from click-config-file>=0.6->twarc>=2.4.0->twarc-csv) (5.0.6)
Requirement already satisfied: setuptools in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from humanize>=3.9->twarc>=2.4.0->twarc-csv) (39.0.1)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from requests_oauthlib>=1.3->twarc>=2.4.0->twarc-csv) (3.1.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from requests_oauthlib>=1.3->twarc>=2.4.0->twarc-csv) (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.0.0->requests_oauthlib>=1.3->twarc>=2.4.0->twarc-csv) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.0.0->requests_oauthlib>=1.3->twarc>=2.4.0->twarc-csv) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.0.0->requests_oauthlib>=1.3->twarc>=2.4.0->twarc-csv) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.0.0->requests_oauthlib>=1.3->twarc>=2.4.0->twarc-csv) (2020.12.5)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from importlib-metadata->click<9,>=7->twarc>=2.4.0->twarc-csv) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from importlib-metadata->click<9,>=7->twarc>=2.4.0->twarc-csv) (3.4.1)`

The same issue prevails, unfortunately...
I also updated twarc but that doesn't help either.

**Comment by SamHames** [comment]
Can you try upgrading pandas specifically (pip3 install --upgrade pandas) ?
The output you have suggests you're on pandas version 1.1.5 - you'll need
at least 1.2.5 and the latest release is 1.3.3.

**Comment by desperateBeginner7** [comment]
I already tried that as well: 

`C:\Users\User>pip3 install --upgrade pandas
Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (1.1.5)
Requirement already satisfied: pytz>=2017.2 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from pandas) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from pandas) (1.19.5)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)`

Did not help...

**Comment by desperateBeginner7** [comment]
It appears that the answer to my problem was getting a new computer.
I took a friend's laptop and installed twarc and python. Did everything as described above. It worked.

(Why do I always get those computer-related problems?)

The only weird thing is that the csv has always one blank row in between. Is that normal?

![image](https://user-images.githubusercontent.com/91413863/134810815-3a5e701e-1f34-4d98-8e04-6d7ed429961b.png)

**Comment by SamHames** [comment]
Okay, I think I see what your problem is now - I don't think pandas is
building precompiled wheels for a version of python that old. I'd recommend
you update your Python version and try installing again.

**Comment by SamHames** [comment]
Ah, glad that worked :)

For your second problem - that is nothing to do with the output and
everything to do with Excel mangling your csv file. I wouldn't recommend
using Excel at all if you can avoid it.

If you do need to use Excel there is a totally non obvious set of tricks to
read tweet related csvs, but I'd have to look it up when I'm in the office
tomorrow.

**Comment by desperateBeginner7** [comment]
Okay, thanks for your recommendation. I have no experience with other tools but I am happy to try it out if you name me some alternatives. I managed to get rid of the empty rows using with help of the counta() function. 

And thank you for being helpful!

**Comment by edsu** [comment]
Give Google Sheets a try maybe?

**Comment by igorbrigadir** [comment]
My vote would be Google sheets too. I tested the output on that. 

For excel, it's way easier to just not use it - but if you must, always make a copy of the file for viewing and never re-save it. When opening, always force it to interpret everything as a string https://www.hesa.ac.uk/support/user-guides/import-csv that can sometimes make it work.
