### ISSUE TITLE
Best way to open twarc json (flatten and not) in R? There might be problems with search json format

### ISSUE THREAD

**Issue by numeroteca** [DocNow/twarc#547]
As you know I am working in the analysis of links in tweets gathered with twarc in `json` files (https://github.com/DocNow/twarc/wiki/Analyzing-links-in-tweets). I am having some problems reading directly from json

I've used a quick trick to make it possible:
I use a `head(n)` to only use the first `n` tweets:
```
fn <- "file_flatten.json"
wrongjson <- paste(readLines(fn) %>% head(100000), collapse = "")
```
If I don't filter by the first lines I get this error:
```
Error in gsub("\\}\\s*\\{", "},{", wrongjson) : 
  'Calloc' could not allocate memory (18446744071562067968 of 1 bytes)
```

Then I build, again, the (unflatten) json file:
```
if (grepl("\\}\\s*\\{", wrongjson)) {
  wrongjson <- paste0("[", gsub("\\}\\s*\\{", "},{", wrongjson), "]")
}
json <- jsonlite::fromJSON(wrongjson, simplifyDataFrame = FALSE)
```

If I try to use the the original json file, unflatten I get this error. This only happens for big files:
```
json <- jsonlite::fromJSON( "file.json", simplifyDataFrame = FALSE)
Error in parse_con(txt, bigint_as_char) : parse error: trailing garbage
          2021-04-25T15:34:51+00:00"}} {"possibly_sensitive": false, "
                     (right here) ------^
```

If I look what is going on in the `json` file I see.

What I see in a small search file is a good formatted `json` file:

```
{
 "data": [
  {
  "text": "text of tweet",
  "referenced_tweets": [...],
  "lang": "es",
  "public_metrics": {...},
  ...
  },
  { ... another tweet ... },
  { ... another tweet ... }
 ],
 "includes": {
  "users": [...],
  "tweets": [
   {
     "text": "text of tweet",
     "lang": "es",
     ...
   },
   { ... another tweet ... },
   { ... another tweet ... }
  ],
  "media": [ ...]
 },
 "meta": {...},
 "__twarc": {...},
}
```

What I see in a big search json file are these 3 lines, which seems weird, and might be causing the error, it seems more like a `jsonl`:

```
{
 "data": [...],
 "includes": {...},
 "errors"; [...],
 "meta": {...},
 "__twarc": {...}
}
{
 "data": [...],
 "includes": {...},
 "meta": {...},
 "__twarc": {...}
}
{
 "data": [...],
 "includes": {...},
 "meta": {...},
 "__twarc": {...}
}
```

The first line, when the `json` is propperly formated goes from 1 to 12,397 line, the second from 12,898 to 23,921 and the third section 23,922 to 26,520.

What is the expected format of the `json` original file after `twarc2 search word > file.json`?

**Comment by SamHames** [comment]
The data format is one page of results per line (so yes it is jsonl) - this
is exactly the json returned when you call the Twitter API.

How many tweets are you working with? Loading the Json into memory is going
to take much more space than the file on disk, because there is overhead
for representing each piece of data within the structure.

What you probably want to do is parse the json one row at a time and
extract only the fields you need into a structured dataframe.

**Comment by numeroteca** [comment]
So, the result of a search file is a `jsonl` with only 1 line (that has many tweets in it) and inserts new lines if more tweets are gathered? 

If I can understand how the json is built I can iterate and parse the json. Maybe it is documented somewhere and I haven't seen it.

I am working with 200,000-300,000 tweets files, they could be bigger.

**Comment by SamHames** [comment]
To make things more concrete, sorry if I wasn't clear earlier:

The result of (almost) all twarc CLI operations is a jsonl file with one
line per api call response. Each response (line in the file) is a complete
Json document containing the data for a number of tweets. The tweets
themselves are the array under the 'data' key in each response document. So
to iterate through the file, you retrieve the data key for that line, then
iterate through that array.

You can check out the code in that does flattening in twarc, and also in
the twarc-csv plugin for more examples (I think the ensure_flattened
function is what you want in twarc/expansions.py, but I'm writing from my
phone).

As a side note a colleague has also started some work on processing the
tweets into an Sqlite database so you can just write a query to bring out
what you need.

**Comment by igorbrigadir** [comment]
Was the data collected on the same OS as this analysis is happening?

I wonder if it's something else - if it's multiple requests / tweets per line that's an error - i think twarc inserts `\n` newline characters as newlines - but if you use Windows, you may see those multiple lines as a single line because windows expects `\r\n` (2 characters) that mark a newline.

The solution is to either convert the newlines in the file, or explicitly treat `\n` as a newline in whatever script you're running (i'm not sure how to do this in R)

**Comment by numeroteca** [comment]
I am using Linux (unbuntu). I create and analyze everything in the same OS.

Not sure I understand well what you say regarding new lines. I still don't get why there are multiple lines in the json file.

**Comment by SamHames** [comment]
I'm not quite sure what you're asking about the data format/newlines - both of the examples you pasted look the same to me? The small example and the large example both have the same top level keys, the small example just expands to show keys in the next level down. That data format is exactly what the Twitter API returns - each block including the "data" top level key is an API response.

How are you looking at the JSON? If you're using a JSON specific tool it is likely to be pretty printing the whitespace for you - the raw JSON is much uglier.

**Comment by edsu** [comment]
I'm kind of confused about what this ticket is about.

**Comment by SamHames** [comment]
I'm going to close this issue - from everything you've shown it looks like you have valid Twitter JSON produced by twarc, and the crux of your question is really about data analysis in R, which is not really in scope for the twarc tool itself. I think you would get more helpful responses in an R specific venue.

If you do dig into it and find something more suggesting it's a twarc specific problem feel free to reopen :)
