### ISSUE TITLE
Point Radius search verification

### ISSUE THREAD

**Issue by joseph-allen** [DocNow/twarc#557]
Hello all, I am trying to scrape tweets from London.

I make the following query:
```
twarc2 search --archive --limit 100 --start-time "2019-01-04" --end-time "2019-01-06" "(vegan OR vegetarian OR plant-based) point_radius:[-0.127758 51.507351 5mi]" 100VeganLondonJan2019.jsonl
```

Is there a way I can verify these results? When I look at the users author.location I would say about 20% seem to at least be self-defined as London or at least the UK.

The few with geolocation vary across the UK and US.

**Comment by joseph-allen** [comment]
While it says unsupported, changing the point-radius does change the number of tweets I get back from different areas?

**Comment by joseph-allen** [comment]
Apologies I didn't answer the question, what can I do to confirm that those tweets are actually from near London, since most of them contain no geo data, and only some of them even self-report a location near London in their author.location

**Comment by SamHames** [comment]
Can you try again with the query in your original question with the
brackets?

The data you shared was collected with a different query - the brackets are
critical as without them you end up with a query that implicitly is like "a
OR b OR (c and d)". The Twitter API applies the implicit AND first.
