### ISSUE TITLE
Twarc2 CLI commands aren't visible in the documentation structure.

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#570]
The CLI level headings don't show up in the nav for twarc2 https://twarc-project.readthedocs.io/en/latest/twarc2_en_us/ , it just ends at the handwritten documentation. 

This means that commands in the CLI but don't have non-cli level docs are invisible - for example the compliance-job functionality can't be found by scanning the section titles.

**Comment by igorbrigadir** [comment]
Took a try or two but the issue was multiple `#` h1  in there, and missing `:depth: 1` mkdocs setting
