### ISSUE TITLE
Support new Lists endpoints

### ISSUE THREAD

**Issue by igorbrigadir** [DocNow/twarc#572]
The v2 API is officially launched now and has endpoints for reading Lists, which are important to have: 

https://twittercommunity.com/t/announcing-list-lookup-endpoints-for-the-twitter-api-v2/161965

https://developer.twitter.com/en/docs/twitter-api/lists/list-lookup/introduction

**Comment by igorbrigadir** [comment]
Some preliminary ideas on `twarc2 lists` command:

A user on twitter can either create and curate a list, or follow some other public list. I when twarc gets lists of a user, it should get both the "owned" lists and "subscribed" lists as this is more expected, given the lists page of a user (it's a mix of created and followed) eg https://twitter.com/recsyslabs/lists

```
twarc2 lists list [user_id] 
```

should call both: https://developer.twitter.com/en/docs/twitter-api/lists/list-lookup/api-reference/get-users-id-owned_lists and https://developer.twitter.com/en/docs/twitter-api/lists/list-follows/api-reference/get-users-id-followed_lists 

We can also have 

```
twarc2 lists owned [user_id] 
```

```
twarc2 lists followed [user_id] 
```

and 

```
twarc2 lists pinned [user_id]
```

https://developer.twitter.com/en/docs/twitter-api/lists/pinned-lists/api-reference/get-users-id-pinned_lists

separately too. May be better than having a command line switch in `twarc2 lists list` ? 

```
twarc2 lists lookup [list_id]
```

to call list lookup on an individual list https://developer.twitter.com/en/docs/twitter-api/lists/list-lookup/api-reference/get-lists-id

To get followers of a list,

```
twarc2 lists followers [list_id]
```

to call https://developer.twitter.com/en/docs/twitter-api/lists/list-follows/api-reference/get-lists-id-followers

```
twarc2 lists members [list_id]
```

for the members https://developer.twitter.com/en/docs/twitter-api/lists/list-members/api-reference/get-lists-id-members

and 

```
twarc2 lists memberships [list_id]
```

for https://developer.twitter.com/en/docs/twitter-api/lists/list-members/api-reference/get-users-id-list_memberships

and finally 

```
twarc2 lists tweets [list_id] 
```

that calls https://developer.twitter.com/en/docs/twitter-api/lists/list-tweets/api-reference/get-lists-id-tweets

I think grouping command into `twarc2 lists` is better than making them `twarc2 list-members` and `twarc2 lists-tweets` for example, but i'm not strongly attached to this either.

**Comment by edsu** [comment]
Thanks for this detailed write up @igorbrigadir! I agree about grouping within a `lists` subcommand being preferable to `list-members` etc. I did find myself wondering if `lists all` would fit better with `lists owned` and `lists followed` than `lists list`. But I could get used to it :-)

**Comment by igorbrigadir** [comment]
Oh, yeah i kinda like `lists all` more than `lists list`

**Comment by PoliTwit1984** [comment]
But there will be an option to just search one list, correct?

**Comment by igorbrigadir** [comment]
> But there will be an option to just search one list, correct?

What do you mean exactly? 

Unfortunately there's no endpoint to search for lists, you can only get a set of them based on a user ID, and then look up the IDs individually.

Speaking of which, I think these commands should also take a text file of IDs as input too, for batch lookups ( the APIs don't have batch lookups but we can definitely make things easier) so you could have a text file with 1 user ID per line, and we would retrieve all lists for each user, with `twarc2 lists users.txt output.json` for example

**Comment by PoliTwit1984** [comment]
I'm not sure how it is implement but in tweepy they have an option to do this....
list_id = 673888992464
response = client.get_list_tweets(list_id, max_results=100)

where list id is one list I've created that has 150 members in it. Not sure how they implemented it under the hood. I haven't looked at the source code.

**Comment by PoliTwit1984** [comment]
Got it, thank you! :)
