### ISSUE TITLE
Application suspension notice

### ISSUE THREAD

**Issue by cxyccc** [DocNow/twarc#579]
Hello! I just created a new twitter v2 app and used the _conversation_ function that twarc2 provided, then my app was suspended! The command I used is _twarc2 conversation 266031293945503744 > conversation.jsonl_. Anybody knows why? How to avoid it? Many thanks!!!

**Comment by SamHames** [comment]
That shouldn't happen with normal usage of twarc.

1. Have you been using that Twitter app with any other tools, or is that
conversation command the first thing you've done with a new app?
2. In the directory you ran the twarc command there should be a twarc.log
file - if twarc has done anything weird it will be logged there.

**Comment by cxyccc** [comment]
Thank you for your reply! I also tried some simple tweepy codes with my newly created app yesterday. I used twarc2 with proxy, maybe the problem is here? But I used twarc(v1) with proxy for many times, nothing abnormal happened.

**Comment by cxyccc** [comment]
I noticed that in the twarc.log, 
_caught requests exception: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/recent?expansions=author_id%2Cin_reply_to_user_id%2Creferenced_tweets.id%2Creferenced_tweets.id.author_id%2Centities.mentions.username%2Cattachments.poll_ids%2Cattachments.media_keys%2Cgeo.place_id&tweet.fields=attachments%2Cauthor_id%2Ccontext_annotations%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpublic_metrics%2Ctext%2Cpossibly_sensitive%2Creferenced_tweets%2Creply_settings%2Csource%2Cwithheld&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Cpublic_metrics%2Curl%2Cusername%2Cverified%2Cwithheld&media.fields=alt_text%2Cduration_ms%2Cheight%2Cmedia_key%2Cpreview_image_url%2Ctype%2Curl%2Cwidth%2Cpublic_metrics&poll.fields=duration_minutes%2Cend_datetime%2Cid%2Coptions%2Cvoting_status&place.fields=contained_within%2Ccountry%2Ccountry_code%2Cfull_name%2Cgeo%2Cid%2Cname%2Cplace_type&query=conversation_id%3A1461956070167904258&max_results=100 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))_
occured many times. 

Apart from this, there are no other abnormal issues.

**Comment by edsu** [comment]
You are the first person to have reported this type of issue. However the logic for waiting between requests did change slightly in v2.8.2. Is that what you are using?
It would be useful to see the timing in full log.

Also, is it possible that others were using the proxy as well? Is it an open proxy or is it one you are running? It's possible that the security measures of the v2 api platform differ from v1. @igorbrigadir have you seen any reports of similar issues?

**Comment by edsu** [comment]
Also, just out of curiosity, how do you tell  twarc to talk to a proxy instead of directly to the API?

**Comment by cxyccc** [comment]
I just tried the _conversation_ function like this: _twarc2 conversation 266031293945503744 > conversation.jsonl_. I recevied correct results sometimes.

And the tweepy code I tried is as follows:
```
import tweepy

bearer_token = 'xxxx'
client = tweepy.Client(bearer_token=bearer_token)
tweets_fields_list = ['created_at','id','text']
expansions_list = ['author_id']

for response in tweepy.Paginator(client.search_all_tweets, query="conversation_id:xxx -from:xxx", tweet_fields=tweets_fields_list, expansions=expansions_list,
                                 max_results=5, limit=2):

    print("一共有：" + str(len(response.data)) + " 条回复")
    for tweet in response.data:
        print("-------------分割线----------------")
        print(tweet.author_id,tweet.id,tweet.created_at,tweet.text)
```
But I received a status code of 401/403 and failed.

What is the waiting logic you said is? It seems that I didn't use it.

**Comment by cxyccc** [comment]
Yes, I share the proxy with someone else. But he never uses something like twarc and twitter api. Maybe the exception _HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url_ mentioned above is caused by shared proxy and speed limit, i.e. network error. But I think its not the reason why twitter suspend my app. Or, maybe unfortunately I used the ip address banned by twitter?

**Comment by cxyccc** [comment]
I use proxy when I visiting foreign websites (like twitter), that's a smart mode. And I use twarc in cmd. Sorry I don't know the details about twarc talking to proxy.

**Comment by cxyccc** [comment]
I noticed that a similar issue on the Internet. Someone used twarc and his app was suspended. [https://twittercommunity.com/t/application-suspension-notice/155902](url)

Many thanks.

**Comment by SamHames** [comment]
I don't think this is a twarc issue, it looks like a new twitter dev
account being flagged issue. I'd go through the appeal process linked in
the thread you shared. If you're still having trouble after that, then we
can dive into more investigation.

@edsu - from memory requests picks up proxy details from the environment,
using standard environment variables.

**Comment by edsu** [comment]
Re: your question above there is no need to handle the wait times and rate limiting yourself. This is something that twarc does for you.

Depending on what proxy you are using, and who else is using it, it could certainly end up on a block list, and your app getting blocked. As pointed out in that thread by @igorbrigadir your best bet at this point is to [fill out the form](https://help.twitter.com/en/forms/platform/suspended-or-restricted).

I just ran `warc2 conversation 266031293945503744 > conversation.jsonl` and it ran without a problem. I haven't been blocked, or at least not yet. It only brought back two tweets because there have only been that many replies to that tweet in the last weeks (what you get unless you have Academic Product Track access to the full archive).

**Comment by edsu** [comment]
Wow yes, I had no idea that requests would honor HTTP_PROXY and HTTPS_PROXY in the environment. Thanks for that @SamHames!

https://docs.python-requests.org/en/latest/user/advanced/?highlight=proxy#proxies

This might be one for the twarc docs. @cxyccc sorry we can't really help you further.

**Comment by cxyccc** [comment]
Thank you for your help!!! @SamHames @edsu I will ask for Twitter's help and try more.
