### ISSUE TITLE
Total tweet count per day

### ISSUE THREAD

**Issue by ANN-zhi** [DocNow/twarc#583]
Hi, I'm new to twarc and I hope to know if there’s any way to get the total tweet count per day?
 (To retrieve counts for all the tweets per day without setting any keyword for query in the full archive, using the /search/all endpoint)
Thanks a lot!

**Comment by edsu** [comment]
The [counts API endpoint](https://developer.twitter.com/en/docs/twitter-api/tweets/counts/api-reference/get-tweets-counts-all) requires a query. So no, this isn't possible, unless you can search for something that can act as a proxy for the overall traffic. Feel free to join us [in Slack](https://bit.ly/docnow-slack) if you want to trade ideas or chat about things.

**Comment by ANN-zhi** [comment]
Thank you so much!!!
