### ISSUE TITLE
Add a user-agent for twarc

### ISSUE THREAD

**Issue by sparack** [DocNow/twarc#591]
Would be nice if there was a custom user-agent for Twarc (one for v1.1 calls and another for v2 calls)

**Comment by igorbrigadir** [comment]
I added #592 

> one for v1.1 calls and another for v2 calls

come to think of it.. maybe `API/v1.1` / `API/v2`  isn't necessary at all? On twitter's end that should be implicit from the requested URL? But if it simplifies stuff there's no harm in keeping it. I was going to add something to differentiate command line usage from script / library usage somehow but i don't know if there's a reliable way to do that so i left it out.

**Comment by edsu** [comment]
This was just released as twarc v2.9.2 -- thanks for the elegant and simple fix for this @igorbrigadir!
