### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#594]
I created this Twarc logo (for a refresh to docnow.io) and was wondering what other people thought of it. Would it be ok to inject into some of our twarc documentation if there are easy ways to do that?

![twarc](https://user-images.githubusercontent.com/33829/152559139-a5d100c6-7295-4006-8f43-400ef6f748c6.svg)

**Comment by igorbrigadir** [comment]
Yes! The only thing that i'd mess with is the alignment of `twarc` text with the box, it's more left aligned right now when it feels like it should be centered underneath if that makes sense? Otherwise i love it!

**Comment by edsu** [comment]
Ok I switched the font and moved it around a bit more. Does this look any better, or am I on the wrong track?

![twarc](https://user-images.githubusercontent.com/33829/152601791-82e7a6d2-3741-46dd-ae6a-df081fdba29d.svg)

**Comment by igorbrigadir** [comment]
Yes! That's much better

**Comment by SamHames** [comment]
I don't know how I missed this, but I just wanted to say it looks good!
