### ISSUE TITLE
twarc2 lookup-user command to retrieve a single user profile

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#598]
Sometimes, you just need to do a quick lookup to go from a single username to a single user_id. It would be handy in these cases to be able to do, rather than squeeze this specific usecase into the `users` functionality:

`twarc2 lookup-user {username/user_id}` -> single user_profile

or possible even
`twarc2 lookup-user-id username` -> user_id

**Comment by igorbrigadir** [comment]
We have `twarc2 tweet 1234`, so I guess it should be fine to also put in `twarc2 user 1234`?

**Comment by SamHames** [comment]
I have absolutely no idea why I didn't think of `user`, that fits so much better.
