### ISSUE TITLE
One strategy to do reiterative searches: sharing ideas and doubts

### ISSUE THREAD

**Issue by numeroteca** [DocNow/twarc#600]
This is an issue to share my strategy for downloading tweets and set a pair of questions.

Let's say I am following a political scandal in Twitter. I hope to get as many tweets as possible to analyze them later.
This is the strategy that I am following. What would would be your advice?

1. Make different searches queries with `twarc2 counts` for a concrete period of time. 
2. Compare the results and pick the one with more tweets (be cautious not to take too common words, make searches for them by themselves to see). 
3. Download the tweets with `twarc2 search` with the selected query. Example: `word1 OR word2 OR word3 word4 OR @twitteruser`. If I am  within 7 days, I don't have to spend my 10 000 000 tweets/month credit of the academic track.
4. Review the downloaded tweets. In my case: see the RT network (with Gephi) to find weird communities and read the most common retweets. That can guide to remove certain words. In my case `word2` resulted in many false positives.
5. Download the tweets without `word2`, but adding `word5` and `word6`, which should have been included. Example: `word1 OR word3 word4 OR @twitteruser OR word5 OR word6`. This would result in downloading **again** most of the tweets

Other possibility would be, for point 5., to download only tweets with `word5` OR `word6` and then merge the results with the search of point 3., but remove from those tweets the ones with `word2`. Which is problematic, as removing tweets with `word2` can result in removing tweets with `word1`.
 
Questions:
- Is there a way to remove tweets with a search (a filter) from a twarc2 search  downloaded `jsonl` file?
- Is there a way for merging downloaded `jsonl` files?

**Comment by edsu** [comment]
[search/recent](https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent) is subject to the same app level Tweet cap.

**Comment by edsu** [comment]
The downside to not collecting in real time is you will miss out on transient tweets: tweets that are sent, retweeted, commented on, and then deleted in a short period of time. Whether this matters or not probably depends on the type of research you are doing, but a political scandal sounds like it could be one of them.

**Comment by igorbrigadir** [comment]
Just going over some old issues:

> Is there a way to remove tweets with a search (a filter) from a twarc2 search downloaded jsonl file?

Currently no, i think this is something best suited for a plugin maybe, or custom code.

> Is there a way for merging downloaded jsonl files? 

Not in twarc, but in command line, there usually is a good way to merge files, for example, with `cat` and output redirects `>` and pipes etc. Just be careful with the format: twarc expects 1 json object per line, so it's important to make sure you don't merge 2 files and end up with 2 json objects on the same line.

Feel free to open up a new issue for the plugins! This issue could be turned into a good docs paragraph later i think!
