### ISSUE TITLE
Release of 2.9.3 on pip

### ISSUE THREAD

**Issue by DavidHernandez** [DocNow/twarc#601]
I see that GitHub and the Twarc doc page has already the information of the 2.9.3 release. But in the pipy site this version is not available, just the 2.9.2. If this version is ready, could it be released for pip too?

**Comment by SamHames** [comment]
Oops, sorry, that was my mistake. It should have been pushed automatically.

**Comment by SamHames** [comment]
Okay - I've fixed this now, but to avoid rewriting the past to keep the metadata consistent for the release what should have been in 2.9.3 has been release to PyPI as 2.9.4.

**Comment by DavidHernandez** [comment]
Thank you for the quick response @SamHames!
