### ISSUE TITLE
`twarc2 counts --archive` returning incomplete results

### ISSUE THREAD

**Issue by melaniewalsh** [DocNow/twarc#602]
I'm running `twarc2 counts` with the Academic Track of the Twitter API, and for some reason it's returning incomplete results (only going back a few years) with the following query:

```
!twarc2 counts "(\"this is how\" \"not with a\" but) OR (\"not with a bang\") OR (\"not with a\" \"but a whimper\") OR (\"not with a\" \"but with a whimper\") OR (\"this is the way\" \"not with a\" but)" --archive --granularity day --csv > tweets.csv
```
(For reference I'm doing a project about T.S. Eliot's "not with a bang but a whimper.")

When I check twarc.log, I can see that an empty page is returned, which is interpreted as the end of the search:
```
2022-02-28 15:59:21,700 INFO Retrieved an empty page of results
2022-02-28 15:59:21,700 INFO No more results for search.
```

**Comment by igorbrigadir** [comment]
I think one problem may be the huge time range - If no `--start-time` and `--end-time` is set, twarc2 assumes it's "from the very first tweet ever, up to now" so from `2006-03-21`. Maybe it will work slightly better with a more restricted time range?

**Comment by SamHames** [comment]
If we can find a repeatable example it might be worth taking a look to confirm whether there are any matches after the empty page of results. If there are, it's definitely a bit weird of the Twitter API to have this behaviour.

I'll take a dig through the results of that query.

**Comment by SamHames** [comment]
Oh this is definitely a bug in twarc (possibly exarcebating a Twitter API oddity?) - that search gives an empty page of results in 2020, with obviously many more results to come after that.

**Comment by SamHames** [comment]
Thanks for sharing the exact query, I'll see what I can do about this.

**Comment by SamHames** [comment]
Hmmmmmm, I take it back, here is an example of the response from the Twitter API that causes Twarc to stop. 

> {"meta": {"total_tweet_count": 0}, "__twarc": {"url": "https://api.twitter.com/2/tweets/counts/all?start_time=2006-03-21T00%3A00%3A00%2B00%3A00&end_time=2020-01-01T00%3A00%3A00%2B00%3A00&query=%28%22this+is+how%22+%22not+with+a%22+but%29+OR+%28%22not+with+a+bang%22%29+OR+%28%22not+with+a%22+%22but+a+whimper%22%29+OR+%28%22not+with+a%22+%22but+with+a+whimper%22%29+OR+%28%22this+is+the+way%22+%22not+with+a%22+but%29&granularity=day&next_token=1jzu9lk96azp0b3x7888hrpuraspczgubxg0gxk58l8d", "version": "2.9.4", "retrieved_at": "2022-03-04T05:41:09+00:00"}}

I think stopping here is correct as there's no `next_token` to continue pagination. To me this looks more like an API bug or undocumented limitation. 

In principle I think we can work around this by comparing the last retrieved `start-time` to the desired `start-time` and restarting the counts from that point. I'm investigating what this looks like at the moment.

**Comment by SamHames** [comment]
I did put a workaround together in the linked #604 - it turned out to be easier than I thought it was going to be, as long as start-time is specified in the query we can check if we've reached that point or not. 

@melaniewalsh - you're welcome to test against that branch, or if it would be easier for you I can push a pre-release to PyPI on Monday.

**Comment by edsu** [comment]
I greatly appreciate the API detective work here @melaniewalsh & @SamHames -- we all benefit from your efforts here.

I tried running @melaniewalsh's query above and it works now 🥳 

```
(twarc) ➜  twarc git:(workaround_counts_API_zero_count) ✗ twarc2 counts "(\"this is how\" \"not with a\" but) OR (\"not with a bang\") OR (\"not with a\" \"but a whimper\") OR (\"not with a\" \"but with a whimper\") OR (\"this is the way\" \"not with a\" but)" --archive --granularity day --csv tweets.csv
100%|█████████████████| Processed 15 years/15 years [16:33<00:00, 354018 tweets total ]
```

**Comment by edsu** [comment]
@melaniewalsh please `pip install --upgrade twarc` and see if v2.9.5 helps!
