### ISSUE TITLE
redundant connection for sample

### ISSUE THREAD

**Issue by JanaLasser** [DocNow/twarc#603]
I am looking to set up a pipeline to ingest data from the sampled stream of the v2 API. Reading Twitter's [documentation](https://developer.twitter.com/en/docs/twitter-api/tweets/volume-streams/integrate/recovery-and-redundancy-features), it seems to be possible to open two redundant connections to the sampled stream by "simply connecting to the same URL used for the primary connection".

I was wondering whether there is functionality to do this in twarc or whether I would have to go back to compose the API request myself.

**Comment by igorbrigadir** [comment]
According to https://developer.twitter.com/en/docs/twitter-api/tweets/volume-streams/integrate/recovery-and-redundancy-features

> Sampled stream currently only allows those with [Academic Research access](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-level) to connect to up to two redundant connections. To use a redundant stream, simply connect to the same URL used for your primary connection.

There is no need to make any changes to twarc to support this, you would install and configure twarc on one server, start the stream, and then install and configure twarc on a different redundant server, and start the stream exactly the same way. (I don't see any point in running a redundant stream on the same physical machine, but you could do this - running twarc twice)

This applies both to Sample and Filter streams if you have Academic Access. If you don't have academic access, the older connection is dropped as far as i know.

Hope that helps!

**Comment by JanaLasser** [comment]
Ah perfect - thanks a lot, that's what I wanted to know. I am envisioning the two-server setup you have described, to ensure data completeness in case of an internet or power outage of one of the servers.

**Comment by edsu** [comment]
Thanks for raising this @JanaLasser and for the help @igorbrigadir. I wonder if this might be a good pattern to describe in the docs?
