### ISSUE TITLE
Twarc connection with Server MkDocs

### ISSUE THREAD

**Issue by agrecasens** [DocNow/twarc#607]
Hello! You can run Twarc successfully via the terminal.
What I don't understand is the MkDocs server, create the site as indicated by the server and install Twarc inside the directory. What function would the server fulfill? Thanks

**Comment by edsu** [comment]
The mkdocs configuration is what is used to build https://twarc-project.readthedocs.io/en/latest/ you can ignore it unless you want to help us document twarc!
