### ISSUE TITLE
Endpoints not implemented

### ISSUE THREAD

**Issue by DavidHernandez** [DocNow/twarc#609]
Hi!

I am mentoring some people and as a way to learn Python and improve their CVs, I told them they could contribute to this project. One of them already submitted a PR that was accepted: #605 

In order to make it easier to find what endpoints are not yet implemented or not being worked on already it will be handy to have a list of missing implementations. This also could be an entry point to new contributors. We could create some kind of guide of things to take into consideration.

Does that sound good to you? Could anyone provide a list of missing endpoints?

Thanks!

**Comment by igorbrigadir** [comment]
Sure, this sounds great! All this is just my own opinion, so I'm just speaking for myself as a contributor, not on behalf of anything:

I don't think we're missing any endpoints now, but making sure would also be a very helpful contribution, as comments in #608 issue for example. We were mostly looking at implementing endpoints that allow you to read and archive public data, not post tweets or modify profiles or lists etc - this is a good doc for scope: https://github.com/DocNow/twarc/wiki/twarc2-Design#design-principles-for-twarc2 it's a bit old now, but it was the plan for twarc2.

I think there are some outstanding issues that would be good for newcomers. I'll try to mark those as "good first issue" https://github.com/DocNow/twarc/labels/good%20first%20issue 

We are definitely missing tests too - the client API I think has a bunch, but the command line interface lacks tests currently.

Also, plugins! There are other repositories with twarc2 plugins that also could have some great opportunities for new contributors https://twarc-project.readthedocs.io/en/latest/plugins/ there's a few links to the repos there, or, if you find some good functionality in the old https://github.com/DocNow/twarc/tree/main/utils set of scripts, making a new twarc2 compatible plugin for those would also be an excellent contribution for someone. (The scripts in utils all work on the old v1 format, but we would love to have v2 API format plugins for twarc2 work)

Hope that helps!

**Comment by edsu** [comment]
I agree with what @igorbrigadir said above. Plugins that do things with the collected data would be a great way to contribute. Another would be to contribute [wiki](https://github.com/DocNow/twarc/wiki) pages for doing interesting things (recipes) with Twitter data. We also had some nice [translations](https://twarc-project.readthedocs.io/en/latest/twarc1_es_mx/) of the docs for v1 that we do not yet have for v2. 

In terms of endpoints one thing to keep in mind about twarc's [design](https://github.com/DocNow/twarc/wiki/twarc2-Design#design-principles-for-twarc2) is that it is really meant for reading Twitter data. So endpoints that mutate the state of Twitter resources are out of scope for twarc.

**Comment by edsu** [comment]
Also if there are missing endpoints that need to be implemented I suggest that we create individual github issue tickets. So I'm going to close this.
