### ISSUE TITLE
Bias in historical Twitter research

### ISSUE THREAD

**Issue by numeroteca** [DocNow/twarc#616]
I’d like to know if you know of existing literature of the bias introduced with the extraction of Twitter data years after an event has occurred. I am thinking of studying 2013 topics and I wonder if someone has already made this kind of comparison: live stream data  vs. current academic track access.
Thanks!

**Comment by igorbrigadir** [comment]
Yes! A lot of deletions happen, here are a few good papers on this: https://github.com/igorbrigadir/tweet-delete/blob/master/references/related-work.md

**Comment by edsu** [comment]
This is a helpful list, thanks for the pointer @igorbrigadir!
