### ISSUE TITLE
JSON Files - Retweeted-By & Liking-Users

### ISSUE THREAD

**Issue by willturn001** [DocNow/twarc#622]
The JSON returned from the Retweeted-By and Liking-Users endpoints is invalid and return multiple json arrays

**Comment by SamHames** [comment]
Can you share an example of the failures you're seeing, including the raw
data?

**Comment by willturn001** [comment]
For example, I want to take the users who liked this tweet: https://twitter.com/GreekAnalyst/status/1510222487941890050 
twarc2 liking-users 1510222487941890050 likingusersexample.json
Attached is the output in a txt file
[likingusersexample.txt](https://github.com/DocNow/twarc/files/8404231/likingusersexample.txt)
.

**Comment by SamHames** [comment]
That is the correct format - there's one json object per line, corresponding to a single page of results as returned by the Twitter API. This is similar to the output you'd see from the twarc2 search or twarc2 timeline commands. 

If you want to parse the data, you'll need to iterate through the lines in the file and calling `json.loads` once per line.
