### ISSUE TITLE
ensure_flattened does not handle responses that include "errors" but not "data" and "includes"

### ISSUE THREAD

**Issue by SamHames** [DocNow/twarc#627]
For example in #626, if you lookup an account that doesn't exist anymore, you will get a response that only has an error key, which is currently passed through as is because it checks for "data" and "includes" keys only. I think the correct behaviour in this key is an empty response, as an API response with only errors has no content.

**Comment by edsu** [comment]
@SamHames does [this test](https://github.com/DocNow/twarc/blob/flattened-errors/test_twarc2.py#L512-L518) reflect how you think it should behave?
