### ISSUE TITLE
Missing progress Bar?

### ISSUE THREAD

**Issue by HarryHe11** [DocNow/twarc#635]
<img width="620" alt="1651852094(1)" src="https://user-images.githubusercontent.com/68176557/167167658-521b95b8-985e-4e90-91d2-e8b50753d794.png">
Thank you so much for this helpful tool. But there is an issue that I didn't use "hide_progress", but the progress bar is missing. (It was shown when I run the command line for the first time) How can I fix it?

**Comment by edsu** [comment]
The progress bar is only displayed if you instruct twarc to write to a file, instead of using stdout redirection as you did there. Try this instead:

```
twarc2 conversation --archive 266031293945503744 re.jsonl
```
