### ISSUE TITLE
twarc2 conversations output?

### ISSUE THREAD

**Issue by HarryHe11** [DocNow/twarc#636]
I have been trying to download conversations using the twarc2 conversations functionality and supplying a list of 2000 conversation IDs. I have academic research API access. This is the command I used:

twarc2 conversations --archive conversation_ids.txt results.jsonl

Although I successfully got 44,000+ tweets, I found that:
1. there are only 92 unique conversation ids in the results. jsonl (by checking the conversation id field in a CSV file)
2. the source tweet (the tweets that start conversations, whose id ==conversation id) do not exist in the results.jsonl

Why would this happen?  

Thank you so much if you could help me to understand how this command work!

**Comment by edsu** [comment]
@HarryHe11 can you identify a tweet id in `conversation_ids.txt` which has a thread when you look at it in Twitter, and which is not present in your output? Otherwise it is difficult for us to say what is going on here  without your input data.

If you look at how this is implemented in twarc it is doing a search, e.g. `conversation_id:123456789`. It is possible that there is a reason why if would not be searchable (shadow banning).

**Comment by HarryHe11** [comment]
Dear Sir
Here are three example ids in conversation_ids.txt ['1460244999090626563', '1401646588926251013', '1370670466722000896',] which I didn't receive any of their replies. And ['1436019603251994632', '1417844715047763968', '1419298709360324610', '1426933290058096648'] are examples of those tweets which I successfully got replies.

To construct the conversation_ids.txt, I first got about a million COVID-related tweets by searching hashtags. Then I use the set(data.conversation_ids.to_list()) to get a set of conversation_ids. At last, I randomly sampled 2000 of them, and write them into the conversation_ids.txt file. 

I am not sure whether the process would result in some un-searchable conversation ids. But I think the shadow banning would not lead to the majority (in my case 1908/2000) of conversations missing.

Thank you!

**Comment by HarryHe11** [comment]
@edsu

**Comment by edsu** [comment]
Just looking at the first one, there is no conversation at: https://twitter.com/Jean__Fisch/status/1401646588926251013

**Comment by HarryHe11** [comment]
Oh, I made a few more tests and now I can understand why this happen:
1. for those tweets that didn't receive any replies, their tweet_ids were recorded in the field "conversation_ids", but there are actually no conversations under those tweets. 

2. the twarc2 conversation command would only return replies (without returning the source_tweets), to reconstruct a conversation thread, source_tweets need to be searched independently.

3. therefore, in my case (or using a similar way to construct a conversation_ids.txt), only 92 tweets actually have a conversation in my conversation_ids.txt, so the rest of them will be ignored.

Thank you @edsu  so much for your help and your excellent twarc tool! Wish you have a nice day!

**Comment by edsu** [comment]
I'm glad I could help you understand your data better!
