### ISSUE TITLE
Any easy way to use this code as a python client? 

### ISSUE THREAD

**Issue by ntorba** [DocNow/twarc#642]
Hey Twarc team! 

Sorry if this answer is already available and I can't find it. 

Is there a good way to use this project as a python client instead of from the command line? It would be great to be able to call these functions from my python code instead of at the command line. 

Thanks for any help!

**Comment by edsu** [comment]
Twitter have published some tutorials some of which use twarc as a library:

https://github.com/twitterdev/getting-started-with-the-twitter-api-v2-for-academic-research/blob/main/modules/6a-labs-code-academic-python.md

You might also want to take a look at the [unit tests](https://github.com/DocNow/twarc/blob/main/test_twarc2.py), which use it as a library against live Twitter.

The documentation also provides some guidance:

https://twarc-project.readthedocs.io/en/latest/api/client2/

**Comment by ntorba** [comment]
@edsu this is exactly what I was hoping for. Thank you!!

**Comment by edsu** [comment]
Great. Please keep asking questions either here or on [Slack](https://bit.ly/docnow-slack).
