### ISSUE TITLE
Having a problem installing 

### ISSUE THREAD

**Issue by t-yamane-jp** [DocNow/twarc#651]
I am a frequent user of R and now trying to learn python because I realized that twarc can be very helpful to collect old twitter records. I first tried academictwitteR, R package, but did not work well to collect big twitter data.

I have been working for a week to figure out how to use python with Rstudio. A lot of install and uninstall  and download, not I finally figure out how, but installing twarc does not work. I get the following error message. I am hoping that somebody can help me with this problem. Thank you very much.
```
library(reticulate)
reticulate::conda_install(packages = "twarc==2.10.3", envname = "H:\\sync\\miniconda\\envs\\r-reticulate")
+ "H:/sync/miniconda/condabin/conda.bat" "install" "--yes" "--prefix" "H:/sync/miniconda/envs/r-reticulate" "-c" "conda-forge" "twarc==2.10.3"
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - twarc==2.10.3

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Error: one or more Python packages failed to install [error code 1]
```
I also tried the below, but I basically got the same results.

`reticulate::py_install("twarc", envname = "H:/sync/miniconda/envs/r-reticulate")`

my environment: 
```
> reticulate::py_config()
python:         H:/sync/miniconda/envs/r-reticulate/python.exe
libpython:      H:/sync/miniconda/envs/r-reticulate/python38.dll
pythonhome:     H:/sync/miniconda/envs/r-reticulate
version:        3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:45) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          H:/sync/miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.23.1

NOTE: Python version was forced by RETICULATE_PYTHON
```
```
>utils::sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.25

loaded via a namespace (and not attached):
[1] compiler_4.2.1  Matrix_1.4-1    tools_4.2.1     rappdirs_0.3.3  Rcpp_1.0.9      grid_4.2.1      jsonlite_1.8.0  png_0.1-7       lattice_0.20-45`
```

**Comment by igorbrigadir** [comment]
I would advise against trying to run twarc via R. It's probably possible but unnecessary, since twarc can more easily be run in the operating system as yet another command line utility, outside of the R environment entirely.

You can get away with running twarc as a command line tool, and then import the dataframe into R, so instead of trying to install twarc inside rstudio with reticulate, it's easier to install Python and twarc in your operating system, so in windows provided you have Python installed, in Powershell:

```
pip3 install --upgrade twarc twarc-csv
twarc2 configure
```

and then whatever commands you need, like 

```
twarc2 search --limit 500 "dogs" dogs.jsonl
```

and convert to CSV to import into R for analysis:

```
twarc2 csv dogs.jsonl dogs.csv
```

**Comment by edsu** [comment]
Once installed you may also find it useful to run twarc as a system command in R, if you want to integrate data collection into some kind of data analysis pipeline that is written in R.

It is good to hear you are finding twarc useful for historical data collection, even if you are doing your main work in R!

**Comment by t-yamane-jp** [comment]
Thank you @igorbrigadir  for your advise. Installation worked in Powershell. 
Thank you for your message @edsu. I cannot figure out how to run twarc in R, but I think I will download twitter data in Powershell and save it as CSV and do only analysis in R. Thank you.

**Comment by edsu** [comment]
I don't use R but: https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/system
