### ISSUE TITLE
Ersatz full archive search, to bypass 3200-tweet limit

### ISSUE THREAD

**Issue by atomicthumbs** [DocNow/twarc#666]
If I'm reading the documentation right, any given command that would be most useful to archive a user's entire Tweet history is hindered by a 3200-tweet technical limit, for users without Academic Product Track access.  

I've successfully iterated through Twitter history on web by using Twitter's before/after date search features as a sort of sliding window of time. Would it be possible to add an option to the search/searches/timeline/timelines commands that automatically constructs multiple time-limited search queries, retrieving tweets one day, or one week, or so on, at a time, in order to achieve a more complete archive?  

This feature would be quite useful, given the current uncertainties about the website's future.

**Comment by edsu** [comment]
Yes, you are reading the docs right. twarc is really oriented around the Twitter API, so it is similarly constrained by endpoints and limitations of the API. You might want to take a look at a scraping tool like [snscrape](https://github.com/JustAnotherArchivist/snscrape) if you want to scrape the Twitter API.
