### ISSUE TITLE
Is it possible to convert twarc jsnol files to twarc2 jsonl files?

### ISSUE THREAD

**Issue by fishfree** [DocNow/twarc#692]
If so, how to do it, please?

**Comment by edsu** [comment]
Its theoretically possible, but its not something that twarc does currently. It also would be a lot or work for little gain. Why do you want to do this?!

**Comment by igorbrigadir** [comment]
The mapping from v1.1 API format to v2 API format is here if you want to take a stab at it: https://developer.twitter.com/en/docs/twitter-api/migrate/data-formats/standard-v1-1-to-v2 and in this interactive thing here too: https://visual-data-format-migration-tool.glitch.me/ 

However, it's infinitely easier to take a v1.1 dataset, dehydrate it, and hydrate it with twarc2:

```
twarc dehydrate some_dataset_in_v1.jsonl > ids.txt
twarc2 hydrate ids.txt dataset_in_v2.jsonl
```
