### ISSUE TITLE
twarc2 hydrate

### ISSUE THREAD

**Issue by frogger** [DocNow/twarc#697]
Hey, I am having real problems migrating to Twitter V2 since they pulled my app and I had to pay for a new one :( My current code doesn't work anymore and I tried twarc2 hydrate and got an invalid literal for int() error.  I stripped my data back to just the Tweet ids with no header etc and that seems to work however I am struggling to comprehend the output as it is completely different. Any advice would be appreciated, this is for my masters dissertation so I'm getting a bit stressed!!

**Comment by edsu** [comment]
Yes the Twitter API V2 data is quite different. You may be interested in "flattening" the data after collecting, which makes it a little bit easier to process. Some details are in: https://news.docnow.io/twarc2-779278e66ea0

**Comment by igorbrigadir** [comment]
Also check out twarc-csv for exploring: https://github.com/DocNow/twarc-csv but note that Excel does poorly with tweet and user IDs, so you have to be careful with making those all explicitly `TEXT` when importing, otherwise the data is corrupted. Google Sheets works though.
