### ISSUE TITLE
twarc2 hydrate freezes at 20%

### ISSUE THREAD

**Issue by frogger** [DocNow/twarc#698]
Hi,

I am trying to migrate my app from twarc to twarc2 and I am using hydrate. The file is from a pre-existing csv file that includes the tweet id and the date and time. It has not been collected using twarc. The problem that I have is that twarc2 freezes at around 20% on a sample of 7000 records. It worked fine with twarc. Is there a limit on how many tweets you can hydrate at one time?
Thanks

**Comment by frogger** [comment]
Ah yes it says:

2023-05-09 18:39:35,689 WARNING rate limit exceeded: sleeping 891.3103821277618 secs

**Comment by edsu** [comment]
If you wait it should start back up again.
