### ISSUE TITLE
Client forbidden

### ISSUE THREAD

**Issue by santoshbs** [DocNow/twarc#699]
For some reason, I am getting a "Client Forbidden" error no matter which of the following commands I use:

`twarc2 search --limit 10 "blacklivesmatter" results.jsonl`

`twarc2 search --archive --limit 10 "blacklivesmatter" results.jsonl`

This is after I have successfully completed `twarc2 configure`.

Much appreciate any advice on addressing this issue.

**Comment by myrainbowandsky** [comment]
I have exactly the same issue.

**Comment by santoshbs** [comment]
@myrainbowandsky - Looks like Twitter Academic APIs are deprecated. Not sure if that is the root cause of the client forbidden issue.

**Comment by edsu** [comment]
Your keys are expired -- sorry :-( Twitter sux.
