### ISSUE TITLE
Forbidden error after few tweets hydrated (403)

### ISSUE THREAD

**Issue by santoshbs** [DocNow/twarc#700]
For some reason, I am getting `Forbidden` error after twarc2 hydrates a few tweets.  I am using the below command:
`twarc2 --verbose hydrate _tmp/tmp_ids.txt tmp.json`

![image](https://github.com/DocNow/twarc/assets/20974015/826b3a87-ecc4-49f1-884b-89cc0da0ef12)

The log file had the following error:
`2023-08-01 16:24:54,569 ERROR Unexpected HTTP response: <Response [403]>
` 

Note that the configuration with bearer/api token all is fine. I was able to hydrate several thousand tweets yesterday. It is only today that I get this error.

Not sure how to debug and address this issue.

**Comment by santoshbs** [comment]
@edsu - I don't think I am over the usage limit.

![image](https://github.com/DocNow/twarc/assets/20974015/23ed398a-1f81-4682-a78d-9f88e6da988e)

**Comment by edsu** [comment]
Wow, yeah, looks like you're a-ok. I guess this is Enterprise access?

If you rerun command does it fail immediately, or at the same point in the hydration?

**Comment by santoshbs** [comment]
It looks it was an intermittent issue. It appears to work again - at least as of now. Thanks, @edsu for your attention,

**Comment by edsu** [comment]
Sure, it's actually good to hear that twarc is still operational for people who have API access.
