### ISSUE TITLE
emit twitter ids only

### ISSUE THREAD

**Issue by edsu** [DocNow/twarc#8]
It would be useful if twarc, or some similar command line tool, could only emit the tweet ids for a particular query. Apparently this is a popular-ish way for researchers to share twitter data sets without worrying about the ability to republish twitter data.

**Comment by raine** [comment]
This is easy with [ramda-cli](https://github.com/raine/ramda-cli). 
(Disclaimer: I am the author)

```
$ twarc --search 'query' | R '.id'
607153386128089100
606994440893263900
606957259223134200
...
```

or as a JSON array:

```
$ twarc --search 'ramda-cli' | R -s 'map (.id)'
[
  607153386128089100,
  606994440893263900,
  606957259223134200,
  605453205301018600,
  605450694091542500,
  605449859584409600,
  604727202123509800,
  604443334732615700,
  604052770430308400
]
```
